#!/bin/sh
# Xcode Cloud post-clone hook (Apple looks for ci_scripts/ next to the
# workspace). The repo intentionally does not commit build products, so a
# bare clone is missing everything the archive step needs:
#   - ios/App/App/public            (the compiled web app, from vite build)
#   - ios/App/App/capacitor.config.json  (generated by cap copy)
#   - ios/App/Pods                  (CocoaPods project the workspace references)
# Rebuild all three here, exactly like `npm run sync:native` + `pod install`
# do on a dev Mac. Fails loudly (set -e) so a broken web build stops the
# archive instead of shipping a stale shell.
#
# Every network-touching step is retried with backoff: Xcode Cloud runners
# intermittently drop connections to registry.npmjs.org and
# cdn.cocoapods.org ("Connection reset by peer - SSL_connect"), and one
# transient handshake failure must not kill a whole archive.
set -e
set -x

# retry <max> <cmd...>: run cmd up to <max> times, sleeping 10s, 20s, 30s...
# between attempts. POSIX sh (Xcode Cloud runs this with /bin/sh).
retry() {
  _max=$1
  shift
  _n=1
  while true; do
    "$@" && return 0
    if [ "$_n" -ge "$_max" ]; then
      echo "retry: '$*' failed after $_max attempts" >&2
      return 1
    fi
    sleep $((10 * _n))
    _n=$((_n + 1))
  done
}

cd "$CI_PRIMARY_REPOSITORY_PATH"

# Node: Xcode Cloud images ship Homebrew but not Node. (Vite 6 needs >=18;
# brew's current node satisfies that.)
export HOMEBREW_NO_AUTO_UPDATE=1
export HOMEBREW_NO_INSTALL_CLEANUP=1
retry 3 brew install node
node --version
npm --version

# Web app -> native shell. cap copy places the web assets and
# capacitor.config.json but runs NO pod install (cap sync would, and its
# embedded install failing on a CDN reset is exactly what killed archives);
# the pods get their own retry/fallback below instead.
retry 3 npm ci --no-audit --no-fund
npm run build
retry 3 npx cap copy ios

# CocoaPods. Plain install first; if the CDN keeps resetting, force a spec
# refresh once before giving up. The Podfile is committed, so plain install
# is all a clean runner needs.
export COCOAPODS_DISABLE_STATS=true
cd ios/App
retry 4 pod install || retry 2 pod install --repo-update

echo "ci_post_clone: web assets, capacitor config, and Pods ready"
