#!/bin/sh
# Xcode Cloud post-clone hook (Apple looks for ci_scripts/ next to the
# workspace). The repo intentionally does not commit build products, so a
# bare clone is missing everything the archive step needs:
#   - ios/App/App/public            (the compiled web app, from vite build)
#   - ios/App/App/capacitor.config.json  (generated by cap sync)
#   - ios/App/Pods                  (CocoaPods project the workspace references)
# Rebuild all three here, exactly like `npm run sync:native` + `pod install`
# do on a dev Mac. Fails loudly (set -e) so a broken web build stops the
# archive instead of shipping a stale shell.
set -e
set -x

cd "$CI_PRIMARY_REPOSITORY_PATH"

# Node: Xcode Cloud images ship Homebrew but not Node. (Vite 6 needs >=18;
# brew's current node satisfies that.)
export HOMEBREW_NO_AUTO_UPDATE=1
export HOMEBREW_NO_INSTALL_CLEANUP=1
brew install node
node --version
npm --version

# Web app -> native shell (same as npm run sync:native).
npm ci --no-audit --no-fund
npm run build
npx cap sync ios

# CocoaPods (cap sync already runs it when pod is available, but be explicit
# so a cap behavior change never silently skips it).
cd ios/App
pod install

echo "ci_post_clone: web assets, capacitor config, and Pods ready"
