/* FR UI strings, split out of langpacks.js so a child only downloads the
   language they actually use. Loaded on demand by platform/i18n.js; any key
   omitted here falls back to the inline English at the t() call site. */
export default {
        backpack: 'Sac à dos', home: 'Accueil', continue: 'Continuer', gotIt: 'Compris',
    nice: 'Bravo !', amazing: 'Fantastique ! {n} d’affilée !', notQuite: 'Pas tout à fait !', tryAgain: '— écoute et réessaie',
    yourTurn: "À toi de le dire !", levelUp: 'Niveau terminé !', levelComplete: 'Niveau terminé !', playAgain: 'Rejouer', listen: 'Écoute…',
            grownups: 'Pour les grands : progrès et astuces',     wordsTitle: 'Premiers Mots', whichStart: 'Par quelle lettre ça commence ?', readAndMatch: 'Lis le mot, puis touche son image', stoneFwd: 'Écoute ! Touche la lettre pour sauter !', stoneBack: 'Écoute ! Saute pour rentrer !', stoneTeach: 'Voici la lettre ! Touche-la en bas pour remonter Anbessa', stoneTray: 'Cartes de lettres', fixTitle: 'Presque !', fixBody: '{n} lettres veulent encore un peu d’entraînement. Maîtrise-les, puis réessaie !', fixCta: 'Entraîne les difficiles', fixReady: 'Bien joué !', fixReadyBody: 'Tu es prêt. Montre à ces lettres qui commande !', fixRetry: 'Retente le quiz', fixCapTitle: 'Bel entraînement aujourd’hui !', fixCapBody: 'Ces lettres deviennent plus fortes. La prochaine fois, on s’échauffe avec elles et on réussit le quiz !',
    popHint: 'Fais éclater la bulle !', familyDone: 'Famille maîtrisée !', traceHint: 'Écoute, puis trace la lettre avec ton doigt',
    hearIt: 'Réécouter', traceClear: 'Effacer', traceCheck: 'Vérifier', start: 'Départ', langText: "Langue de l'appli", langLearn: 'Langue à apprendre', langTitle: 'Langue', langSheetBody: 'Choisis l’alphabet à apprendre et la langue des textes de l’appli.', streakBody: 'Joue un peu chaque jour et la flamme grandit. Un jour manqué la fait repartir de zéro - garde-la allumée !', streakBest: 'Record : {n} jours', keepGoing: 'Continue !', buildWord: 'Touche les lettres dans l’ordre', rebuildWord: 'Construis le mot de l’image', wordsDoneTitle: 'Tu sais lire de nouveaux mots !', wordsDoneBody: '{n} nouveaux mots - Anbessa est fier !',
    teeTitle: 'Boutique T-shirt Anbessa', teeOrder: 'Commander un vrai t-shirt', teeSave: 'Enregistrer le motif',
    masterTitle: 'Maître du Fidel', masterChart: 'Tableau', masterAuto: 'Voix auto', masterAbugida: 'Abugida', masterPlayAbugida: "Lire tout l'Abugida",
    sayWithMe: 'Dis avec moi',     closetTitle: "L'armoire d'Anbessa", keepGoing: 'Continue !',
    back: 'Retour', playAll: 'Tout jouer', stop: 'Stop', pace_slow: 'Lent', pace_normal: 'Normal', pace_fast: 'Rapide',
    exploreHeader: 'Explorateur de Lettres', exploreHeaderSub: 'Choisis une voyelle, puis touche une famille pour l’entendre',
    exploreFamilyTitle: 'La famille {name}', exploreFamilySub: 'Sept formes, une lettre — touche pour entendre chacune',
    closetShort: 'Armoire', teeShort: 'Boutique T-shirt', wordsShort: 'Premiers Mots', explorerShort: 'Explorer', classicShort: 'Classique', practiceShort: 'Entraînement', familyShort: 'Famille', fvShort: 'Voix de Famille', nameShort: 'Mon nom', grownupsShort: 'Adultes', giftShort: 'Cadeau', reviewShort: 'Avis',
    nameTitle: 'Écris ton nom', nameSub: 'Épelle-le en Fidel, un son à la fois',
    nameHint: 'Choisis un son de voyelle ci-dessous, puis touche les lettres pour écrire ton nom.',
    namePlay: 'Entendre le nom', nameBackspace: 'Enlever la dernière lettre', nameClear: 'Effacer', nameVowel: 'Voyelle', nameLetters: 'Lettres', nameShare: 'Partager mon nom',
    namePrivacy: 'La carte est créée sur cet appareil. Rien n’est partagé sauf si tu touches Partager.',
    fvTitle: 'Voix de Famille', fvSub: 'Fais parler Anbessa avec la voix d’un proche', fvWhoSpeaks: 'Qui parle ?', fvDefault: 'Par défaut', fvImport: 'Importer une voix', fvForGrownups: 'Pour les grands', fvRecordBtn: 'Enregistrer une nouvelle voix', fvNoMic: 'L’enregistrement nécessite un microphone — utilise un téléphone ou une tablette.',
    streakDays: '{n} jours d’affilée', chapterDone: 'Chapitre {n} terminé !', earnedItem: 'Anbessa a obtenu {item} !', shareMilestone: '{name} a appris {n} lettres !',
    huntShort: 'Chasse du jour', huntTitle: 'Chasse aux lettres du jour', huntSub: 'Jibby a caché les lettres ! Trouve-les à l’oreille',
    huntFind: 'Trouve la lettre qui dit', huntListen: 'Réécouter le son', huntDoneTitle: 'Tu les as toutes trouvées !',
    huntTreasure: 'Ouvre le trésor', huntTomorrow: 'Reviens demain — Jibby cachera de nouvelles lettres !',
    huntFoundOne: 'trouvée', huntHidden: 'lettre cachée',
    pcShort: 'Carte postale', pcTitle: 'Carte postale vocale', pcSub: 'Envoie ta voix à quelqu’un que tu aimes',
    pcHint: 'Dis « Selam ! », dis tes nouvelles lettres ou chante — les grands-parents adorent t’entendre.',
    pcRecord: 'Enregistrer', pcStop: 'Stop', pcListen: 'Écouter', pcRedo: 'Réenregistrer', pcSend: 'Envoyer à la famille', pcSendAgain: 'Renvoyer',
    pcGateIntro: 'L’envoi est pour les grands — tu choisis qui la reçoit.', pcShared: 'Carte envoyée !', pcSaved: 'Enregistrée ! Partage-la où tu veux.',
    pcPrivacy: 'L’enregistrement reste sur cet appareil. Il ne voyage que si un adulte l’envoie.',
    celebPostcard: 'Envoie ça à la famille !',
    hol_enkutatash: 'Enkutatash — Bonne année !', hol_meskel: 'Meskel — la fête de la Croix', hol_genna: 'Genna — Joyeux Noël !', hol_timkat: 'Timkat — l’Épiphanie !', hol_adwa: 'Jour de la victoire d’Adwa', hol_eritrea: 'Fête de l’indépendance de l’Érythrée',
    planTitle: 'Le plan du jour', planNewShort: 'Nouvelle étape', planEta: 'À ce rythme, tu finis tout le Fidel pour le {date} !', planMake: 'Créer mon plan', planSetupTitle: 'Mon plan d’apprentissage', planSetupSub: 'Choisis un rythme - le coach te guide chaque jour', paceChill: 'Tranquille - 1 famille de lettres par semaine', paceSteady: 'Régulier - 2 familles par semaine', paceZoom: 'Zoom - 4 familles par semaine', planSave: 'Lancer mon plan', warmTitle: 'Échauffement', warmNudgeTitle: 'Échauffe-toi d’abord !', warmNudgeBody: 'Une petite révision de tes lettres, puis le jeu !', warmNudgeMustBody: 'Quelques lettres ont besoin d’entraînement. Un petit échauffement, puis on continue !', warmStart: 'Commencer l’échauffement', warmSkip: 'Jouer quand même', gpPlanTitle: 'Plan d’apprentissage', gpRequireWarmup: 'Exiger l’échauffement avant les jeux', gpRequireHint: 'Si activé, l’enfant doit finir la révision du jour avant de jouer.', gpWarmups: '{n} échauffements terminés',
    jcTitle: 'Rejoindre la classe de {who} ?', jcBody: 'L’appli ne retient la classe que sur cet appareil. Rien sur toi n’est envoyé nulle part.', jcJoin: 'Rejoindre la classe', jcJoined: 'Tu es dans la classe de {who} !', jcJoinedBody: 'Les devoirs de ton maître apparaîtront dans ton plan du jour.', jcShareText: 'Rejoins ma classe eGeez :',
    asTitle: 'Devoir', asFrom: '{who} a envoyé un devoir à votre classe !', asDetail: '{n} questions · pour le {date}', asStart: 'Commencer le devoir', asLater: 'Plus tard', asDoneTitle: 'Devoir terminé !', asScore: '{score} sur {n} du premier coup', asName: 'Ton nom (le maître le voit)', asSend: 'Envoyer le résultat au maître', asShareText: 'Devoir eGeez de votre maître :', asShareBack: 'Résultat eGeez pour {who} :',
    tmTitle: 'Outils de l’enseignant', tmSub: 'Liens de classe, devoirs, résultats — sans comptes', tmCreateTitle: 'Lancez votre classe', tmIntro: 'Faites tourner une classe avec de simples liens — sans comptes, sans serveur. Les élèves rejoignent en ouvrant un lien ; les résultats reviennent sous forme de liens.', tmYourName: 'Votre nom (les élèves le voient)', tmClassCode: 'Code de la classe (4–12 lettres ou chiffres)', tmCodePh: 'ex. STMARY1', tmCreate: 'Créer la classe', tmInvite: 'Inviter les élèves', tmInviteHint: 'Un élève ouvre ce lien une fois (ou scanne le code) — son appli rejoint votre classe. Marche par WhatsApp.', tmShareInvite: 'Partager le lien d’invitation', tmNewAssign: 'Devoir extra', tmAssignHint: 'Chaque élève reçoit les mêmes questions. À la fin, l’appli fabrique un lien de résultat qu’il vous renvoie.', tmPickFamilies: 'Familles de lettres', tmQuestions: 'Questions', tmDue: 'À rendre le', tmBuildLink: 'Fabriquer le lien', tmMakeLink: 'Partager le lien du devoir', tmRoster: 'Élèves', tmRosterEmpty: 'Pas encore de résultats. Quand un élève termine, il vous envoie un lien de résultat — ouvrez-le sur cet appareil et il se rangera ici.', tmBest: 'meilleur', tmReceiptFiled: 'Résultat enregistré : {who} — {score}', tmReceiptWrongClass: 'Ce résultat appartient à une classe qui n’est pas sur cet appareil.', tmRemove: 'Supprimer la classe et les résultats…', tmRemoveConfirm: 'Effacer cette classe et tous ses résultats de cet appareil ?', tmTv: 'Affichage TV', tmTvHint: 'Branchez cet appareil sur une TV : grandes lettres et son pour toute la classe, avec le code d’accès dans le coin.', tmTvOpen: 'Ouvrir l’affichage TV',
    tvExit: 'Quitter l’affichage TV', tvPrevFamily: 'Famille précédente', tvNextFamily: 'Famille suivante', tvPause: 'Mettre le chant en pause', tvPlay: 'Lancer le chant', tvJoin: 'Scanne pour rejoindre la classe',
    tmShort: 'Enseignant', parentsShort: 'Parents', tmLockTitle: 'Espace enseignant', tmLockBody: 'Entrez le code de votre classe pour l’ouvrir.', tmLockOpen: 'Ouvrir', tmLockWrong: 'Ce n’est pas le code de la classe.', tmPlanTitle: 'Plan du trimestre', tmPlanIntro: 'Choisissez combien de familles de lettres par semaine - tout le trimestre se met en place tout seul ; chaque semaine a sa leçon TV, son lien de devoir et sa liste de remises.', tmPerWeek: '{n} familles par semaine', tmPerWeekAny: 'Votre propre rythme (1-10)', tmPerWeekUnit: 'familles par semaine', tmPerWeekSet: 'Choisir', tmWeek: 'Semaine {n}', tmThisWeek: 'cette semaine', tmDueShort: 'pour le {date}', tmTeach: 'Leçon TV', tmHomework: 'Envoyer le devoir', tmShareAgain: 'Repartager le lien', tmTurnedIn: '{n} sur {total} rendus', tmMissing: 'manquent : {names}', tmNoneKnown: 'En attente du premier lien de résultat', tmChangePace: 'Changer le rythme', tmTroubleTitle: 'Lettres difficiles de la classe', tmTroubleEmpty: 'Rien pour l’instant - les lettres ratées arrivent dans les liens de résultat et se rassemblent ici.', tmTroubleWho: '{n} ratés · {names}', tmForms: 'Formes des lettres', tmOrdersBase: 'Lettres de base', tmOrdersAll: 'Les 7 formes', tmSent: 'Devoirs envoyés', tmExtra: 'Extra', tvChant: 'Chant', tvQuiz: 'Quiz', tvSay: 'Qui est-ce ?', tvSayAfter: 'Répétez après moi', tvYourTurn: 'À vous - dites-la !', tvChoose: 'Choisir les lettres', tvDone: 'Terminé', tvAll: 'Toutes', tvNone: 'Aucune', tvSayAfter: 'Répétez après moi', tvYourTurn: 'À vous - dites-la !', tvChoose: 'Choisir les lettres', tvDone: 'Terminé', tvAll: 'Toutes',     tmHowTitle: 'Comment ça marche', tmHow1: 'Créez votre classe une fois - elle vit sur ce téléphone, sans compte.', tmHow2: 'Invitez les élèves : ils ouvrent un lien ou scannent le code QR.', tmHow3: 'En classe : les lettres sur la TV - chantez ou faites le quiz ensemble.', tmHow4: 'Envoyez le lien du devoir de la semaine dans le groupe WhatsApp des familles.', tmHow5: 'Les résultats reviennent en liens - ouvrez-les ici et la liste se remplit toute seule.',
    challengeFrom: '{who} te défie !', challengeScored: '{who} a fait {score} % sur {level}. Peux-tu faire mieux ?',
    giftGot: 'Nouveau : {item} !', gpMastery: 'Maîtrise des lettres · {n} réponses enregistrées', gpReplayLevel: 'Rejouer le niveau {n}', gpTapNumber: 'Touche le nombre {word}',
    lettersUnlocked: '{n} / {total} lettres débloquées', // native review pending 
    
    teeLockedAt: 'Apprends {n} lettres', teeNext: 'Apprends encore {n} familles pour débloquer le prochain t-shirt !',
    aFriend: 'Un ami',
    bestStreak: 'Meilleure série',
    catchHint: 'Nourris Anbessa avant que Jibby ne l\'attrape !',
    ccApply: 'Valider',
    ccBlurb: 'Tu as un code d\'une église, d\'une école ou d\'un groupe ? Saisis-le pour qu\'ils soient crédités.',
    ccChange: 'Changer',
    ccPh: 'ex. DEBRE',
    ccThanks: 'Merci — tu soutiens',
    ccTitle: 'Code communautaire',
    challengeBack: 'Défier en retour',
    challengeFriend: 'Défier un ami',
    challengeGone: 'Ce défi n\'est plus disponible.',
    challengeLose: 'Si près !',
    challengeShareText: 'Bats mon score à eGeez ! Tu peux ?',
    challengeStart: 'Relever le défi',
    challengeTie: 'Égalité !',
    challengeTitle: 'Un défi !',
    challengeWin: 'Tu gagnes !',
    champion: 'Champion du Fidel - toutes les étoiles gagnées !',
    closetEmpty: 'Termine des leçons pour gagner des chapeaux, écharpes et capes pour Anbessa !',
    dailyGift: 'Ouvrir le cadeau d\'Anbessa',
    dismiss: 'Plus tard',
    feedHint: 'Fais glisser la lettre que dit Kokeb vers Anbessa',
    firstTry: 'Du premier coup',
    fvDefaultVoice: 'Revenir à la voix par défaut',
    fvDelete: 'Supprimer la voix',
    fvEmpty: 'Pas encore de voix de famille. Enregistres-en une, ou importe la voix qu\'un proche t\'a envoyée.',
    fvGateIntro: 'L\'enregistrement est pour les grands — il utilise le micro.',
    fvGreetingShort: 'Coucou !',
    fvGreetingSlot: 'Salutation',
    fvImportFail: 'Ce fichier n\'est pas une voix eGeez.',
    fvImported: 'Voix importée !',
    fvNameLabel: 'Nom de la voix',
    fvNamePh: 'La voix de qui ? ex. Mamie',
    fvNowSpeaking: 'Anbessa parle maintenant avec cette voix',
    fvPrivacy: 'Les voix restent sur cet appareil. Rien n\'est envoyé — une voix ne voyage que dans le fichier que tu choisis de partager.',
    fvRecordBlurb: 'Enregistre les lettres avec ta propre voix, puis partage le fichier avec ton enfant par WhatsApp. Un grand-parent loin peut enregistrer pour les enfants ici — et vice versa.',
    fvRecordHint: 'Touche une lettre pour l\'enregistrer, retouche pour arrêter. Touche ✓ pour la réécouter.',
    fvRecordTitle: 'Enregistre ta voix',
    fvShare: 'Partager avec un enfant',
    fvUseVoice: 'L\'utiliser ici',
    giftAllDone: 'Tu as tout collectionné - trop contente que tu sois revenu !',
    giftTitle: 'Un cadeau d\'Anbessa !',
    goHome: 'Accueil',
    gpAccuracy: 'Précision',
    gpCorrect: 'correct',
    gpHold: 'Maintiens-moi',
    gpHoldHint: 'Appuie et maintiens deux secondes',
    gpIntro: 'Cette zone est pour les grands : détails des progrès et conseils.',
    gpLessonStars: 'Étoiles des leçons',
    gpMasteryLegend: 'Vert : solide · Jaune : en progrès · Rouge : à revoir · Gris : pas encore travaillé. Les quiz travaillent pour l\'instant les lettres du premier ordre.',
    gpOpenExplorer: 'Ouvrir dans l\'Explorateur',
    gpPlayerName: 'Nom du joueur',
    gpPlayerNameHint: 'Affiché sur les défis envoyés aux amis. Facultatif — laisse vide pour rester « Un ami ». Il ne quitte jamais cet appareil, sauf dans un lien de défi que tu choisis de partager.',
    gpPlayerNamePh: 'ex. Selam',
    gpReset: 'Effacer tous les progrès…',
    gpResetConfirm: 'Effacer étoiles, records, îles et historique d\'apprentissage ?',
    gpResetNo: 'Garder',
    gpUnlockAll: 'Tout debloquer (pour tester)…',
    gpUnlockConfirm: 'Ouvrir tous les niveaux, iles et lettres pour tester ?',
    gpUnlockYes: 'Oui, tout ouvrir',
    paySupport: 'Soutenir eGeez', payTitle: 'Continuez à apprendre avec eGeez', payBody: 'Votre essai gratuit de {n} jours est terminé. Acheter l\u2019appli la garde active pour votre enfant - et la fait grandir.', payLeft: 'Essai gratuit : {n} jours restants', payEnded: 'Votre essai gratuit est terminé.', payBuy: 'Acheter l\u2019appli', payFamily: 'Demander à la famille de l\u2019offrir', payFamilyHint: 'Aucun moyen de payer là où vous vivez ? Un proche n\u2019importe où dans le monde peut l\u2019offrir - partagez ceci avec lui.', payShareText: 'Nos enfants apprennent l\u2019alphabet éthiopien avec eGeez. Pourriez-vous nous offrir l\u2019appli ?', payFeedback: 'Vous n\u2019achetez pas ? Dites-nous franchement pourquoi', payFeedbackHint: 'Un avis honnête donne {n} jours gratuits de plus.', payFeedbackBody: 'Ce qu\u2019on a aimé :\n\nCe qui devrait être mieux :\n\nPourquoi on n\u2019a pas acheté :\n', payFeedbackDone: 'Merci ! {n} jours gratuits ajoutés.', payOwned: 'Ma famille l\u2019a déjà achetée', payThanks: 'Merci de soutenir eGeez !', gpMoveTitle: 'Passer sur un autre téléphone', gpMoveHint: 'Enregistrez toute la progression dans un petit fichier, envoyez-le au nouveau téléphone (WhatsApp fonctionne), puis chargez-le là-bas.', gpExport: 'Enregistrer le fichier de progression', gpImport: 'Charger le fichier de progression', swUpdate: 'Nouvelle version prête - touchez pour mettre à jour',
    gpResetYes: 'Oui, effacer',
    gpRunnerBest: 'Record du Runner',
    gpTrouble: 'Lettres difficiles',
    gpTroubleFew: 'Pas encore assez joué — reviens après quelques parties.',
    gpTroubleNone: 'Aucune lettre difficile pour l\'instant. Bravo !',
    grownupsSub: 'Progrès, lettres difficiles et conseils de pratique',
    installCta: 'Ajouter',
    installHow: 'Comment ?',
    installIosHint: 'Touche le bouton Partager, puis « Sur l\'écran d\'accueil »',
    installTitle: 'Ajoute Anbessa à ton écran d\'accueil',
    jumpToStep: 'Aller à mon étape suivante',
    learnSub: 'Apprends chaque lettre, une étape à la fois',
    learnTitle: 'Les étapes des lettres',
    level: 'Niveau',
    linkCopied: 'Lien copié !',
    masterInOrder: 'Dans l\'ordre',
    masterLetters: 'lettres',
    masterMixed: 'Mélangées',
    masterPause: 'Pause',
    masterPlay: 'Lire',
    masterReshuffle: 'Remélanger',
    mixDone: 'Beau mélange !',
    muncherWins: 'Miam !', munched: 'Miam !',
    myStep: 'Mon étape',
    newReward: 'Nouveau !',
    nextVowel: 'Puis la voyelle suivante',
    openCloset: 'Ouvrir la garde-robe d\'Anbessa',
    practiceComplete: 'Entraînement terminé !',
    practicePraise: 'Ces lettres difficiles deviennent plus fortes. Kokeb est fier de toi !',
    remindBody: 'Viens apprendre une lettre aujourd\'hui.',
    remindDesc: 'Un petit rappel chaque après-midi pour garder la série.',
    remindTitle: 'Anbessa s\'ennuie de toi !',
    remindTitleLabel: 'Rappel quotidien',
    runAgain: 'Recourir',
    runBest: 'Record',
    runBossAttack: 'Jibby la hyène attaque !',
    runBossWin: 'Le pouvoir des lettres d\'Anbessa gagne !',
    runMoveLeft: 'Aller à gauche',
    runMoveRight: 'Aller à droite',
    runNewBest: 'Nouveau record !',
    runQuit: 'Quitter la course',
    saysWord: 'dit',
    scopeAll: 'Toutes les lettres',
    scopeLabel: 'Quelles lettres',
    scopeLearned: 'Mes lettres',
    shareAnbessa: 'Partager Anbessa',
    shareSaved: 'Enregistré ! Partage-le partout.',
    shareShowOff: 'Montre à tout le monde !',
    shareThanks: 'Merci d\'avoir partagé !',
    
    
    
    
    
    
    
        steerInto: 'Dirige Anbessa vers',
    teeGrownup: 'Commander ouvre une boutique — demande à un grand.',
    teeIntro: 'Gagne un nouveau design de t-shirt à chaque chapitre — Anbessa porte ton alphabet ! Enregistre l\'image ou demande à un grand de commander un vrai t-shirt.',
    teeOrdered: 'Ouverture de la boutique pour un grand...',
    teeSaveHint: 'Enregistre l\'image et imprime-la sur n\'importe quel t-shirt.',
    teeSaved: 'Design enregistré ! Imprime-le partout.',
    teeUnlocked: 'Débloqué !',
    whichLetter: 'Quelle lettre dit',
    you: 'Toi',
}
