/* IT UI strings, split out of langpacks.js so a child only downloads the
   language they actually use. Loaded on demand by platform/i18n.js; any key
   omitted here falls back to the inline English at the t() call site. */
export default {
        backpack: 'Zaino', home: 'Home', continue: 'Continua', gotIt: 'Capito',
    nice: 'Bravo!', amazing: 'Fantastico! {n} di fila!', notQuite: 'Non proprio!', tryAgain: '— ascolta e riprova',
    yourTurn: 'Ora tocca a te!', levelUp: 'Livello completato!', levelComplete: 'Livello completato!', playAgain: 'Gioca ancora', listen: 'Ascolta…',
            grownups: 'Per i grandi: progressi e consigli',     wordsTitle: 'Prime Parole', whichStart: 'Con quale lettera inizia?', readAndMatch: 'Leggi la parola, poi tocca la sua figura', stoneFwd: 'Ascolta! Tocca la lettera per saltare!', stoneBack: 'Ascolta! Salta di nuovo a casa!', stoneTeach: 'Ecco la lettera! Toccala qui sotto per tirare su Anbessa', stoneTray: 'Carte delle lettere', fixTitle: 'Quasi!', fixBody: '{n} lettere vogliono ancora un po’ di pratica. Imparale bene, poi riprova!', fixCta: 'Allena quelle difficili', fixReady: 'Ottima pratica!', fixReadyBody: 'Sei pronto. Fai vedere a quelle lettere chi comanda!', fixRetry: 'Riprova il quiz', fixCapTitle: 'Ottimo allenamento oggi!', fixCapBody: 'Queste lettere stanno diventando piu’ forti. La prossima volta ci riscaldiamo con loro e superiamo il quiz!',
    popHint: 'Fai scoppiare la bolla!', familyDone: 'Famiglia imparata!', traceHint: 'Ascolta, poi traccia la lettera con il dito',
    hearIt: 'Ascolta ancora', traceClear: 'Cancella', traceCheck: 'Controlla', start: 'Inizia', langText: 'Lingua app', langLearn: 'Lingua da imparare', langTitle: 'Lingua', langSheetBody: 'Scegli l’alfabeto da imparare e la lingua dei testi dell’app.', streakBody: 'Gioca un po’ ogni giorno e la fiamma cresce. Salta un giorno e riparte da zero - tienila accesa!', streakBest: 'Record: {n} giorni', keepGoing: 'Continua così!', buildWord: 'Tocca le lettere in ordine', rebuildWord: 'Costruisci la parola per la figura', wordsDoneTitle: 'Sai leggere parole nuove!', wordsDoneBody: '{n} parole nuove - Anbessa è fiero!',
    teeTitle: 'Negozio T-shirt Anbessa', teeOrder: 'Ordina una vera maglietta', teeSave: 'Salva il disegno',
    masterTitle: 'Maestro del Fidel', masterChart: 'Tabella', masterAuto: 'Voce auto', masterAbugida: 'Abugida', masterPlayAbugida: "Riproduci tutto l'Abugida",
    sayWithMe: 'Dillo con me',     closetTitle: 'Armadio di Anbessa', keepGoing: 'Continua così!',
    back: 'Indietro', playAll: 'Riproduci tutto', stop: 'Ferma', pace_slow: 'Lento', pace_normal: 'Normale', pace_fast: 'Veloce',
    exploreHeader: 'Esploratore di Lettere', exploreHeaderSub: 'Scegli una vocale, poi tocca una famiglia per ascoltarla',
    exploreFamilyTitle: 'La famiglia {name}', exploreFamilySub: 'Sette forme, una lettera — tocca per ascoltare ognuna',
    closetShort: 'Armadio', teeShort: 'Negozio T-shirt', wordsShort: 'Prime Parole', explorerShort: 'Esplora', classicShort: 'Classico', practiceShort: 'Pratica', familyShort: 'Famiglia', fvShort: 'Voce di Famiglia', nameShort: 'Il mio nome', grownupsShort: 'Adulti', giftShort: 'Regalo', reviewShort: 'Recensione',
    nameTitle: 'Scrivi il tuo nome', nameSub: 'Scrivilo in Fidel, un suono alla volta',
    nameHint: 'Scegli una vocale qui sotto, poi tocca le lettere per scrivere il tuo nome.',
    namePlay: 'Ascolta il nome', nameBackspace: 'Togli l’ultima lettera', nameClear: 'Cancella', nameVowel: 'Vocale', nameLetters: 'Lettere', nameShare: 'Condividi il mio nome',
    namePrivacy: 'La scheda è creata su questo dispositivo. Niente viene condiviso finché non tocchi Condividi.',
    fvTitle: 'Voce di Famiglia', fvSub: 'Fai parlare Anbessa con la voce di una persona cara', fvWhoSpeaks: 'Chi parla?', fvDefault: 'Predefinita', fvImport: 'Importa una voce', fvForGrownups: 'Per i grandi', fvRecordBtn: 'Registra una nuova voce', fvNoMic: 'La registrazione richiede un microfono — usa un telefono o un tablet.',
    streakDays: '{n} giorni di fila', chapterDone: 'Capitolo {n} completato!', earnedItem: 'Anbessa ha ottenuto {item}!', shareMilestone: '{name} ha imparato {n} lettere!',
    huntShort: 'Caccia del giorno', huntTitle: 'Caccia alle lettere del giorno', huntSub: 'Jibby ha nascosto le lettere! Trovale con l’orecchio',
    huntFind: 'Trova la lettera che dice', huntListen: 'Riascolta il suono', huntDoneTitle: 'Le hai trovate tutte!',
    huntTreasure: 'Apri il tesoro', huntTomorrow: 'Torna domani — Jibby nasconderà nuove lettere!',
    huntFoundOne: 'trovata', huntHidden: 'lettera nascosta',
    pcShort: 'Cartolina', pcTitle: 'Cartolina vocale', pcSub: 'Manda la tua voce a chi ami',
    pcHint: 'Di’ «Selam!», di’ le tue lettere nuove o canta — i nonni adorano sentirti.',
    pcRecord: 'Registra', pcStop: 'Ferma', pcListen: 'Ascolta', pcRedo: 'Registra di nuovo', pcSend: 'Invia alla famiglia', pcSendAgain: 'Invia di nuovo',
    pcGateIntro: 'L’invio è per i grandi — scegli tu chi la riceve.', pcShared: 'Cartolina inviata!', pcSaved: 'Salvata! Condividila dove vuoi.',
    pcPrivacy: 'La registrazione resta su questo dispositivo. Parte solo quando un adulto la invia.',
    celebPostcard: 'Mandalo alla famiglia!',
    hol_enkutatash: 'Enkutatash — Buon anno!', hol_meskel: 'Meskel — la festa della Croce', hol_genna: 'Genna — Buon Natale!', hol_timkat: 'Timkat — Epifania!', hol_adwa: 'Giorno della vittoria di Adwa', hol_eritrea: 'Festa dell’indipendenza eritrea',
    planTitle: 'Piano di oggi', planNewShort: 'Nuovo passo', planEta: 'A questo ritmo finisci tutto il Fidel entro il {date}!', planMake: 'Crea il mio piano', planSetupTitle: 'Il mio piano di studio', planSetupSub: 'Scegli un ritmo - il coach ti guida ogni giorno', paceChill: 'Tranquillo - 1 famiglia a settimana', paceSteady: 'Costante - 2 famiglie a settimana', paceZoom: 'Zoom - 4 famiglie a settimana', planSave: 'Inizia il mio piano', warmTitle: 'Riscaldamento', warmNudgeTitle: 'Prima riscaldati!', warmNudgeBody: 'Un ripasso veloce delle tue lettere, poi il gioco!', warmNudgeMustBody: 'Alcune lettere hanno bisogno di più pratica. Prima un riscaldamento veloce, poi avanti!', warmStart: 'Inizia il riscaldamento', warmSkip: 'Gioca lo stesso', gpPlanTitle: 'Piano di studio', gpRequireWarmup: 'Richiedi il riscaldamento prima dei giochi', gpRequireHint: 'Se attivo, il bambino deve finire il ripasso del giorno prima di giocare.', gpWarmups: '{n} riscaldamenti completati',
    jcTitle: 'Vuoi unirti alla classe di {who}?', jcBody: 'L’app ricorda la classe solo su questo dispositivo. Nulla su di te viene inviato da nessuna parte.', jcJoin: 'Unisciti alla classe', jcJoined: 'Sei nella classe di {who}!', jcJoinedBody: 'I compiti del tuo maestro appariranno nel tuo piano quotidiano.', jcShareText: 'Unisciti alla mia classe di eGeez:',
    asTitle: 'Compito', asFrom: '{who} ha mandato i compiti alla vostra classe!', asDetail: '{n} domande · entro il {date}', asStart: 'Inizia il compito', asLater: 'Più tardi', asDoneTitle: 'Compito finito!', asScore: '{score} su {n} al primo tentativo', asName: 'Il tuo nome (il maestro lo vede)', asSend: 'Invia il risultato al maestro', asShareText: 'Compito di eGeez dal vostro maestro:', asShareBack: 'Risultato di eGeez per {who}:',
    tmTitle: 'Strumenti per insegnanti', tmSub: 'Link di classe, compiti, risultati — senza account', tmCreateTitle: 'Avvia la tua classe', tmIntro: 'Gestisci una classe solo con link — senza account, senza server. Gli alunni si uniscono aprendo un link; i risultati tornano come link.', tmYourName: 'Il tuo nome (gli alunni lo vedono)', tmClassCode: 'Codice della classe (4–12 lettere o cifre)', tmCodePh: 'es. STMARY1', tmCreate: 'Crea la classe', tmInvite: 'Invita gli alunni', tmInviteHint: 'Un alunno apre questo link una volta (o scansiona il codice) — la sua app si unisce alla tua classe. Funziona su WhatsApp.', tmShareInvite: 'Condividi il link di invito', tmNewAssign: 'Compito extra', tmAssignHint: 'Ogni alunno riceve le stesse domande. Alla fine l’app crea un link con il risultato da rimandarti.', tmPickFamilies: 'Famiglie di lettere', tmQuestions: 'Domande', tmDue: 'Scadenza', tmBuildLink: 'Crea il link', tmMakeLink: 'Condividi il link del compito', tmRoster: 'Alunni', tmRosterEmpty: 'Ancora nessun risultato. Quando un alunno finisce, ti manda un link — aprilo su questo dispositivo e verrà registrato qui.', tmBest: 'migliore', tmReceiptFiled: 'Risultato salvato: {who} — {score}', tmReceiptWrongClass: 'Questo risultato appartiene a una classe che non è su questo dispositivo.', tmRemove: 'Rimuovi classe e risultati…', tmRemoveConfirm: 'Cancellare questa classe e tutti i suoi risultati da questo dispositivo?', tmTv: 'Schermo TV', tmTvHint: 'Collega questo dispositivo a una TV: lettere grandi e audio per tutta la classe, con il codice di accesso nell’angolo.', tmTvOpen: 'Apri lo schermo TV',
    tvExit: 'Esci dallo schermo TV', tvPrevFamily: 'Famiglia precedente', tvNextFamily: 'Famiglia successiva', tvPause: 'Metti in pausa il canto', tvPlay: 'Avvia il canto', tvJoin: 'Scansiona per unirti alla classe',
    tmShort: 'Maestro', parentsShort: 'Genitori', tmLockTitle: 'Area insegnante', tmLockBody: 'Inserisci il codice della tua classe per aprirla.', tmLockOpen: 'Apri', tmLockWrong: 'Questo non è il codice della classe.', tmPlanTitle: 'Piano del trimestre', tmPlanIntro: 'Scegli quante famiglie di lettere a settimana - tutto il trimestre si dispone da solo; ogni settimana ha la sua lezione in TV, il suo link dei compiti e la lista delle consegne.', tmPerWeek: '{n} famiglie a settimana', tmPerWeekAny: 'Il tuo ritmo (1-10)', tmPerWeekUnit: 'famiglie a settimana', tmPerWeekSet: 'Imposta', tmWeek: 'Settimana {n}', tmThisWeek: 'questa settimana', tmDueShort: 'entro il {date}', tmTeach: 'Lezione in TV', tmHomework: 'Manda i compiti', tmShareAgain: 'Condividi di nuovo il link', tmTurnedIn: '{n} su {total} consegnati', tmMissing: 'mancano: {names}', tmNoneKnown: 'In attesa del primo link con i risultati', tmChangePace: 'Cambia ritmo', tmTroubleTitle: 'Lettere difficili della classe', tmTroubleEmpty: 'Ancora niente - le lettere sbagliate arrivano nei link dei risultati e si raccolgono qui.', tmTroubleWho: '{n} errori · {names}', tmForms: 'Forme delle lettere', tmOrdersBase: 'Lettere base', tmOrdersAll: 'Tutte e 7 le forme', tmSent: 'Compiti inviati', tmExtra: 'Extra', tvChant: 'Canto', tvQuiz: 'Quiz', tvSay: 'Chi è questo?', tvSayAfter: 'Ripetete dopo di me', tvYourTurn: 'Tocca a voi - ditelo!', tvChoose: 'Scegli le lettere', tvDone: 'Fatto', tvAll: 'Tutte', tvNone: 'Nessuna', tvSayAfter: 'Ripetete dopo di me', tvYourTurn: 'Tocca a voi - ditelo!', tvChoose: 'Scegli le lettere', tvDone: 'Fatto', tvAll: 'Tutte',     tmHowTitle: 'Come funziona', tmHow1: 'Crea la tua classe una volta - vive su questo telefono, senza account.', tmHow2: 'Invita gli alunni: aprono un link o scansionano il codice QR.', tmHow3: 'In classe metti le lettere sulla TV - cantate o fate il quiz insieme.', tmHow4: 'Manda il link dei compiti della settimana nel gruppo WhatsApp delle famiglie.', tmHow5: 'I risultati tornano come link - aprili qui e il registro si riempie da solo.',
    challengeFrom: '{who} ti sfida!', challengeScored: '{who} ha fatto {score}% in {level}. Riesci a batterlo?',
    giftGot: 'Novità: {item}!', gpMastery: 'Padronanza delle lettere · {n} risposte registrate', gpReplayLevel: 'Rigioca il livello {n}', gpTapNumber: 'Tocca il numero {word}',
    lettersUnlocked: '{n} / {total} lettere sbloccate', // native review pending 
    
    teeLockedAt: 'Impara {n} lettere', teeNext: 'Impara altre {n} famiglie per sbloccare la prossima maglietta!',
    aFriend: 'Un amico',
    bestStreak: 'Serie migliore',
    catchHint: 'Nutri Anbessa prima che Jibby lo prenda!',
    ccApply: 'Applica',
    ccBlurb: 'Hai un codice da una chiesa, scuola o gruppo della comunità? Inseriscilo per dare loro il merito.',
    ccChange: 'Cambia',
    ccPh: 'es. DEBRE',
    ccThanks: 'Grazie — stai sostenendo',
    ccTitle: 'Codice comunità',
    challengeBack: 'Rilancia la sfida',
    challengeFriend: 'Sfida un amico',
    challengeGone: 'Questa sfida non è disponibile.',
    challengeLose: 'Per un pelo!',
    challengeShareText: 'Batti il mio punteggio a eGeez! Ci riesci?',
    challengeStart: 'Accetta la sfida',
    challengeTie: 'È un pareggio!',
    challengeTitle: 'Una sfida!',
    challengeWin: 'Hai vinto!',
    champion: 'Campione del Fidel - ogni stella guadagnata!',
    closetEmpty: 'Finisci le lezioni per guadagnare cappelli, sciarpe e mantelli per Anbessa!',
    dailyGift: 'Apri il regalo di Anbessa',
    dismiss: 'Non ora',
    feedHint: 'Trascina la lettera che dice Kokeb verso Anbessa',
    firstTry: 'Al primo colpo',
    fvDefaultVoice: 'Torna alla voce predefinita',
    fvDelete: 'Elimina voce',
    fvEmpty: 'Ancora nessuna voce di famiglia. Registrane una, o importa una voce che ti ha mandato un parente.',
    fvGateIntro: 'La registrazione è per i grandi — usa il microfono.',
    fvGreetingShort: 'Ciao!',
    fvGreetingSlot: 'Saluto',
    fvImportFail: 'Questo file non è una voce di eGeez.',
    fvImported: 'Voce importata!',
    fvNameLabel: 'Nome della voce',
    fvNamePh: 'Di chi è la voce? es. Nonna',
    fvNowSpeaking: 'Anbessa ora parla con questa voce',
    fvPrivacy: 'Le voci restano su questo dispositivo. Niente viene caricato — una voce viaggia solo nel file che scegli di condividere.',
    fvRecordBlurb: 'Registra le lettere con la tua voce, poi condividi il file con il tuo bambino via WhatsApp. Un nonno lontano può registrare per i bambini qui — e viceversa.',
    fvRecordHint: 'Tocca una lettera per registrarla, tocca di nuovo per fermare. Tocca ✓ per riascoltarla.',
    fvRecordTitle: 'Registra la tua voce',
    fvShare: 'Condividi con un bambino',
    fvUseVoice: 'Usala qui',
    giftAllDone: 'Hai raccolto tutto - che bello che sei tornato!',
    giftTitle: 'Un regalo da Anbessa!',
    goHome: 'Home',
    gpAccuracy: 'Precisione',
    gpCorrect: 'corretti',
    gpHold: 'Tienimi premuto',
    gpHoldHint: 'Premi e tieni premuto per due secondi',
    gpIntro: 'Quest\'area è per i grandi: dettagli sui progressi e consigli per esercitarsi.',
    gpLessonStars: 'Stelle delle lezioni',
    gpMasteryLegend: 'Verde: solido · Giallo: quasi · Rosso: serve aiuto · Grigio: non ancora esercitato. I quiz al momento esercitano le lettere di prim\'ordine.',
    gpOpenExplorer: 'Apri in Esploratore',
    gpPlayerName: 'Nome giocatore',
    gpPlayerNameHint: 'Mostrato nelle sfide che mandi agli amici. Facoltativo — lascialo vuoto per restare "Un amico". Non lascia mai questo dispositivo se non dentro un link di sfida che scegli di condividere.',
    gpPlayerNamePh: 'es. Selam',
    gpReset: 'Azzera tutti i progressi…',
    gpResetConfirm: 'Cancellare stelle, record, isole e cronologia di apprendimento?',
    gpResetNo: 'Tieni tutto',
    gpUnlockAll: 'Sblocca tutto (per i test)…',
    gpUnlockConfirm: 'Aprire tutti i livelli, le isole e le lettere per i test?',
    gpUnlockYes: 'Si, apri tutto',
    paySupport: 'Sostieni eGeez', payTitle: 'Continua a imparare con eGeez', payBody: 'La vostra prova gratuita di {n} giorni è finita. Comprare l\u2019app la tiene attiva per il vostro bambino - e la fa crescere.', payLeft: 'Prova gratuita: {n} giorni rimasti', payEnded: 'La vostra prova gratuita è finita.', payBuy: 'Compra l\u2019app', payFamily: 'Chiedi alla famiglia di regalarla', payFamilyHint: 'Nessun modo di pagare dove vivete? Un parente ovunque nel mondo può regalarla - condividete questo con lui.', payShareText: 'I nostri bambini imparano l\u2019alfabeto etiope con eGeez. Potreste regalarci l\u2019app?', payFeedback: 'Non comprate? Diteci onestamente perché', payFeedbackHint: 'Un parere onesto vale {n} giorni gratis in più.', payFeedbackBody: 'Cosa ci è piaciuto:\n\nCosa migliorare:\n\nPerché non l\u2019abbiamo comprata:\n', payFeedbackDone: 'Grazie! Aggiunti altri {n} giorni gratis.', payOwned: 'La mia famiglia l\u2019ha già comprata', payThanks: 'Grazie per sostenere eGeez!', gpMoveTitle: 'Passa a un altro telefono', gpMoveHint: 'Salva tutti i progressi come un piccolo file, invialo al nuovo telefono (WhatsApp va bene), poi caricalo lì.', gpExport: 'Salva file dei progressi', gpImport: 'Carica file dei progressi', swUpdate: 'Nuova versione pronta - tocca per aggiornare',
    gpResetYes: 'Sì, cancella',
    gpRunnerBest: 'Record Corsa',
    gpTrouble: 'Lettere difficili',
    gpTroubleFew: 'Ancora troppo poco gioco — ricontrolla dopo qualche partita.',
    gpTroubleNone: 'Nessuna lettera difficile ora. Bravo!',
    grownupsSub: 'Progressi, lettere difficili e consigli per esercitarsi',
    installCta: 'Aggiungi',
    installHow: 'Come?',
    installIosHint: 'Tocca il pulsante Condividi, poi \'Aggiungi a Home\'',
    installTitle: 'Aggiungi Anbessa alla tua schermata Home',
    jumpToStep: 'Vai al mio prossimo passo',
    learnSub: 'Impara ogni lettera, un passo alla volta',
    learnTitle: 'Passi delle Lettere',
    level: 'Livello',
    linkCopied: 'Link copiato!',
    masterInOrder: 'In ordine',
    masterLetters: 'lettere',
    masterMixed: 'Mescolate',
    masterPause: 'Pausa',
    masterPlay: 'Play',
    masterReshuffle: 'Rimescola',
    mixDone: 'Bella mescolata!',
    muncherWins: 'Sgranocchiato!', munched: 'Sgranocchiato!',
    myStep: 'Il mio passo',
    newReward: 'Nuovo!',
    nextVowel: 'Poi la vocale seguente',
    openCloset: 'Apri l\'Armadio di Anbessa',
    practiceComplete: 'Esercizio completato!',
    practicePraise: 'Quelle lettere difficili stanno diventando più forti. Kokeb è fiero di te!',
    remindBody: 'Vieni a imparare una lettera oggi.',
    remindDesc: 'Una gentile spinta ogni pomeriggio per non perdere la serie.',
    remindTitle: 'Anbessa ti manca!',
    remindTitleLabel: 'Promemoria giornaliero',
    runAgain: 'Corri di nuovo',
    runBest: 'Record',
    runBossAttack: 'Jibby la iena attacca!',
    runBossWin: 'Il potere delle lettere di Anbessa vince!',
    runMoveLeft: 'Vai a sinistra',
    runMoveRight: 'Vai a destra',
    runNewBest: 'Nuovo record!',
    runQuit: 'Esci dalla corsa',
    saysWord: 'dice',
    scopeAll: 'Tutte le lettere',
    scopeLabel: 'Quali lettere',
    scopeLearned: 'Le mie lettere',
    shareAnbessa: 'Condividi Anbessa',
    shareSaved: 'Salvato! Condividilo ovunque.',
    shareShowOff: 'Mostralo a tutti!',
    shareThanks: 'Grazie per aver condiviso!',
    
    
    
    
    
    
    
        steerInto: 'Guida Anbessa verso',
    teeGrownup: 'Ordinare apre un negozio — chiedi a un grande.',
    teeIntro: 'Guadagna un nuovo disegno di maglietta a ogni capitolo — Anbessa indossa il tuo alfabeto! Salva l\'immagine o chiedi a un grande di ordinare una maglietta vera.',
    teeOrdered: 'Apro il negozio per un grande...',
    teeSaveHint: 'Salva l\'immagine e stampala su qualsiasi maglietta.',
    teeSaved: 'Disegno salvato! Stampalo ovunque.',
    teeUnlocked: 'Sbloccato!',
    whichLetter: 'Quale lettera dice',
    you: 'Tu',
}
