/* NL UI strings, split out of langpacks.js so a child only downloads the
   language they actually use. Loaded on demand by platform/i18n.js; any key
   omitted here falls back to the inline English at the t() call site. */
export default {
        backpack: 'Rugzak', home: 'Home', continue: 'Verder', gotIt: 'Begrepen',
    nice: 'Goed zo!', amazing: 'Geweldig! {n} op een rij!', notQuite: 'Net niet!', tryAgain: '— luister en probeer opnieuw',
    yourTurn: 'Nu zeg jij het!', levelUp: 'Level voltooid!', levelComplete: 'Level voltooid!', playAgain: 'Opnieuw spelen', listen: 'Luister…',
            grownups: 'Voor volwassenen: voortgang en tips',     wordsTitle: 'Eerste woorden', whichStart: 'Met welke letter begint het?', readAndMatch: 'Lees het woord en tik dan op het plaatje', stoneFwd: 'Luister! Tik op de letter en spring over!', stoneBack: 'Luister! Spring terug naar huis!', stoneTeach: 'Dit is de letter! Tik erop hieronder om Anbessa omhoog te trekken', stoneTray: 'Letterkaarten', fixTitle: 'Bijna!', fixBody: '{n} letters willen nog wat oefening. Beheers ze en probeer het opnieuw!', fixCta: 'Oefen de lastige', fixReady: 'Goed geoefend!', fixReadyBody: 'Je bent er klaar voor. Laat die letters zien wie de baas is!', fixRetry: 'Probeer de quiz opnieuw', fixCapTitle: 'Goed geoefend vandaag!', fixCapBody: 'Deze letters worden sterker. Volgende keer warmen we ermee op en halen we de quiz!',
    popHint: 'Prik de bel!', familyDone: 'Familie geleerd!', traceHint: 'Luister en trek de letter na met je vinger',
    hearIt: 'Nog eens horen', traceClear: 'Wissen', traceCheck: 'Check', start: 'Start', langText: 'App-taal', langLearn: 'Leertaal', langTitle: 'Taal', langSheetBody: 'Kies het alfabet om te leren en de taal van de app-tekst.', streakBody: 'Speel elke dag een beetje en de vlam groeit. Sla je een dag over, dan begint hij opnieuw - houd hem brandend!', streakBest: 'Beste: {n} dagen', keepGoing: 'Ga zo door!', buildWord: 'Tik de letters op volgorde aan', rebuildWord: 'Bouw het woord bij het plaatje', wordsDoneTitle: 'Je kunt nieuwe woorden lezen!', wordsDoneBody: '{n} nieuwe woorden - Anbessa is trots!',
    teeTitle: 'Anbessa T-shirtwinkel', teeOrder: 'Bestel een echt shirt', teeSave: 'Ontwerp opslaan',
    masterTitle: 'Fidel-meester', masterChart: 'Tabel', masterAuto: 'Auto-stem', masterAbugida: 'Abugida', masterPlayAbugida: 'Speel de hele Abugida',
    sayWithMe: 'Zeg met mij mee',     closetTitle: 'Anbessa’s kledingkast', keepGoing: 'Ga zo door!',
    back: 'Terug', playAll: 'Alles afspelen', stop: 'Stop', pace_slow: 'Langzaam', pace_normal: 'Normaal', pace_fast: 'Snel',
    exploreHeader: 'Letterontdekker', exploreHeaderSub: 'Kies een klinker en tik op een familie om te horen',
    exploreFamilyTitle: 'De {name}-familie', exploreFamilySub: 'Zeven vormen, één letter — tik om elke te horen',
    closetShort: 'Kledingkast', teeShort: 'T-shirtwinkel', wordsShort: 'Eerste woorden', explorerShort: 'Ontdek', classicShort: 'Klassiek', practiceShort: 'Oefenen', familyShort: 'Familie', fvShort: 'Familiestem', nameShort: 'Mijn naam', grownupsShort: 'Volwassenen', giftShort: 'Cadeau', reviewShort: 'Beoordeling',
    nameTitle: 'Schrijf je naam', nameSub: 'Spel hem in Fidel, één klank per keer',
    nameHint: 'Kies hieronder een klinker, tik dan op letters om je naam te spellen.',
    namePlay: 'Hoor de naam', nameBackspace: 'Laatste letter verwijderen', nameClear: 'Wissen', nameVowel: 'Klinker', nameLetters: 'Letters', nameShare: 'Mijn naam delen',
    namePrivacy: 'De kaart wordt op dit apparaat gemaakt. Er wordt niets gedeeld tenzij je op Delen tikt.',
    fvTitle: 'Familiestem', fvSub: 'Laat Anbessa spreken met de stem van een dierbare', fvWhoSpeaks: 'Wie spreekt er?', fvDefault: 'Standaard', fvImport: 'Een stem importeren', fvForGrownups: 'Voor volwassenen', fvRecordBtn: 'Een nieuwe stem opnemen', fvNoMic: 'Opnemen heeft een microfoon nodig — gebruik een telefoon of tablet.',
    streakDays: '{n} dagen op rij', chapterDone: 'Hoofdstuk {n} voltooid!', earnedItem: 'Anbessa kreeg {item}!', shareMilestone: '{name} leerde {n} letters!',
    huntShort: 'Dagelijkse jacht', huntTitle: 'Dagelijkse letterjacht', huntSub: 'Jibby heeft de letters verstopt! Vind ze op het gehoor',
    huntFind: 'Vind de letter die zegt', huntListen: 'Hoor het geluid nog eens', huntDoneTitle: 'Je hebt ze allemaal gevonden!',
    huntTreasure: 'Open de schat', huntTomorrow: 'Kom morgen terug — Jibby verstopt nieuwe letters!',
    huntFoundOne: 'gevonden', huntHidden: 'verstopte letter',
    pcShort: 'Kaartje', pcTitle: 'Spraakkaartje', pcSub: 'Stuur je stem naar iemand van wie je houdt',
    pcHint: 'Zeg “Selam!”, zeg je nieuwste letters of zing — opa en oma horen je graag.',
    pcRecord: 'Opnemen', pcStop: 'Stop', pcListen: 'Luister', pcRedo: 'Opnieuw opnemen', pcSend: 'Naar familie sturen', pcSendAgain: 'Opnieuw sturen',
    pcGateIntro: 'Versturen is voor volwassenen — jij kiest wie het krijgt.', pcShared: 'Kaartje verstuurd!', pcSaved: 'Opgeslagen! Deel het waar je wilt.',
    pcPrivacy: 'De opname blijft op dit apparaat. Hij reist alleen als een volwassene hem verstuurt.',
    celebPostcard: 'Stuur dit naar de familie!',
    hol_enkutatash: 'Enkutatash — Gelukkig nieuwjaar!', hol_meskel: 'Meskel — het feest van het Kruis', hol_genna: 'Genna — Vrolijk kerstfeest!', hol_timkat: 'Timkat — Driekoningen!', hol_adwa: 'Adwa-overwinningsdag', hol_eritrea: 'Eritrese onafhankelijkheidsdag',
    planTitle: 'Plan van vandaag', planNewShort: 'Nieuwe stap', planEta: 'In dit tempo heb je het hele Fidel af op {date}!', planMake: 'Mijn leerplan maken', planSetupTitle: 'Mijn leerplan', planSetupSub: 'Kies een tempo - de coach begeleidt je elke dag', paceChill: 'Rustig - 1 letterfamilie per week', paceSteady: 'Gestaag - 2 families per week', paceZoom: 'Zoom - 4 families per week', planSave: 'Start mijn plan', warmTitle: 'Warming-up', warmNudgeTitle: 'Eerst opwarmen!', warmNudgeBody: 'Een korte herhaling van je letters, dan het spel!', warmNudgeMustBody: 'Een paar letters hebben eerst meer oefening nodig. Even opwarmen, dan verder!', warmStart: 'Start warming-up', warmSkip: 'Toch spelen', gpPlanTitle: 'Leerplan', gpRequireWarmup: 'Warming-up verplicht voor spellen', gpRequireHint: 'Als dit aanstaat moet het kind eerst de dagelijkse herhaling afmaken.', gpWarmups: '{n} warming-ups gedaan',
    jcTitle: 'Bij de klas van {who} aansluiten?', jcBody: 'De app onthoudt de klas alleen op dit apparaat. Er wordt niets over jou ergens naartoe gestuurd.', jcJoin: 'Bij de klas aansluiten', jcJoined: 'Je zit in de klas van {who}!', jcJoinedBody: 'Opdrachten van je leraar verschijnen in je dagplan.', jcShareText: 'Kom bij mijn eGeez-klas:',
    asTitle: 'Opdracht', asFrom: '{who} heeft jullie klas huiswerk gestuurd!', asDetail: '{n} vragen · uiterlijk {date}', asStart: 'Opdracht starten', asLater: 'Later', asDoneTitle: 'Opdracht klaar!', asScore: '{score} van {n} in één keer goed', asName: 'Je naam (de leraar ziet hem)', asSend: 'Resultaat naar de leraar sturen', asShareText: 'eGeez-huiswerk van jullie leraar:', asShareBack: 'eGeez-resultaat voor {who}:',
    tmTitle: 'Leraargereedschap', tmSub: 'Klaslinks, opdrachten, resultaten — zonder accounts', tmCreateTitle: 'Start je klas', tmIntro: 'Run een klas met alleen links — zonder accounts, zonder server. Leerlingen sluiten aan door één link te openen; resultaten komen als links terug.', tmYourName: 'Je naam (leerlingen zien hem)', tmClassCode: 'Klascode (4–12 letters of cijfers)', tmCodePh: 'bijv. STMARY1', tmCreate: 'Klas aanmaken', tmInvite: 'Leerlingen uitnodigen', tmInviteHint: 'Een leerling opent deze link één keer (of scant de code) — de app sluit aan bij jouw klas. Werkt via WhatsApp.', tmShareInvite: 'Uitnodigingslink delen', tmNewAssign: 'Extra opdracht', tmAssignHint: 'Elke leerling krijgt dezelfde vragen. Na afloop bouwt de app een resultaatlink die ze naar jou terugsturen.', tmPickFamilies: 'Letterfamilies', tmQuestions: 'Vragen', tmDue: 'Inleverdatum', tmBuildLink: 'Link maken', tmMakeLink: 'Opdrachtlink delen', tmRoster: 'Leerlingen', tmRosterEmpty: 'Nog geen resultaten. Als een leerling klaar is, stuurt die je een resultaatlink — open die op dit apparaat en hij wordt hier bewaard.', tmBest: 'beste', tmReceiptFiled: 'Resultaat opgeslagen: {who} — {score}', tmReceiptWrongClass: 'Dit resultaat hoort bij een klas die niet op dit apparaat staat.', tmRemove: 'Klas en resultaten verwijderen…', tmRemoveConfirm: 'Deze klas en al haar resultaten van dit apparaat wissen?', tmTv: 'Tv-weergave', tmTvHint: 'Sluit dit apparaat aan op een tv: grote letters en geluid voor de hele klas, met de aanmeldcode in de hoek.', tmTvOpen: 'Tv-weergave openen',
    tvExit: 'Tv-weergave sluiten', tvPrevFamily: 'Vorige familie', tvNextFamily: 'Volgende familie', tvPause: 'Gezang pauzeren', tvPlay: 'Gezang starten', tvJoin: 'Scan om bij de klas te komen',
    tmShort: 'Leraar', parentsShort: 'Ouders', tmLockTitle: 'Leraargedeelte', tmLockBody: 'Voer je klascode in om je klas te openen.', tmLockOpen: 'Openen', tmLockWrong: 'Dat is niet de klascode.', tmPlanTitle: 'Trimesterplan', tmPlanIntro: 'Kies hoeveel letterfamilies per week - het hele trimester legt zichzelf uit; elke week krijgt zijn tv-les, zijn huiswerklink en zijn inleverlijst.', tmPerWeek: '{n} families per week', tmPerWeekAny: 'Je eigen tempo (1-10)', tmPerWeekUnit: 'families per week', tmPerWeekSet: 'Instellen', tmWeek: 'Week {n}', tmThisWeek: 'deze week', tmDueShort: 'uiterlijk {date}', tmTeach: 'Tv-les', tmHomework: 'Huiswerk sturen', tmShareAgain: 'Link opnieuw delen', tmTurnedIn: '{n} van {total} ingeleverd', tmMissing: 'ontbreekt: {names}', tmNoneKnown: 'Wacht op de eerste resultaatlink', tmChangePace: 'Tempo wijzigen', tmTroubleTitle: 'Moeilijke letters van de klas', tmTroubleEmpty: 'Nog niets - gemiste letters komen mee in de resultaatlinks en verzamelen zich hier.', tmTroubleWho: '{n} missers · {names}', tmForms: 'Lettervormen', tmOrdersBase: 'Basisletters', tmOrdersAll: 'Alle 7 vormen', tmSent: 'Verstuurde opdrachten', tmExtra: 'Extra', tvChant: 'Gezang', tvQuiz: 'Quiz', tvSay: 'Wie is dit?', tvSayAfter: 'Zeg mij na', tvYourTurn: 'Jullie beurt - zeg het!', tvChoose: 'Kies letters', tvDone: 'Klaar', tvAll: 'Alle', tvNone: 'Geen', tvSayAfter: 'Zeg mij na', tvYourTurn: 'Jullie beurt - zeg het!', tvChoose: 'Kies letters', tvDone: 'Klaar', tvAll: 'Alle',     tmHowTitle: 'Zo werkt het', tmHow1: 'Maak je klas één keer aan - hij leeft op deze telefoon, zonder account.', tmHow2: 'Nodig leerlingen uit: ze openen één link of scannen de QR-code.', tmHow3: 'In de les: de letters op de tv - samen zingen of quizzen.', tmHow4: 'Stuur de huiswerklink van de week naar de WhatsApp-groep van de families.', tmHow5: 'Resultaten komen terug als links - open ze hier en de lijst vult zichzelf.',
    challengeFrom: '{who} daagt je uit!', challengeScored: '{who} haalde {score}% op {level}. Kun jij dat verslaan?',
    giftGot: 'Nieuw: {item}!', gpMastery: 'Letterbeheersing · {n} antwoorden vastgelegd', gpReplayLevel: 'Level {n} opnieuw spelen', gpTapNumber: 'Tik op het getal {word}',
    lettersUnlocked: '{n} / {total} letters ontgrendeld', // native review pending 
    
    teeLockedAt: 'Leer {n} letters', teeNext: 'Leer nog {n} families om het volgende shirt te openen!',
    aFriend: 'Een vriend',
    bestStreak: 'Beste reeks',
    catchHint: 'Voer Anbessa voordat Jibby het pakt!',
    ccApply: 'Toepassen',
    ccBlurb: 'Heb je een code van een kerk, school of buurtgroep? Vul hem in zodat zij punten krijgen.',
    ccChange: 'Wijzigen',
    ccPh: 'bijv. DEBRE',
    ccThanks: 'Bedankt — je steunt',
    ccTitle: 'Buurtcode',
    challengeBack: 'Daag terug uit',
    challengeFriend: 'Daag een vriend uit',
    challengeGone: 'Deze uitdaging is niet beschikbaar.',
    challengeLose: 'Net niet!',
    challengeShareText: 'Versla mijn eGeez-score! Lukt het jou?',
    challengeStart: 'Doe de uitdaging',
    challengeTie: 'Gelijkspel!',
    challengeTitle: 'Een uitdaging!',
    challengeWin: 'Je wint!',
    champion: 'Fidel Kampioen - elke ster verdiend!',
    closetEmpty: 'Maak lessen af om hoeden, sjaals en capes voor Anbessa te verdienen!',
    dailyGift: 'Open Anbessa\'s cadeau',
    dismiss: 'Niet nu',
    feedHint: 'Sleep de letter die Kokeb zegt naar Anbessa',
    firstTry: 'Eerste keer',
    fvDefaultVoice: 'Terug naar de standaardstem',
    fvDelete: 'Stem verwijderen',
    fvEmpty: 'Nog geen familiestemmen. Neem er een op, of importeer een stem die een familielid je stuurde.',
    fvGateIntro: 'Opnemen is voor volwassenen — het gebruikt de microfoon.',
    fvGreetingShort: 'Hoi!',
    fvGreetingSlot: 'Begroeting',
    fvImportFail: 'Dat bestand is geen eGeez-stem.',
    fvImported: 'Stem geïmporteerd!',
    fvNameLabel: 'Naam van de stem',
    fvNamePh: 'Wiens stem? bijv. Oma',
    fvNowSpeaking: 'Anbessa spreekt nu met deze stem',
    fvPrivacy: 'Stemmen blijven op dit apparaat. Er wordt niets geüpload — een stem reist alleen mee in het bestand dat je deelt.',
    fvRecordBlurb: 'Neem de letters in je eigen stem op en deel het bestand met je kind via WhatsApp. Een opa of oma ver weg kan opnemen voor kinderen hier — en andersom.',
    fvRecordHint: 'Tik op een letter om op te nemen, tik weer om te stoppen. Tik op ✓ om het terug te horen.',
    fvRecordTitle: 'Neem je stem op',
    fvShare: 'Deel met een kind',
    fvUseVoice: 'Gebruik het hier',
    giftAllDone: 'Je hebt alles verzameld - fijn dat je terug bent!',
    giftTitle: 'Een cadeau van Anbessa!',
    goHome: 'Home',
    gpAccuracy: 'Nauwkeurigheid',
    gpCorrect: 'goed',
    gpHold: 'Houd me vast',
    gpHoldHint: 'Twee seconden ingedrukt houden',
    gpIntro: 'Dit gedeelte is voor volwassenen: voortgang en oefentips.',
    gpLessonStars: 'Lessterren',
    gpMasteryLegend: 'Groen: sterk · Geel: bijna · Rood: hulp nodig · Grijs: nog niet geoefend. Quizzen oefenen nu de eersteordeletters.',
    gpOpenExplorer: 'Open in Verkenner',
    gpPlayerName: 'Naam speler',
    gpPlayerNameHint: 'Getoond bij uitdagingen die je naar vrienden stuurt. Optioneel — laat leeg om "Een vriend" te blijven. Het verlaat dit apparaat alleen in een uitdagingslink die je zelf deelt.',
    gpPlayerNamePh: 'bijv. Selam',
    gpReset: 'Alle voortgang wissen…',
    gpResetConfirm: 'Sterren, records, eilanden en leergeschiedenis wissen?',
    gpResetNo: 'Behouden',
    gpUnlockAll: 'Alles ontgrendelen (om te testen)…',
    gpUnlockConfirm: 'Alle levels, eilanden en letters openen om te testen?',
    gpUnlockYes: 'Ja, alles openen',
    paySupport: 'Steun eGeez', payTitle: 'Blijf leren met eGeez', payBody: 'Jullie gratis proef van {n} dagen is voorbij. De app kopen houdt hem werkend voor je kind - en laat hem groeien.', payLeft: 'Gratis proef: nog {n} dagen', payEnded: 'Jullie gratis proef is voorbij.', payBuy: 'Koop de app', payFamily: 'Vraag familie om hem cadeau te doen', payFamilyHint: 'Geen manier om te betalen waar je woont? Een familielid waar ook ter wereld kan hem cadeau doen - deel dit met hen.', payShareText: 'Onze kinderen leren het Ethiopische alfabet met eGeez. Kunnen jullie ons de app cadeau doen?', payFeedback: 'Niet kopen? Vertel ons eerlijk waarom', payFeedbackHint: 'Eerlijke feedback levert {n} extra gratis dagen op.', payFeedbackBody: 'Wat we leuk vonden:\n\nWat beter moet:\n\nWaarom we niet kochten:\n', payFeedbackDone: 'Dank je! {n} extra gratis dagen toegevoegd.', payOwned: 'Mijn familie heeft hem al gekocht', payThanks: 'Bedankt voor het steunen van eGeez!', gpMoveTitle: 'Verhuizen naar een andere telefoon', gpMoveHint: 'Bewaar alle voortgang als één klein bestand, stuur het naar de nieuwe telefoon (WhatsApp werkt) en laad het daar.', gpExport: 'Voortgangsbestand opslaan', gpImport: 'Voortgangsbestand laden', swUpdate: 'Nieuwe versie klaar - tik om bij te werken',
    gpResetYes: 'Ja, wissen',
    gpRunnerBest: 'Runner-record',
    gpTrouble: 'Lastige letters',
    gpTroubleFew: 'Nog niet genoeg gespeeld — kom terug na een paar spelletjes.',
    gpTroubleNone: 'Geen lastige letters nu. Goed gedaan!',
    grownupsSub: 'Voortgang, lastige letters en oefentips',
    installCta: 'Toevoegen',
    installHow: 'Hoe?',
    installIosHint: 'Tik op de Deel-knop en dan op \'Zet op beginscherm\'',
    installTitle: 'Zet Anbessa op je beginscherm',
    jumpToStep: 'Ga naar mijn volgende stap',
    learnSub: 'Leer elke letter, stap voor stap',
    learnTitle: 'Letterstappen',
    level: 'Level',
    linkCopied: 'Link gekopieerd!',
    masterInOrder: 'Op volgorde',
    masterLetters: 'letters',
    masterMixed: 'Gemengd',
    masterPause: 'Pauze',
    masterPlay: 'Speel',
    masterReshuffle: 'Opnieuw mengen',
    mixDone: 'Goed gemengd!',
    muncherWins: 'Opgegeten!', munched: 'Opgegeten!',
    myStep: 'Mijn stap',
    newReward: 'Nieuw!',
    nextVowel: 'Dan de volgende klinker',
    openCloset: 'Open Anbessa\'s kledingkast',
    practiceComplete: 'Oefening voltooid!',
    practicePraise: 'Die lastige letters worden sterker. Kokeb is trots op je!',
    remindBody: 'Kom vandaag een letter leren.',
    remindDesc: 'Elke middag een zacht duwtje om de reeks vol te houden.',
    remindTitle: 'Anbessa mist je!',
    remindTitleLabel: 'Dagelijkse herinnering',
    runAgain: 'Ren opnieuw',
    runBest: 'Beste',
    runBossAttack: 'Jibby de hyena valt aan!',
    runBossWin: 'Anbessa\'s letterkracht wint!',
    runMoveLeft: 'Ga naar links',
    runMoveRight: 'Ga naar rechts',
    runNewBest: 'Nieuw record!',
    runQuit: 'Stop de run',
    saysWord: 'zegt',
    scopeAll: 'Alle letters',
    scopeLabel: 'Welke letters',
    scopeLearned: 'Mijn letters',
    shareAnbessa: 'Deel Anbessa',
    shareSaved: 'Opgeslagen! Deel het overal.',
    shareShowOff: 'Laat het iedereen zien!',
    shareThanks: 'Bedankt voor het delen!',
    
    
    
    
    
    
    
        steerInto: 'Stuur Anbessa naar',
    teeGrownup: 'Bestellen opent een winkel — vraag een volwassene.',
    teeIntro: 'Verdien elk hoofdstuk een nieuw shirtontwerp — Anbessa draagt jouw alfabet! Bewaar de foto of vraag een volwassene om een echt shirt te bestellen.',
    teeOrdered: 'De winkel wordt geopend voor een volwassene...',
    teeSaveHint: 'Bewaar de foto en druk hem op elk shirt.',
    teeSaved: 'Ontwerp opgeslagen! Druk het overal.',
    teeUnlocked: 'Ontgrendeld!',
    whichLetter: 'Welke letter zegt',
    you: 'Jij',
}
