/* NO UI strings, split out of langpacks.js so a child only downloads the
   language they actually use. Loaded on demand by platform/i18n.js; any key
   omitted here falls back to the inline English at the t() call site. */
export default {
        backpack: 'Ryggsekk', home: 'Hjem', continue: 'Fortsett', gotIt: 'Skjønner',
    nice: 'Bra!', amazing: 'Fantastisk! {n} på rad!', notQuite: 'Ikke helt!', tryAgain: '— lytt og prøv igjen',
    yourTurn: 'Nå sier du det!', levelUp: 'Nivå fullført!', levelComplete: 'Nivå fullført!', playAgain: 'Spill igjen', listen: 'Lytt…',
            grownups: 'For voksne: fremgang og tips',     wordsTitle: 'Første ord', whichStart: 'Hvilken bokstav begynner det med?', readAndMatch: 'Les ordet, og trykk så på bildet', stoneFwd: 'Lytt! Trykk på bokstaven og hopp over!', stoneBack: 'Lytt! Hopp hjem igjen!', stoneTeach: 'Dette er bokstaven! Trykk på den nedenfor for å dra opp Anbessa', stoneTray: 'Bokstavkort', fixTitle: 'Nesten!', fixBody: '{n} bokstaver trenger litt mer øving. Mestre dem og prøv igjen!', fixCta: 'Øv på de vanskelige', fixReady: 'Bra øvd!', fixReadyBody: 'Du er klar. Vis bokstavene hvem som bestemmer!', fixRetry: 'Prøv quizen igjen', fixCapTitle: 'Bra øvd i dag!', fixCapBody: 'Bokstavene blir sterkere. Neste gang varmer vi opp med dem og klarer quizen!',
    popHint: 'Sprett boblen!', familyDone: 'Familien mestret!', traceHint: 'Lytt og tegn bokstaven med fingeren',
    hearIt: 'Hør igjen', traceClear: 'Tøm', traceCheck: 'Sjekk', start: 'Start', langText: 'App-språk', langLearn: 'Språk å lære', langTitle: 'Språk', langSheetBody: 'Velg alfabetet du vil lære og språket for appteksten.', streakBody: 'Spill litt hver dag, så vokser flammen. Hopper du over en dag, starter den på nytt - hold den i live!', streakBest: 'Beste: {n} dager', keepGoing: 'Fortsett!', buildWord: 'Trykk på bokstavene i rekkefølge', rebuildWord: 'Bygg ordet til bildet', wordsDoneTitle: 'Du kan lese nye ord!', wordsDoneBody: '{n} nye ord - Anbessa er stolt!',
    teeTitle: 'Anbessas T-skjortebutikk', teeOrder: 'Bestill en ekte skjorte', teeSave: 'Lagre designet',
    masterTitle: 'Fidel-mester', masterChart: 'Tabell', masterAuto: 'Auto-stemme', masterAbugida: 'Abugida', masterPlayAbugida: 'Spill hele Abugidaen',
    sayWithMe: 'Si med meg',     closetTitle: 'Anbessas garderobe', keepGoing: 'Fortsett sånn!',
    back: 'Tilbake', playAll: 'Spill alle', stop: 'Stopp', pace_slow: 'Sakte', pace_normal: 'Normal', pace_fast: 'Rask',
    exploreHeader: 'Bokstavutforskeren', exploreHeaderSub: 'Velg en vokal og trykk på en familie for å høre den',
    exploreFamilyTitle: '{name}-familien', exploreFamilySub: 'Sju former, én bokstav — trykk for å høre hver',
    closetShort: 'Garderobe', teeShort: 'T-skjortebutikk', wordsShort: 'Første ord', explorerShort: 'Utforsk', classicShort: 'Klassisk', practiceShort: 'Øv', familyShort: 'Familie', fvShort: 'Familiestemme', nameShort: 'Mitt navn', grownupsShort: 'Voksne', giftShort: 'Gave', reviewShort: 'Vurdering',
    nameTitle: 'Skriv navnet ditt', nameSub: 'Stav det i Fidel, én lyd om gangen',
    nameHint: 'Velg en vokallyd nedenfor, trykk så på bokstaver for å stave navnet ditt.',
    namePlay: 'Hør navnet', nameBackspace: 'Fjern siste bokstav', nameClear: 'Tøm', nameVowel: 'Vokallyd', nameLetters: 'Bokstaver', nameShare: 'Del navnet mitt',
    namePrivacy: 'Kortet lages på denne enheten. Ingenting deles med mindre du trykker på Del.',
    fvTitle: 'Familiestemme', fvSub: 'La Anbessa snakke med stemmen til en du er glad i', fvWhoSpeaks: 'Hvem snakker?', fvDefault: 'Standard', fvImport: 'Importer en stemme', fvForGrownups: 'For voksne', fvRecordBtn: 'Spill inn en ny stemme', fvNoMic: 'Innspilling krever en mikrofon — bruk en telefon eller nettbrett.',
    streakDays: '{n} dager på rad', chapterDone: 'Kapittel {n} fullført!', earnedItem: 'Anbessa fikk {item}!', shareMilestone: '{name} lærte {n} bokstaver!',
    huntShort: 'Dagens jakt', huntTitle: 'Dagens bokstavjakt', huntSub: 'Jibby har gjemt bokstavene! Finn dem på lyden',
    huntFind: 'Finn bokstaven som sier', huntListen: 'Hør lyden igjen', huntDoneTitle: 'Du fant alle!',
    huntTreasure: 'Åpne skatten', huntTomorrow: 'Kom tilbake i morgen — Jibby gjemmer nye bokstaver!',
    huntFoundOne: 'funnet', huntHidden: 'gjemt bokstav',
    pcShort: 'Postkort', pcTitle: 'Talepostkort', pcSub: 'Send stemmen din til noen du er glad i',
    pcHint: 'Si «Selam!», si dine nyeste bokstaver eller syng — besteforeldre elsker å høre deg.',
    pcRecord: 'Ta opp', pcStop: 'Stopp', pcListen: 'Lytt', pcRedo: 'Ta opp igjen', pcSend: 'Send til familien', pcSendAgain: 'Send igjen',
    pcGateIntro: 'Sending er for voksne — du velger hvem som får det.', pcShared: 'Postkort sendt!', pcSaved: 'Lagret! Del det hvor som helst.',
    pcPrivacy: 'Opptaket blir på denne enheten. Det reiser bare når en voksen sender det.',
    celebPostcard: 'Send dette til familien!',
    hol_enkutatash: 'Enkutatash — Godt nytt år!', hol_meskel: 'Meskel — korsets høytid', hol_genna: 'Genna — God jul!', hol_timkat: 'Timkat — helligtrekongersdag!', hol_adwa: 'Adwa-seiersdagen', hol_eritrea: 'Eritreas uavhengighetsdag',
    planTitle: 'Dagens plan', planNewShort: 'Nytt steg', planEta: 'I dette tempoet fullfører du hele Fidel innen {date}!', planMake: 'Lag planen min', planSetupTitle: 'Læringsplanen min', planSetupSub: 'Velg et tempo - treneren veileder deg hver dag', paceChill: 'Rolig - 1 bokstavfamilie i uka', paceSteady: 'Jevnt - 2 familier i uka', paceZoom: 'Zoom - 4 familier i uka', planSave: 'Start planen min', warmTitle: 'Oppvarming', warmNudgeTitle: 'Varm opp først!', warmNudgeBody: 'En rask repetisjon av bokstavene dine, så spillet!', warmNudgeMustBody: 'Noen bokstaver trenger mer øving først. En rask oppvarming, så videre!', warmStart: 'Start oppvarmingen', warmSkip: 'Spill likevel', gpPlanTitle: 'Læringsplan', gpRequireWarmup: 'Krev oppvarming før spill', gpRequireHint: 'Når dette er på, må barnet fullføre dagens repetisjon før spillene.', gpWarmups: '{n} oppvarminger fullført',
    jcTitle: 'Bli med i klassen til {who}?', jcBody: 'Appen husker klassen bare på denne enheten. Ingenting om deg sendes noe sted.', jcJoin: 'Bli med i klassen', jcJoined: 'Du er med i klassen til {who}!', jcJoinedBody: 'Oppgaver fra læreren din dukker opp i dagsplanen din.', jcShareText: 'Bli med i eGeez-klassen min:',
    asTitle: 'Oppgave', asFrom: '{who} har sendt lekser til klassen deres!', asDetail: '{n} spørsmål · frist {date}', asStart: 'Start oppgaven', asLater: 'Senere', asDoneTitle: 'Oppgaven er ferdig!', asScore: '{score} av {n} på første forsøk', asName: 'Navnet ditt (læreren ser det)', asSend: 'Send resultatet til læreren', asShareText: 'eGeez-lekse fra læreren deres:', asShareBack: 'eGeez-resultat til {who}:',
    tmTitle: 'Lærerverktøy', tmSub: 'Klasselenker, oppgaver, resultater — uten kontoer', tmCreateTitle: 'Start klassen din', tmIntro: 'Driv en klasse med bare lenker — uten kontoer, uten server. Elever blir med ved å åpne én lenke; resultatene kommer tilbake som lenker.', tmYourName: 'Navnet ditt (elevene ser det)', tmClassCode: 'Klassekode (4–12 bokstaver eller sifre)', tmCodePh: 'f.eks. STMARY1', tmCreate: 'Opprett klasse', tmInvite: 'Inviter elever', tmInviteHint: 'En elev åpner denne lenken én gang (eller skanner koden) — appen blir med i klassen din. Funker via WhatsApp.', tmShareInvite: 'Del invitasjonslenken', tmNewAssign: 'Ekstraoppgave', tmAssignHint: 'Alle elevene får de samme spørsmålene. Når de er ferdige, bygger appen en resultatlenke de sender tilbake til deg.', tmPickFamilies: 'Bokstavfamilier', tmQuestions: 'Spørsmål', tmDue: 'Frist', tmBuildLink: 'Bygg lenken', tmMakeLink: 'Del oppgavelenken', tmRoster: 'Elever', tmRosterEmpty: 'Ingen resultater ennå. Når en elev er ferdig, sender de deg en resultatlenke — åpne den på denne enheten, så havner den her.', tmBest: 'best', tmReceiptFiled: 'Resultat lagret: {who} — {score}', tmReceiptWrongClass: 'Dette resultatet tilhører en klasse som ikke finnes på denne enheten.', tmRemove: 'Fjern klassen og resultatene…', tmRemoveConfirm: 'Slette denne klassen og alle resultatene fra denne enheten?', tmTv: 'TV-visning', tmTvHint: 'Koble enheten til en TV: store bokstaver og lyd for hele klassen, med påmeldingskoden i hjørnet.', tmTvOpen: 'Åpne TV-visningen',
    tvExit: 'Lukk TV-visningen', tvPrevFamily: 'Forrige familie', tvNextFamily: 'Neste familie', tvPause: 'Pause sangen', tvPlay: 'Start sangen', tvJoin: 'Skann for å bli med i klassen',
    tmShort: 'Lærer', parentsShort: 'Foreldre', tmLockTitle: 'Lærerområde', tmLockBody: 'Skriv inn klassekoden din for å åpne klassen.', tmLockOpen: 'Åpne', tmLockWrong: 'Det er ikke klassekoden.', tmPlanTitle: 'Semesterplan', tmPlanIntro: 'Velg hvor mange bokstavfamilier per uke - hele semesteret legger seg selv; hver uke får sin TV-time, sin lekselenke og sin innleveringsliste.', tmPerWeek: '{n} familier per uke', tmPerWeekAny: 'Ditt eget tempo (1-10)', tmPerWeekUnit: 'familier per uke', tmPerWeekSet: 'Velg', tmWeek: 'Uke {n}', tmThisWeek: 'denne uken', tmDueShort: 'frist {date}', tmTeach: 'TV-time', tmHomework: 'Send lekse', tmShareAgain: 'Del lenken igjen', tmTurnedIn: '{n} av {total} levert', tmMissing: 'mangler: {names}', tmNoneKnown: 'Venter på den første resultatlenken', tmChangePace: 'Endre tempo', tmTroubleTitle: 'Klassens vanskelige bokstaver', tmTroubleEmpty: 'Ingenting ennå - bokstaver som bommes kommer i resultatlenkene og samles her.', tmTroubleWho: '{n} bom · {names}', tmForms: 'Bokstavformer', tmOrdersBase: 'Grunnbokstaver', tmOrdersAll: 'Alle 7 formene', tmSent: 'Sendte oppgaver', tmExtra: 'Ekstra', tvChant: 'Sang', tvQuiz: 'Quiz', tvSay: 'Hvem er dette?', tvSayAfter: 'Si etter meg', tvYourTurn: 'Deres tur - si den!', tvChoose: 'Velg bokstaver', tvDone: 'Ferdig', tvAll: 'Alle', tvNone: 'Ingen', tvSayAfter: 'Si etter meg', tvYourTurn: 'Deres tur - si den!', tvChoose: 'Velg bokstaver', tvDone: 'Ferdig', tvAll: 'Alle',     tmHowTitle: 'Slik funker det', tmHow1: 'Opprett klassen din én gang - den bor på denne telefonen, uten konto.', tmHow2: 'Inviter elever: de åpner én lenke eller skanner QR-koden.', tmHow3: 'I timen: bokstavene på TV-en - syng eller quiz sammen.', tmHow4: 'Send ukens lekselenke til familienes WhatsApp-gruppe.', tmHow5: 'Resultatene kommer tilbake som lenker - åpne dem her, så fyller listen seg selv.',
    challengeFrom: '{who} utfordrer deg!', challengeScored: '{who} fikk {score}% på {level}. Klarer du bedre?',
    giftGot: 'Nytt: {item}!', gpMastery: 'Bokstavmestring · {n} svar registrert', gpReplayLevel: 'Spill nivå {n} igjen', gpTapNumber: 'Trykk på tallet {word}',
    lettersUnlocked: '{n} / {total} bokstaver låst opp', // native review pending 
    
    teeLockedAt: 'Lær {n} bokstaver', teeNext: 'Lær {n} familier til for å låse opp neste t-skjorte!',
    aFriend: 'En venn',
    bestStreak: 'Beste rekke',
    catchHint: 'Gi Anbessa mat før Jibby napper den!',
    ccApply: 'Bruk',
    ccBlurb: 'Har du en kode fra en kirke, skole eller lokal gruppe? Skriv den inn så de får æren.',
    ccChange: 'Endre',
    ccPh: 'f.eks. DEBRE',
    ccThanks: 'Takk — du støtter',
    ccTitle: 'Fellesskapskode',
    challengeBack: 'Utfordre tilbake',
    challengeFriend: 'Utfordre en venn',
    challengeGone: 'Denne utfordringen er ikke tilgjengelig.',
    challengeLose: 'Så nære!',
    challengeShareText: 'Slå min eGeez-poengsum! Klarer du det?',
    challengeStart: 'Ta utfordringen',
    challengeTie: 'Det ble uavgjort!',
    challengeTitle: 'En utfordring!',
    challengeWin: 'Du vinner!',
    champion: 'Fidel-mester - hver stjerne tjent!',
    closetEmpty: 'Fullfør leksjoner for å tjene hatter, skjerf og kapper til Anbessa!',
    dailyGift: 'Åpne Anbessas gave',
    dismiss: 'Ikke nå',
    feedHint: 'Dra bokstaven Kokeb sier til Anbessa',
    firstTry: 'Første forsøk',
    fvDefaultVoice: 'Tilbake til standardstemmen',
    fvDelete: 'Slett stemme',
    fvEmpty: 'Ingen familiestemmer ennå. Ta opp en, eller importer en stemme en slektning sendte deg.',
    fvGateIntro: 'Opptak er for voksne — det bruker mikrofonen.',
    fvGreetingShort: 'Hei!',
    fvGreetingSlot: 'Hilsen',
    fvImportFail: 'Den filen er ikke en eGeez-stemme.',
    fvImported: 'Stemme importert!',
    fvNameLabel: 'Stemmenavn',
    fvNamePh: 'Hvem sin stemme? f.eks. Bestemor',
    fvNowSpeaking: 'Anbessa snakker nå med denne stemmen',
    fvPrivacy: 'Stemmer blir på denne enheten. Ingenting lastes opp — en stemme reiser bare i filen du velger å dele.',
    fvRecordBlurb: 'Ta opp bokstavene med din egen stemme, og del filen med barnet ditt på WhatsApp. En besteforelder langt unna kan ta opp for barn her — og motsatt.',
    fvRecordHint: 'Trykk på en bokstav for å ta den opp, trykk igjen for å stoppe. Trykk ✓ for å høre den.',
    fvRecordTitle: 'Ta opp stemmen din',
    fvShare: 'Del med et barn',
    fvUseVoice: 'Bruk den her',
    giftAllDone: 'Du har samlet alt - så glad for at du kom tilbake!',
    giftTitle: 'En gave fra Anbessa!',
    goHome: 'Hjem',
    gpAccuracy: 'Treffsikkerhet',
    gpCorrect: 'riktig',
    gpHold: 'Hold meg',
    gpHoldHint: 'Trykk og hold i to sekunder',
    gpIntro: 'Dette området er for voksne: fremgangsdetaljer og øvingstips.',
    gpLessonStars: 'Leksjonsstjerner',
    gpMasteryLegend: 'Grønn: sitter · Gul: på vei · Rød: trenger hjelp · Grå: ikke øvd ennå. Quizene øver nå på førsteordens bokstaver.',
    gpOpenExplorer: 'Åpne i Utforsker',
    gpPlayerName: 'Spillernavn',
    gpPlayerNameHint: 'Vises på utfordringer du sender til venner. Valgfritt — la det stå tomt for å være "En venn". Det forlater aldri denne enheten unntatt i en utfordringslenke du velger å dele.',
    gpPlayerNamePh: 'f.eks. Selam',
    gpReset: 'Nullstill all fremgang…',
    gpResetConfirm: 'Slette stjerner, rekorder, øyer og læringshistorikk?',
    gpResetNo: 'Behold det',
    gpUnlockAll: 'Lås opp alt (for testing)…',
    gpUnlockConfirm: 'Åpne alle nivåer, øyer og bokstaver for testing?',
    gpUnlockYes: 'Ja, åpne alt',
    paySupport: 'Støtt eGeez', payTitle: 'Fortsett å lære med eGeez', payBody: 'Gratisprøven deres på {n} dager er over. Å kjøpe appen holder den i gang for barnet ditt - og lar den vokse.', payLeft: 'Gratisprøve: {n} dager igjen', payEnded: 'Gratisprøven deres er over.', payBuy: 'Kjøp appen', payFamily: 'Be familien gi den i gave', payFamilyHint: 'Ingen måte å betale der dere bor? En slektning hvor som helst i verden kan gi den i gave - del dette med dem.', payShareText: 'Barna våre lærer det etiopiske alfabetet med eGeez. Kan dere gi oss appen i gave?', payFeedback: 'Kjøper dere ikke? Fortell oss ærlig hvorfor', payFeedbackHint: 'Ærlig tilbakemelding gir {n} gratisdager til.', payFeedbackBody: 'Hva vi likte:\n\nHva som bør bli bedre:\n\nHvorfor vi ikke kjøpte:\n', payFeedbackDone: 'Takk! {n} gratisdager til er lagt til.', payOwned: 'Familien min har allerede kjøpt den', payThanks: 'Takk for at dere støtter eGeez!', gpMoveTitle: 'Flytt til en annen telefon', gpMoveHint: 'Lagre all fremgang som en liten fil, send den til den nye telefonen (WhatsApp funker) og last den inn der.', gpExport: 'Lagre fremgangsfil', gpImport: 'Last inn fremgangsfil', swUpdate: 'Ny versjon klar - trykk for å oppdatere',
    gpResetYes: 'Ja, slett',
    gpRunnerBest: 'Løper-rekord',
    gpTrouble: 'Vanskelige bokstaver',
    gpTroubleFew: 'Ikke nok spilling ennå — kom tilbake etter noen spill.',
    gpTroubleNone: 'Ingen vanskelige bokstaver akkurat nå. Bra jobbet!',
    grownupsSub: 'Fremgang, vanskelige bokstaver og øvingstips',
    installCta: 'Legg til',
    installHow: 'Hvordan?',
    installIosHint: 'Trykk på Del-knappen, deretter \'Legg til på Hjem-skjerm\'',
    installTitle: 'Legg Anbessa til på hjem-skjermen',
    jumpToStep: 'Gå til mitt neste steg',
    learnSub: 'Lær hver bokstav, ett steg om gangen',
    learnTitle: 'Bokstavsteg',
    level: 'Nivå',
    linkCopied: 'Lenke kopiert!',
    masterInOrder: 'I rekkefølge',
    masterLetters: 'bokstaver',
    masterMixed: 'Blandet',
    masterPause: 'Pause',
    masterPlay: 'Spill',
    masterReshuffle: 'Bland på nytt',
    mixDone: 'Flott blanding!',
    muncherWins: 'Mumset!', munched: 'Mumset!',
    myStep: 'Mitt steg',
    newReward: 'Ny!',
    nextVowel: 'Så neste vokal',
    openCloset: 'Åpne Anbessas garderobe',
    practiceComplete: 'Øving fullført!',
    practicePraise: 'De vanskelige bokstavene blir sterkere. Kokeb er stolt av deg!',
    remindBody: 'Kom og lær en bokstav i dag.',
    remindDesc: 'Et vennlig dytt hver ettermiddag for å holde rekka i gang.',
    remindTitle: 'Anbessa savner deg!',
    remindTitleLabel: 'Daglig påminnelse',
    runAgain: 'Løp igjen',
    runBest: 'Best',
    runBossAttack: 'Jibby hyenen angriper!',
    runBossWin: 'Anbessas bokstavkraft vinner!',
    runMoveLeft: 'Beveg til venstre',
    runMoveRight: 'Beveg til høyre',
    runNewBest: 'Ny rekord!',
    runQuit: 'Avslutt løp',
    saysWord: 'sier',
    scopeAll: 'Alle bokstaver',
    scopeLabel: 'Hvilke bokstaver',
    scopeLearned: 'Mine bokstaver',
    shareAnbessa: 'Del Anbessa',
    shareSaved: 'Lagret! Del den hvor som helst.',
    shareShowOff: 'Vis det til alle!',
    shareThanks: 'Takk for at du delte!',
    
    
    
    
    
    
    
        steerInto: 'Styr Anbessa inn i',
    teeGrownup: 'Bestilling åpner en butikk — spør en voksen.',
    teeIntro: 'Tjen et nytt skjortedesign hvert kapittel — Anbessa har på seg alfabetet ditt! Lagre bildet eller be en voksen bestille en ekte skjorte.',
    teeOrdered: 'Åpner butikken for en voksen...',
    teeSaveHint: 'Lagre bildet og trykk det på hvilken som helst skjorte.',
    teeSaved: 'Design lagret! Trykk det hvor som helst.',
    teeUnlocked: 'Låst opp!',
    whichLetter: 'Hvilken bokstav sier',
    you: 'Du',
}
