/* SV UI strings, split out of langpacks.js so a child only downloads the
   language they actually use. Loaded on demand by platform/i18n.js; any key
   omitted here falls back to the inline English at the t() call site. */
export default {
        backpack: 'Ryggsäck', home: 'Hem', continue: 'Fortsätt', gotIt: 'Klart',
    nice: 'Bra!', amazing: 'Fantastiskt! {n} i rad!', notQuite: 'Inte riktigt!', tryAgain: '— lyssna och försök igen',
    yourTurn: 'Nu säger du det!', levelUp: 'Nivå klar!', levelComplete: 'Nivå klar!', playAgain: 'Spela igen', listen: 'Lyssna…',
            grownups: 'För vuxna: framsteg och tips',     wordsTitle: 'Första orden', whichStart: 'Vilken bokstav börjar det med?', readAndMatch: 'Läs ordet och tryck sedan på bilden', stoneFwd: 'Lyssna! Tryck på bokstaven och hoppa över!', stoneBack: 'Lyssna! Hoppa hem igen!', stoneTeach: 'Här är bokstaven! Tryck på den nedan för att dra upp Anbessa', stoneTray: 'Bokstavskort', fixTitle: 'Nästan!', fixBody: '{n} bokstäver behöver lite mer övning. Bemästra dem och försök igen!', fixCta: 'Öva de kluriga', fixReady: 'Bra övat!', fixReadyBody: 'Du är redo. Visa bokstäverna vem som bestämmer!', fixRetry: 'Prova quizet igen', fixCapTitle: 'Bra övat i dag!', fixCapBody: 'Bokstäverna blir starkare. Nästa gång värmer vi upp med dem och klarar quizet!',
    popHint: 'Poppa bubblan!', familyDone: 'Familjen klar!', traceHint: 'Lyssna och spåra bokstaven med fingret',
    hearIt: 'Hör igen', traceClear: 'Rensa', traceCheck: 'Kolla', start: 'Start', langText: 'Appspråk', langLearn: 'Språk att lära', langTitle: 'Språk', langSheetBody: 'Välj alfabetet att lära dig och språket för appens text.', streakBody: 'Spela lite varje dag så växer lågan. Missar du en dag börjar den om - håll den vid liv!', streakBest: 'Bästa: {n} dagar', keepGoing: 'Fortsätt!', buildWord: 'Tryck på bokstäverna i ordning', rebuildWord: 'Bygg ordet till bilden', wordsDoneTitle: 'Du kan läsa nya ord!', wordsDoneBody: '{n} nya ord - Anbessa är stolt!',
    teeTitle: 'Anbessas T-shirtbutik', teeOrder: 'Beställ en riktig t-shirt', teeSave: 'Spara designen',
    masterTitle: 'Fidel-mästare', masterChart: 'Tabell', masterAuto: 'Auto-röst', masterAbugida: 'Abugida', masterPlayAbugida: 'Spela hela Abugidan',
    sayWithMe: 'Säg med mig',     closetTitle: 'Anbessas garderob', keepGoing: 'Fortsätt så!',
    back: 'Tillbaka', playAll: 'Spela alla', stop: 'Stopp', pace_slow: 'Långsam', pace_normal: 'Normal', pace_fast: 'Snabb',
    exploreHeader: 'Bokstavsutforskaren', exploreHeaderSub: 'Välj en vokal och tryck på en familj för att höra den',
    exploreFamilyTitle: 'Familjen {name}', exploreFamilySub: 'Sju former, en bokstav — tryck för att höra var och en',
    closetShort: 'Garderob', teeShort: 'T-shirtbutik', wordsShort: 'Första orden', explorerShort: 'Utforska', classicShort: 'Klassisk', practiceShort: 'Öva', familyShort: 'Familj', fvShort: 'Familjeröst', nameShort: 'Mitt namn', grownupsShort: 'Vuxna', giftShort: 'Present', reviewShort: 'Recension',
    nameTitle: 'Skriv ditt namn', nameSub: 'Stava det i Fidel, ett ljud i taget',
    nameHint: 'Välj ett vokalljud nedan, tryck sedan på bokstäver för att stava ditt namn.',
    namePlay: 'Hör namnet', nameBackspace: 'Ta bort sista bokstaven', nameClear: 'Rensa', nameVowel: 'Vokalljud', nameLetters: 'Bokstäver', nameShare: 'Dela mitt namn',
    namePrivacy: 'Kortet skapas på den här enheten. Inget delas om du inte trycker på Dela.',
    fvTitle: 'Familjeröst', fvSub: 'Låt Anbessa tala med en kär persons röst', fvWhoSpeaks: 'Vem talar?', fvDefault: 'Standard', fvImport: 'Importera en röst', fvForGrownups: 'För vuxna', fvRecordBtn: 'Spela in en ny röst', fvNoMic: 'Inspelning kräver en mikrofon — använd en telefon eller surfplatta.',
    streakDays: '{n} dagar i rad', chapterDone: 'Kapitel {n} klart!', earnedItem: 'Anbessa fick {item}!', shareMilestone: '{name} lärde sig {n} bokstäver!',
    huntShort: 'Dagens jakt', huntTitle: 'Dagens bokstavsjakt', huntSub: 'Jibby har gömt bokstäverna! Hitta dem på ljudet',
    huntFind: 'Hitta bokstaven som säger', huntListen: 'Hör ljudet igen', huntDoneTitle: 'Du hittade alla!',
    huntTreasure: 'Öppna skatten', huntTomorrow: 'Kom tillbaka i morgon — Jibby gömmer nya bokstäver!',
    huntFoundOne: 'hittad', huntHidden: 'gömd bokstav',
    pcShort: 'Vykort', pcTitle: 'Röstvykort', pcSub: 'Skicka din röst till någon du älskar',
    pcHint: 'Säg ”Selam!”, säg dina nyaste bokstäver eller sjung — mormor och farfar älskar att höra dig.',
    pcRecord: 'Spela in', pcStop: 'Stopp', pcListen: 'Lyssna', pcRedo: 'Spela in igen', pcSend: 'Skicka till familjen', pcSendAgain: 'Skicka igen',
    pcGateIntro: 'Att skicka är för vuxna — du väljer vem som får det.', pcShared: 'Vykortet skickat!', pcSaved: 'Sparat! Dela det var som helst.',
    pcPrivacy: 'Inspelningen stannar på den här enheten. Den skickas bara när en vuxen skickar den.',
    celebPostcard: 'Skicka det till familjen!',
    hol_enkutatash: 'Enkutatash — Gott nytt år!', hol_meskel: 'Meskel — korsets högtid', hol_genna: 'Genna — God jul!', hol_timkat: 'Timkat — trettondagen!', hol_adwa: 'Adwa-segerdagen', hol_eritrea: 'Eritreas självständighetsdag',
    planTitle: 'Dagens plan', planNewShort: 'Nytt steg', planEta: 'I den här takten klarar du hela Fidel till {date}!', planMake: 'Skapa min plan', planSetupTitle: 'Min inlärningsplan', planSetupSub: 'Välj en takt - coachen guidar dig varje dag', paceChill: 'Lugn - 1 bokstavsfamilj i veckan', paceSteady: 'Stadig - 2 familjer i veckan', paceZoom: 'Zoom - 4 familjer i veckan', planSave: 'Starta min plan', warmTitle: 'Uppvärmning', warmNudgeTitle: 'Värm upp först!', warmNudgeBody: 'En snabb repetition av dina bokstäver, sedan spelet!', warmNudgeMustBody: 'Några bokstäver behöver mer övning först. En snabb uppvärmning, sedan vidare!', warmStart: 'Starta uppvärmningen', warmSkip: 'Spela ändå', gpPlanTitle: 'Inlärningsplan', gpRequireWarmup: 'Kräv uppvärmning före spel', gpRequireHint: 'När det är på måste barnet klara dagens repetition innan spelen.', gpWarmups: '{n} uppvärmningar klara',
    jcTitle: 'Gå med i {who}s klass?', jcBody: 'Appen kommer ihåg klassen bara på den här enheten. Inget om dig skickas någonstans.', jcJoin: 'Gå med i klassen', jcJoined: 'Du är med i {who}s klass!', jcJoinedBody: 'Uppgifter från din lärare dyker upp i din dagliga plan.', jcShareText: 'Gå med i min eGeez-klass:',
    asTitle: 'Uppgift', asFrom: '{who} har skickat läxor till er klass!', asDetail: '{n} frågor · senast {date}', asStart: 'Starta uppgiften', asLater: 'Senare', asDoneTitle: 'Uppgiften klar!', asScore: '{score} av {n} på första försöket', asName: 'Ditt namn (läraren ser det)', asSend: 'Skicka resultatet till läraren', asShareText: 'eGeez-läxa från er lärare:', asShareBack: 'eGeez-resultat till {who}:',
    tmTitle: 'Lärarverktyg', tmSub: 'Klasslänkar, uppgifter, resultat — utan konton', tmCreateTitle: 'Starta din klass', tmIntro: 'Driv en klass med bara länkar — utan konton, utan server. Elever går med genom att öppna en länk; resultaten kommer tillbaka som länkar.', tmYourName: 'Ditt namn (eleverna ser det)', tmClassCode: 'Klasskod (4–12 bokstäver eller siffror)', tmCodePh: 't.ex. STMARY1', tmCreate: 'Skapa klass', tmInvite: 'Bjud in elever', tmInviteHint: 'En elev öppnar länken en gång (eller skannar koden) — appen går med i din klass. Funkar via WhatsApp.', tmShareInvite: 'Dela inbjudningslänken', tmNewAssign: 'Extrauppgift', tmAssignHint: 'Alla elever får samma frågor. När de är klara bygger appen en resultatlänk som de skickar tillbaka till dig.', tmPickFamilies: 'Bokstavsfamiljer', tmQuestions: 'Frågor', tmDue: 'Sista dag', tmBuildLink: 'Bygg länken', tmMakeLink: 'Dela uppgiftslänken', tmRoster: 'Elever', tmRosterEmpty: 'Inga resultat än. När en elev är klar skickar de en resultatlänk — öppna den på den här enheten så hamnar den här.', tmBest: 'bäst', tmReceiptFiled: 'Resultat sparat: {who} — {score}', tmReceiptWrongClass: 'Det här resultatet tillhör en klass som inte finns på den här enheten.', tmRemove: 'Ta bort klassen och resultaten…', tmRemoveConfirm: 'Radera den här klassen och alla dess resultat från den här enheten?', tmTv: 'TV-läge', tmTvHint: 'Anslut enheten till en TV: stora bokstäver och ljud för hela klassen, med anslutningskoden i hörnet.', tmTvOpen: 'Öppna TV-läget',
    tvExit: 'Lämna TV-läget', tvPrevFamily: 'Föregående familj', tvNextFamily: 'Nästa familj', tvPause: 'Pausa ramsan', tvPlay: 'Starta ramsan', tvJoin: 'Skanna för att gå med i klassen',
    tmShort: 'Lärare', parentsShort: 'Föräldrar', tmLockTitle: 'Lärarområde', tmLockBody: 'Ange din klasskod för att öppna din klass.', tmLockOpen: 'Öppna', tmLockWrong: 'Det är inte klasskoden.', tmPlanTitle: 'Terminsplan', tmPlanIntro: 'Välj hur många bokstavsfamiljer per vecka - hela terminen lägger sig själv; varje vecka får sin TV-lektion, sin läxlänk och sin inlämningslista.', tmPerWeek: '{n} familjer per vecka', tmPerWeekAny: 'Din egen takt (1-10)', tmPerWeekUnit: 'familjer per vecka', tmPerWeekSet: 'Välj', tmWeek: 'Vecka {n}', tmThisWeek: 'denna vecka', tmDueShort: 'senast {date}', tmTeach: 'TV-lektion', tmHomework: 'Skicka läxa', tmShareAgain: 'Dela länken igen', tmTurnedIn: '{n} av {total} inlämnade', tmMissing: 'saknas: {names}', tmNoneKnown: 'Väntar på den första resultatlänken', tmChangePace: 'Ändra takt', tmTroubleTitle: 'Klassens svåra bokstäver', tmTroubleEmpty: 'Inget än - missade bokstäver kommer i resultatlänkarna och samlas här.', tmTroubleWho: '{n} missar · {names}', tmForms: 'Bokstavsformer', tmOrdersBase: 'Grundbokstäver', tmOrdersAll: 'Alla 7 formerna', tmSent: 'Skickade uppgifter', tmExtra: 'Extra', tvChant: 'Ramsa', tvQuiz: 'Quiz', tvSay: 'Vem är detta?', tvSayAfter: 'Säg efter mig', tvYourTurn: 'Er tur - säg den!', tvChoose: 'Välj bokstäver', tvDone: 'Klar', tvAll: 'Alla', tvNone: 'Inga', tvSayAfter: 'Säg efter mig', tvYourTurn: 'Er tur - säg den!', tvChoose: 'Välj bokstäver', tvDone: 'Klar', tvAll: 'Alla',     tmHowTitle: 'Så funkar det', tmHow1: 'Skapa din klass en gång - den bor på den här telefonen, utan konto.', tmHow2: 'Bjud in elever: de öppnar en länk eller skannar QR-koden.', tmHow3: 'På lektionen: bokstäverna på TV:n - ramsa eller quizza tillsammans.', tmHow4: 'Skicka veckans läxlänk till familjernas WhatsApp-grupp.', tmHow5: 'Resultaten kommer tillbaka som länkar - öppna dem här så fylls listan av sig själv.',
    challengeFrom: '{who} utmanar dig!', challengeScored: '{who} fick {score}% på {level}. Kan du slå det?',
    giftGot: 'Nytt: {item}!', gpMastery: 'Bokstavskoll · {n} svar registrerade', gpReplayLevel: 'Spela nivå {n} igen', gpTapNumber: 'Tryck på talet {word}',
    lettersUnlocked: '{n} / {total} bokstäver upplåsta', // native review pending 
    
    teeLockedAt: 'Lär dig {n} bokstäver', teeNext: 'Lär dig {n} familjer till för att låsa upp nästa tröja!',
    aFriend: 'En kompis',
    bestStreak: 'Bästa svit',
    catchHint: 'Mata Anbessa innan Jibby tar den!',
    ccApply: 'Använd',
    ccBlurb: 'Har du en kod från en kyrka, skola eller förening? Skriv in den så får de äran.',
    ccChange: 'Ändra',
    ccPh: 't.ex. DEBRE',
    ccThanks: 'Tack — du stöttar',
    ccTitle: 'Föreningskod',
    challengeBack: 'Utmana tillbaka',
    challengeFriend: 'Utmana en kompis',
    challengeGone: 'Den här utmaningen finns inte längre.',
    challengeLose: 'Så nära!',
    challengeShareText: 'Slå mitt resultat i eGeez! Klarar du det?',
    challengeStart: 'Anta utmaningen',
    challengeTie: 'Det blev oavgjort!',
    challengeTitle: 'En utmaning!',
    challengeWin: 'Du vinner!',
    champion: 'Fidel-mästare - varje stjärna tagen!',
    closetEmpty: 'Klara lektioner för att vinna hattar, halsdukar och mantlar till Anbessa!',
    dailyGift: 'Öppna Anbessas present',
    dismiss: 'Inte nu',
    feedHint: 'Dra bokstaven som Kokeb säger till Anbessa',
    firstTry: 'Första försöket',
    fvDefaultVoice: 'Tillbaka till standardrösten',
    fvDelete: 'Radera röst',
    fvEmpty: 'Inga familjeröster än. Spela in en, eller importera en röst som en släkting skickat.',
    fvGateIntro: 'Inspelning är för vuxna — den använder mikrofonen.',
    fvGreetingShort: 'Hej!',
    fvGreetingSlot: 'Hälsning',
    fvImportFail: 'Den filen är ingen eGeez-röst.',
    fvImported: 'Rösten importerad!',
    fvNameLabel: 'Röstens namn',
    fvNamePh: 'Vems röst? t.ex. Mormor',
    fvNowSpeaking: 'Anbessa pratar nu med den här rösten',
    fvPrivacy: 'Röster stannar på den här enheten. Inget laddas upp — en röst reser bara i filen du väljer att dela.',
    fvRecordBlurb: 'Spela in bokstäverna med din egen röst och dela filen med ditt barn via WhatsApp. En mor- eller farförälder långt borta kan spela in åt barnen här — och tvärtom.',
    fvRecordHint: 'Tryck på en bokstav för att spela in, tryck igen för att stoppa. Tryck ✓ för att lyssna.',
    fvRecordTitle: 'Spela in din röst',
    fvShare: 'Dela med ett barn',
    fvUseVoice: 'Använd den här',
    giftAllDone: 'Du har samlat allt - så glad att du kom tillbaka!',
    giftTitle: 'En present från Anbessa!',
    goHome: 'Hem',
    gpAccuracy: 'Träffsäkerhet',
    gpCorrect: 'rätt',
    gpHold: 'Håll mig',
    gpHoldHint: 'Tryck och håll i två sekunder',
    gpIntro: 'Det här området är för vuxna: framsteg i detalj och övningstips.',
    gpLessonStars: 'Lektionsstjärnor',
    gpMasteryLegend: 'Grön: säker · Gul: på gång · Röd: behöver hjälp · Grå: inte övad än. Frågesporterna övar just nu första ordningens bokstäver.',
    gpOpenExplorer: 'Öppna i Utforskaren',
    gpPlayerName: 'Spelarnamn',
    gpPlayerNameHint: 'Visas på utmaningar du skickar till kompisar. Frivilligt — lämna tomt för att förbli "En kompis". Det lämnar aldrig den här enheten utom i en utmaningslänk du väljer att dela.',
    gpPlayerNamePh: 't.ex. Selam',
    gpReset: 'Nollställ alla framsteg…',
    gpResetConfirm: 'Radera stjärnor, rekord, öar och inlärningshistorik?',
    gpResetNo: 'Behåll',
    gpUnlockAll: 'Lås upp allt (för test)…',
    gpUnlockConfirm: 'Öppna alla nivåer, öar och bokstäver för test?',
    gpUnlockYes: 'Ja, öppna allt',
    paySupport: 'Stöd eGeez', payTitle: 'Fortsätt lära med eGeez', payBody: 'Er gratisprov på {n} dagar är slut. Att köpa appen håller den igång för ert barn - och låter den växa.', payLeft: 'Gratisprov: {n} dagar kvar', payEnded: 'Ert gratisprov är slut.', payBuy: 'Köp appen', payFamily: 'Be familjen ge den i gåva', payFamilyHint: 'Inget sätt att betala där ni bor? En släkting var som helst i världen kan ge den i gåva - dela detta med dem.', payShareText: 'Våra barn lär sig det etiopiska alfabetet med eGeez. Kan ni ge oss appen i gåva?', payFeedback: 'Köper ni inte? Berätta ärligt varför', payFeedbackHint: 'Ärlig feedback ger {n} gratisdagar till.', payFeedbackBody: 'Vad vi gillade:\n\nVad som borde bli bättre:\n\nVarför vi inte köpte:\n', payFeedbackDone: 'Tack! {n} gratisdagar till har lagts till.', payOwned: 'Min familj har redan köpt den', payThanks: 'Tack för att ni stöder eGeez!', gpMoveTitle: 'Flytta till en annan telefon', gpMoveHint: 'Spara alla framsteg som en liten fil, skicka den till den nya telefonen (WhatsApp funkar) och ladda den där.', gpExport: 'Spara framstegsfil', gpImport: 'Ladda framstegsfil', swUpdate: 'Ny version klar - tryck för att uppdatera',
    gpResetYes: 'Ja, radera',
    gpRunnerBest: 'Löprekord',
    gpTrouble: 'Kluriga bokstäver',
    gpTroubleFew: 'Inte tillräckligt spelat än — kom tillbaka efter några spel.',
    gpTroubleNone: 'Inga kluriga bokstäver just nu. Bra jobbat!',
    grownupsSub: 'Framsteg, kluriga bokstäver och övningstips',
    installCta: 'Lägg till',
    installHow: 'Hur?',
    installIosHint: 'Tryck på Dela-knappen och sedan \'Lägg till på hemskärmen\'',
    installTitle: 'Lägg till Anbessa på hemskärmen',
    jumpToStep: 'Gå till mitt nästa steg',
    learnSub: 'Lär dig varje bokstav, ett steg i taget',
    learnTitle: 'Bokstavssteg',
    level: 'Nivå',
    linkCopied: 'Länk kopierad!',
    masterInOrder: 'I ordning',
    masterLetters: 'bokstäver',
    masterMixed: 'Blandat',
    masterPause: 'Pausa',
    masterPlay: 'Spela',
    masterReshuffle: 'Blanda om',
    mixDone: 'Bra blandat!',
    muncherWins: 'Mumsat!', munched: 'Mumsat!',
    myStep: 'Mitt steg',
    newReward: 'Ny!',
    nextVowel: 'Sedan nästa vokal',
    openCloset: 'Öppna Anbessas garderob',
    practiceComplete: 'Övningen klar!',
    practicePraise: 'De kluriga bokstäverna blir starkare. Kokeb är stolt över dig!',
    remindBody: 'Kom och lär dig en bokstav idag.',
    remindDesc: 'En vänlig knuff varje eftermiddag för att hålla sviten vid liv.',
    remindTitle: 'Anbessa saknar dig!',
    remindTitleLabel: 'Daglig påminnelse',
    runAgain: 'Spring igen',
    runBest: 'Bäst',
    runBossAttack: 'Jibby hyenan attackerar!',
    runBossWin: 'Anbessas bokstavskraft vinner!',
    runMoveLeft: 'Åt vänster',
    runMoveRight: 'Åt höger',
    runNewBest: 'Nytt rekord!',
    runQuit: 'Avsluta löpning',
    saysWord: 'säger',
    scopeAll: 'Alla bokstäver',
    scopeLabel: 'Vilka bokstäver',
    scopeLearned: 'Mina bokstäver',
    shareAnbessa: 'Dela Anbessa',
    shareSaved: 'Sparat! Dela var du vill.',
    shareShowOff: 'Visa alla!',
    shareThanks: 'Tack för att du delar!',
    
    
    
    
    
    
    
        steerInto: 'Styr Anbessa in i',
    teeGrownup: 'Beställning öppnar en butik — fråga en vuxen.',
    teeIntro: 'Vinn en ny tröjdesign varje kapitel — Anbessa bär ditt alfabet! Spara bilden eller be en vuxen beställa en riktig tröja.',
    teeOrdered: 'Öppnar butiken för en vuxen...',
    teeSaveHint: 'Spara bilden och tryck den på vilken tröja som helst.',
    teeSaved: 'Design sparad! Tryck den var du vill.',
    teeUnlocked: 'Upplåst!',
    whichLetter: 'Vilken bokstav säger',
    you: 'Du',
}
