/* ============================================================================
   DIASPORA UI LANGUAGES
   ----------------------------------------------------------------------------
   Extra app-text languages for the countries with the largest Ethiopian &
   Eritrean communities: English (default), Amharic, German, Italian, Swedish,
   Dutch, Norwegian, French. English is every key's fallback, so these packs
   cover the high-visibility core (navigation, buttons, feedback, celebrations,
   Fidel Master, Tee Shop) plus the full REINFORCEMENT word lists; anything a
   pack omits simply shows in English. Best-effort translations, FLAGGED FOR
   NATIVE-SPEAKER REVIEW. (Hebrew/Arabic are also big diaspora languages but are
   right-to-left and need layout work first — tracked for a later pass.)
   ========================================================================== */

// Order shown in the picker. `label` is the language's own endonym.
export const LANG_META = [
  { id: 'en', label: 'English' },
  { id: 'am', label: 'አማርኛ' },
  { id: 'ti', label: 'ትግርኛ' },
  { id: 'de', label: 'Deutsch' },
  { id: 'it', label: 'Italiano' },
  { id: 'sv', label: 'Svenska' },
  { id: 'nl', label: 'Nederlands' },
  { id: 'no', label: 'Norsk' },
  { id: 'fr', label: 'Français' },
]
export const LANG_IDS = LANG_META.map((l) => l.id)

/* Reinforcement words spoken/shown on right (praise) and wrong (encourage)
   answers, per language. English lives here too so one helper serves both the
   main app and the Classic game. */
export const REINFORCE = {
  en: {
    praise: ['Great job!', 'Wonderful!', 'You are a star!', 'Brilliant!', 'Amazing!', 'Fantastic!', 'You did it!', 'Way to go!', 'Superb!', 'Awesome!'],
    encourage: ['Try again!', 'So close!', 'You can do it!', 'Almost!', 'Keep going!', 'Nearly there!', 'Give it another go!', 'Listen again!'],
  },
  am: {
    praise: ['ጎበዝ!', 'በጣም ጎበዝ!', 'ኮከብ ነህ!', 'ድንቅ!', 'እሰይ!', 'ግሩም!', 'አሪፍ!', 'ተባረክ!', 'ዋው!'],
    encourage: ['እንደገና ሞክር!', 'ተቃርበሃል!', 'ትችላለህ!', 'አይዞህ!', 'በርታ!', 'ደግመህ ስማ!'],
  },
  // Tigrinya (best-effort; flagged for native-speaker review).
  ti: {
    praise: ['ጽቡቕ!', 'ኣዝዩ ጽቡቕ!', 'ኮኸብ ኢኻ!', 'ግሩም!', 'ብሉጽ!', 'መስተንክር!', 'ሰሪሕካዮ!', 'ኣንቱም!', 'ዋው!'],
    encourage: ['ደጊምካ ፈትን!', 'ተቐሪብካ!', 'ትኽእሎ ኢኻ!', 'ኣይዞኻ!', 'ቀጽል!', 'ደጊምካ ስማዕ!'],
  },
  de: {
    praise: ['Super!', 'Toll gemacht!', 'Du bist ein Star!', 'Klasse!', 'Fantastisch!', 'Wunderbar!', 'Du hast es geschafft!', 'Ausgezeichnet!', 'Bravo!'],
    encourage: ['Versuch es nochmal!', 'Fast!', 'Du schaffst das!', 'Weiter so!', 'Hör nochmal zu!', 'Beinahe!'],
  },
  it: {
    praise: ['Bravo!', 'Ottimo lavoro!', 'Sei una stella!', 'Fantastico!', 'Magnifico!', 'Ce l’hai fatta!', 'Eccellente!', 'Meraviglioso!', 'Evviva!'],
    encourage: ['Riprova!', 'Quasi!', 'Ce la puoi fare!', 'Continua così!', 'Ascolta di nuovo!', 'Ci sei quasi!'],
  },
  sv: {
    praise: ['Bra jobbat!', 'Toppen!', 'Du är en stjärna!', 'Fantastiskt!', 'Underbart!', 'Du klarade det!', 'Utmärkt!', 'Superbra!', 'Hurra!'],
    encourage: ['Försök igen!', 'Nästan!', 'Du klarar det!', 'Fortsätt så!', 'Lyssna igen!', 'Du är nästan där!'],
  },
  nl: {
    praise: ['Goed gedaan!', 'Geweldig!', 'Je bent een ster!', 'Fantastisch!', 'Prachtig!', 'Het is je gelukt!', 'Uitstekend!', 'Super!', 'Hoera!'],
    encourage: ['Probeer opnieuw!', 'Bijna!', 'Jij kan het!', 'Ga zo door!', 'Luister nog eens!', 'Je bent er bijna!'],
  },
  no: {
    praise: ['Bra jobba!', 'Kjempebra!', 'Du er en stjerne!', 'Fantastisk!', 'Flott!', 'Du klarte det!', 'Utmerket!', 'Supert!', 'Hurra!'],
    encourage: ['Prøv igjen!', 'Nesten!', 'Du klarer det!', 'Fortsett sånn!', 'Hør en gang til!', 'Du er nesten der!'],
  },
  fr: {
    praise: ['Bravo !', 'Super !', 'Tu es une star !', 'Génial !', 'Fantastique !', 'Magnifique !', 'Tu as réussi !', 'Excellent !', 'Formidable !'],
    encourage: ['Essaie encore !', 'Presque !', 'Tu peux le faire !', 'Continue !', 'Écoute encore !', 'Tu y es presque !'],
  },
}

/* Core UI strings per new language. English (inline fallbacks in t() calls)
   fills every gap, so this is the frequently-seen surface, not every key. */
export const LANGPACKS = {
  de: {
    tagline: 'Lerne das Fidel-Alphabet mit Anbessa',
    playLevel: 'Spielen', backpack: 'Rucksack', home: 'Start', continue: 'Weiter', gotIt: 'Verstanden',
    nice: 'Toll!', amazing: 'Fantastisch! {n} in Folge!', notQuite: 'Nicht ganz!', tryAgain: '— hör zu und versuch es nochmal',
    yourTurn: 'Jetzt sagst du es!', levelComplete: 'Level geschafft!', playAgain: 'Nochmal spielen', listen: 'Hör zu…',
    classicTitle: 'Klassisches Spiel', classicSub: 'Reihen singen, Buchstaben nachfahren, erste Wörter lernen',
    explorerTitle: 'Buchstaben-Entdecker', explorerSub: 'Tippe eine der 231 Silben, um sie zu hören',
    grownups: 'Für Erwachsene: Fortschritt und Tipps', practiceTitle: 'Sternen-Übung',
    wordsTitle: 'Erste Wörter', wordsSub: 'Höre das Wort, tippe sein Bild', whichStart: 'Mit welchem Buchstaben beginnt es?',
    popHint: 'Zerplatze die Blase!', familyDone: 'Familie gemeistert!', traceHint: 'Hör zu und fahre den Buchstaben mit dem Finger nach',
    hearIt: 'Nochmal hören', traceClear: 'Löschen', traceCheck: 'Prüfen', start: 'Start', langText: 'App-Sprache', langLearn: 'Lernsprache',
    teeTitle: 'Anbessa T-Shirt-Shop', teeSub: 'Verdiene und trage deine Alphabet-Shirts', teeOrder: 'Echtes Shirt bestellen', teeSave: 'Design speichern',
    masterTitle: 'Fidel-Meister', masterChart: 'Tafel', masterAuto: 'Auto-Stimme', masterSay: 'Sprich', masterAbugida: 'Abugida', masterPlayAbugida: 'Ganze Abugida abspielen',
    sayGreat: 'Perfekt! ⭐', sayGood: 'Guter Versuch!', sayAgain: 'Sag es nochmal mit mir', saySayIt: 'Sprich es', sayWithMe: 'Sprich mit mir', sayListening: 'Ich höre zu…', sayScore: 'Punkte',
    closetTitle: 'Anbessas Kleiderschrank', closetSub: 'Ziehe Anbessa an und teile es!', keepGoing: 'Weiter so!',
    back: 'Zurück', playAll: 'Alle abspielen', stop: 'Stopp', pace_slow: 'Langsam', pace_normal: 'Normal', pace_fast: 'Schnell',
    exploreHeader: 'Buchstaben-Entdecker', exploreHeaderSub: 'Wähle einen Vokal und tippe eine Familie, um sie zu hören',
    exploreFamilyTitle: 'Die {name}-Familie', exploreFamilySub: 'Sieben Formen, ein Buchstabe — tippe, um jede zu hören',
    closetShort: 'Kleiderschrank', teeShort: 'T-Shirt-Shop', wordsShort: 'Erste Wörter', explorerShort: 'Entdecker', classicShort: 'Klassisch', practiceShort: 'Üben', familyShort: 'Familie', fvShort: 'Familienstimme', nameShort: 'Mein Name', grownupsShort: 'Erwachsene', giftShort: 'Geschenk', reviewShort: 'Rezension',
    nameTitle: 'Schreib deinen Namen', nameSub: 'Buchstabiere ihn im Fidel, Laut für Laut',
    nameHint: 'Wähle unten einen Vokal, tippe dann Buchstaben, um deinen Namen zu schreiben.',
    namePlay: 'Namen anhören', nameBackspace: 'Letzten Buchstaben entfernen', nameClear: 'Löschen', nameVowel: 'Vokal', nameLetters: 'Buchstaben', nameShare: 'Meinen Namen teilen',
    namePrivacy: 'Die Karte wird auf diesem Gerät erstellt. Es wird nichts geteilt, außer du tippst auf Teilen.',
    fvTitle: 'Familienstimme', fvSub: 'Lass Anbessa mit der Stimme eines lieben Menschen sprechen', fvWhoSpeaks: 'Wer spricht?', fvDefault: 'Standard', fvImport: 'Stimme importieren', fvForGrownups: 'Für Erwachsene', fvRecordBtn: 'Neue Stimme aufnehmen', fvNoMic: 'Aufnehmen braucht ein Mikrofon — nutze ein Handy oder Tablet.',
    streakDays: '{n} Tage in Folge', chapterDone: 'Kapitel {n} geschafft!', earnedItem: 'Anbessa hat {item} bekommen!', shareMilestone: '{name} hat {n} Buchstaben gelernt!',
    huntShort: 'Tägliche Jagd', huntTitle: 'Tägliche Buchstabenjagd', huntSub: 'Jibby hat die Buchstaben versteckt! Finde sie nach Gehör',
    huntFind: 'Finde den Buchstaben, der so klingt', huntListen: 'Den Laut nochmal hören', huntDoneTitle: 'Du hast alle gefunden!',
    huntTreasure: 'Den Schatz öffnen', huntTomorrow: 'Komm morgen wieder — Jibby versteckt neue Buchstaben!',
    huntGo: 'Jibby hat die heutigen Buchstaben versteckt — finde sie!', huntDoneChip: 'Heute geschafft — morgen neue Jagd!', huntFoundOne: 'gefunden', huntHidden: 'versteckter Buchstabe',
    pcShort: 'Postkarte', pcTitle: 'Sprachpostkarte', pcSub: 'Schick deine Stimme an einen lieben Menschen',
    pcHint: 'Sag „Selam!“, sag deine neuesten Buchstaben oder sing — Oma und Opa hören dich so gern.',
    pcRecord: 'Aufnehmen', pcStop: 'Stopp', pcListen: 'Anhören', pcRedo: 'Nochmal aufnehmen', pcSend: 'An die Familie senden', pcSendAgain: 'Nochmal senden',
    pcGateIntro: 'Senden ist für Erwachsene — du wählst, wer sie bekommt.', pcShared: 'Postkarte gesendet!', pcSaved: 'Gespeichert! Teile sie überall.',
    pcPrivacy: 'Die Aufnahme bleibt auf diesem Gerät. Sie reist nur, wenn ein Erwachsener sie sendet.',
    celebPostcard: 'Schick das der Familie!',
    calToday: 'Heute', hol_enkutatash: 'Enkutatash — Frohes neues Jahr!', hol_meskel: 'Meskel — das Fest des Kreuzes', hol_genna: 'Genna — Frohe Weihnachten!', hol_timkat: 'Timkat — Epiphanias!', hol_adwa: 'Adwa-Siegestag', hol_eritrea: 'Eritreischer Unabhängigkeitstag',
    aFriend: 'Ein Freund',
    bestStreak: 'Beste Serie',
    catchHint: 'Füttere Anbessa, bevor Jibby ihn schnappt!',
    ccApply: 'Anwenden',
    ccBlurb: 'Hast du einen Code von einer Kirche, Schule oder Gruppe? Gib ihn ein, damit sie Anerkennung bekommen.',
    ccChange: 'Ändern',
    ccPh: 'z. B. DEBRE',
    ccThanks: 'Danke — du unterstützt',
    ccTitle: 'Community-Code',
    challengeBack: 'Zurückfordern',
    challengeFriend: 'Fordere einen Freund heraus',
    challengeFrom: '${who} fordert dich heraus!',
    challengeGone: 'Diese Herausforderung ist nicht verfügbar.',
    challengeLose: 'Fast geschafft!',
    challengeScored: '${who} hat ${challenge.accuracy}% bei ${levelTitle} erreicht. Schaffst du mehr?',
    challengeShareText: 'Schlag meinen Fidel-Quest-Punktestand! Traust du dich?',
    challengeStart: 'Herausforderung annehmen',
    challengeTie: 'Unentschieden!',
    challengeTitle: 'Eine Herausforderung!',
    challengeWin: 'Du gewinnst!',
    champion: 'Fidel-Meister – jeder Stern verdient!',
    closetEmpty: 'Schließe Lektionen ab und verdiene Hüte, Schals und Umhänge für Anbessa!',
    dailyGift: 'Anbessas Geschenk öffnen',
    dismiss: 'Nicht jetzt',
    feedHint: 'Zieh den Buchstaben, den Kokeb sagt, zu Anbessa',
    firstTry: 'Erster Versuch',
    fvDefaultVoice: 'Zurück zur Standardstimme',
    fvDelete: 'Stimme löschen',
    fvEmpty: 'Noch keine Familienstimmen. Nimm eine auf oder importiere eine, die dir ein Verwandter geschickt hat.',
    fvGateIntro: 'Aufnehmen ist für Erwachsene – es nutzt das Mikrofon.',
    fvGreetingShort: 'Hallo!',
    fvGreetingSlot: 'Begrüßung',
    fvImportFail: 'Diese Datei ist keine Fidel-Quest-Stimme.',
    fvImported: 'Stimme importiert!',
    fvNameLabel: 'Name der Stimme',
    fvNamePh: 'Wessen Stimme? z. B. Oma',
    fvNowSpeaking: 'Anbessa spricht jetzt mit dieser Stimme',
    fvPrivacy: 'Stimmen bleiben auf diesem Gerät. Nichts wird hochgeladen – eine Stimme reist nur in der Datei, die du teilst.',
    fvRecordBlurb: 'Nimm die Buchstaben mit deiner eigenen Stimme auf und teile die Datei per WhatsApp mit deinem Kind. Auch Großeltern in der Ferne können für die Kinder hier aufnehmen – und andersherum.',
    fvRecordHint: 'Tippe einen Buchstaben zum Aufnehmen, tippe erneut zum Stoppen. Tippe ✓, um ihn anzuhören.',
    fvRecordTitle: 'Nimm deine Stimme auf',
    fvShare: 'Mit einem Kind teilen',
    fvUseVoice: 'Hier verwenden',
    giftAllDone: 'Du hast alles gesammelt – schön, dass du wieder da bist!',
    giftGot: 'Ein neues ${reward.name}!',
    giftTitle: 'Ein Geschenk von Anbessa!',
    goHome: 'Start',
    gpAccuracy: 'Genauigkeit',
    gpCorrect: 'richtig',
    gpHold: 'Halt mich',
    gpHoldHint: 'Zwei Sekunden gedrückt halten',
    gpIntro: 'Dieser Bereich ist für Erwachsene: Fortschrittsdetails und Übungstipps.',
    gpLessonStars: 'Lektionssterne',
    gpMastery: 'Buchstabenbeherrschung · ${events.length} Antworten erfasst',
    gpMasteryLegend: 'Grün: sicher · Gelb: fast · Rot: braucht Hilfe · Grau: noch nicht geübt. Quizze üben derzeit die Buchstaben erster Ordnung.',
    gpOpenExplorer: 'Im Explorer öffnen',
    gpPlayerName: 'Spielername',
    gpPlayerNameHint: 'Wird bei Herausforderungen an Freunde gezeigt. Optional – lass es leer, um "Ein Freund" zu bleiben. Es verlässt dieses Gerät nur in einem Herausforderungslink, den du teilst.',
    gpPlayerNamePh: 'z. B. Selam',
    gpReplayLevel: 'Level ${tip.level} wiederholen',
    gpReset: 'Ganzen Fortschritt zurücksetzen…',
    gpResetConfirm: 'Sterne, Bestwerte, Inseln und Lernverlauf löschen?',
    gpResetNo: 'Behalten',
    gpResetYes: 'Ja, löschen',
    gpRunnerBest: 'Runner-Bestwert',
    gpTapNumber: 'Tippe die Zahl ${challenge.word}',
    gpTrouble: 'Schwierige Buchstaben',
    gpTroubleFew: 'Noch zu wenig gespielt – schau nach ein paar Spielen wieder vorbei.',
    gpTroubleNone: 'Gerade keine schwierigen Buchstaben. Gut gemacht!',
    grownupsSub: 'Fortschritt, schwierige Buchstaben und Übungstipps',
    installCta: 'Hinzufügen',
    installHow: 'Wie?',
    installIosHint: 'Tippe auf Teilen, dann \'Zum Home-Bildschirm\'',
    installTitle: 'Füge Anbessa zu deinem Home-Bildschirm hinzu',
    jumpToStep: 'Zu meinem nächsten Schritt',
    learnSub: 'Lerne jeden Buchstaben, Schritt für Schritt',
    learnTitle: 'Buchstaben-Schritte',
    lettersLearned: '${stats.forms} / 231 Buchstaben gelernt',
    level: 'Level',
    linkCopied: 'Link kopiert!',
    masterInOrder: 'Der Reihe nach',
    masterLetters: 'Buchstaben',
    masterMixed: 'Gemischt',
    masterPause: 'Pause',
    masterPlay: 'Los',
    masterReshuffle: 'Neu mischen',
    mixDone: 'Toll gemischt!',
    munched: 'Gemampft!',
    myStep: 'Mein Schritt',
    newReward: 'Neu!',
    nextVowel: 'Dann der nächste Vokal',
    openCloset: 'Anbessas Kleiderschrank öffnen',
    practiceComplete: 'Übung abgeschlossen!',
    practicePraise: 'Die kniffligen Buchstaben werden immer stärker. Kokeb ist stolz auf dich!',
    remindBody: 'Komm, lerne heute einen Buchstaben.',
    remindDesc: 'Ein sanfter Anstoß jeden Nachmittag, um die Serie am Laufen zu halten.',
    remindTitle: 'Anbessa vermisst dich!',
    remindTitleLabel: 'Tägliche Erinnerung',
    runAgain: 'Nochmal laufen',
    runBest: 'Bestwert',
    runBossAttack: 'Jibby die Hyäne greift an!',
    runBossWin: 'Anbessas Buchstabenkraft gewinnt!',
    runMoveLeft: 'Nach links',
    runMoveRight: 'Nach rechts',
    runNewBest: 'Neuer Bestwert!',
    runQuit: 'Lauf beenden',
    saysWord: 'sagt',
    scopeAll: 'Alle Buchstaben',
    scopeLabel: 'Welche Buchstaben',
    scopeLearned: 'Meine Buchstaben',
    shareAnbessa: 'Anbessa teilen',
    shareSaved: 'Gespeichert! Teil es überall.',
    shareShowOff: 'Zeig es allen!',
    shareThanks: 'Danke fürs Teilen!',
    skyAllCleared: 'Alle vier Himmelsinseln befreit – Anbessa ist ein Fidel-Meister!',
    skyAllFree: 'jede Himmelsinsel ist frei!',
    skyBridge: 'die Brücke nach ${SESSIONS[st.session].place} ist gewachsen!',
    skyCleared: 'Insel befreit!',
    skyClearedSub: '${st.quiz.length} Buchstaben + 3 vor Jibby gerettet ·',
    skyHold: 'Jibby hält fest – hör noch einmal hin nach',
    skyLearnBtn: 'Sitzung ${nextLearn} lernen',
    skyLearnPrompt: 'lerne die Buchstaben von Sitzung ${nextLearn}, um den Baum zu wecken.',
    skyLearnTap: 'Tippe jede Frucht an, um ihren Buchstaben zu hören –',
    skyListenFirst: 'Hör dir zuerst alle an',
    skyMap: 'Karte',
    skyPlayBtn: 'Level ${nextLearn} spielen',
    skyPluck: 'Pflücke die Frucht, die sagt',
    skyReady: 'bereit für Level ${nextLearn}: es prüft Sitzungen 1–${nextLearn}!',
    skyReplay: 'Wiederholen:',
    skyRescued: 'Gerettet!',
    skyRight: 'Ja!',
    skySession: 'Sitzung',
    skyStartQuest: 'Level ${st.session}-Quest starten',
    skyStole: 'Jibby hat ${st.stolen.length} Buchstaben gestohlen!',
    skyWinBack: 'Hol den zurück, der sagt',
    skyWrong: 'Jibby kichert – hör noch einmal hin nach',
    skylandsTitle: 'Fidel Skylands',
    starHint: 'Zieh von Stern zu Stern und male das Sternbild',
    steerInto: 'Lenke Anbessa in',
    teeGrownup: 'Bestellen öffnet einen Shop – frag einen Erwachsenen.',
    teeIntro: 'Verdiene in jedem Kapitel ein neues T-Shirt-Design – Anbessa trägt dein Alphabet! Speichere das Bild oder bitte einen Erwachsenen, ein echtes Shirt zu bestellen.',
    teeLockedAt: 'Lerne ${design.unlock} Buchstaben',
    teeNext: 'Lerne noch ${Math.max(0, nextAt - families)} Familien, um das nächste Shirt freizuschalten!',
    teeOrdered: 'Öffne den Shop für einen Erwachsenen...',
    teeSaveHint: 'Speichere das Bild und drucke es auf jedes Shirt.',
    teeSaved: 'Design gespeichert! Druck es überall.',
    teeUnlocked: 'Freigeschaltet!',
    whichLetter: 'Welcher Buchstabe sagt',
    you: 'Du',
  },
  it: {
    tagline: "Impara l'alfabeto Fidel con Anbessa",
    playLevel: 'Gioca', backpack: 'Zaino', home: 'Home', continue: 'Continua', gotIt: 'Capito',
    nice: 'Bravo!', amazing: 'Fantastico! {n} di fila!', notQuite: 'Non proprio!', tryAgain: '— ascolta e riprova',
    yourTurn: 'Ora tocca a te!', levelComplete: 'Livello completato!', playAgain: 'Gioca ancora', listen: 'Ascolta…',
    classicTitle: 'Gioco Classico', classicSub: 'Canta gli ordini, traccia le lettere, impara le prime parole',
    explorerTitle: 'Esploratore di Lettere', explorerSub: 'Tocca una delle 231 sillabe per ascoltarla',
    grownups: 'Per i grandi: progressi e consigli', practiceTitle: 'Pratica Stella',
    wordsTitle: 'Prime Parole', wordsSub: 'Ascolta la parola, tocca la sua figura', whichStart: 'Con quale lettera inizia?',
    popHint: 'Fai scoppiare la bolla!', familyDone: 'Famiglia imparata!', traceHint: 'Ascolta, poi traccia la lettera con il dito',
    hearIt: 'Ascolta ancora', traceClear: 'Cancella', traceCheck: 'Controlla', start: 'Inizia', langText: 'Lingua app', langLearn: 'Lingua da imparare',
    teeTitle: 'Negozio T-shirt Anbessa', teeSub: 'Guadagna e indossa le tue magliette dell’alfabeto', teeOrder: 'Ordina una vera maglietta', teeSave: 'Salva il disegno',
    masterTitle: 'Maestro del Fidel', masterChart: 'Tabella', masterAuto: 'Voce auto', masterSay: 'Dillo', masterAbugida: 'Abugida', masterPlayAbugida: "Riproduci tutto l'Abugida",
    sayGreat: 'Perfetto! ⭐', sayGood: 'Bel tentativo!', sayAgain: 'Dillo ancora con me', saySayIt: 'Dillo', sayWithMe: 'Dillo con me', sayListening: 'Sto ascoltando…', sayScore: 'Punti',
    closetTitle: 'Armadio di Anbessa', closetSub: 'Vesti Anbessa e condividi!', keepGoing: 'Continua così!',
    back: 'Indietro', playAll: 'Riproduci tutto', stop: 'Ferma', pace_slow: 'Lento', pace_normal: 'Normale', pace_fast: 'Veloce',
    exploreHeader: 'Esploratore di Lettere', exploreHeaderSub: 'Scegli una vocale, poi tocca una famiglia per ascoltarla',
    exploreFamilyTitle: 'La famiglia {name}', exploreFamilySub: 'Sette forme, una lettera — tocca per ascoltare ognuna',
    closetShort: 'Armadio', teeShort: 'Negozio T-shirt', wordsShort: 'Prime Parole', explorerShort: 'Esplora', classicShort: 'Classico', practiceShort: 'Pratica', familyShort: 'Famiglia', fvShort: 'Voce di Famiglia', nameShort: 'Il mio nome', grownupsShort: 'Adulti', giftShort: 'Regalo', reviewShort: 'Recensione',
    nameTitle: 'Scrivi il tuo nome', nameSub: 'Scrivilo in Fidel, un suono alla volta',
    nameHint: 'Scegli una vocale qui sotto, poi tocca le lettere per scrivere il tuo nome.',
    namePlay: 'Ascolta il nome', nameBackspace: 'Togli l’ultima lettera', nameClear: 'Cancella', nameVowel: 'Vocale', nameLetters: 'Lettere', nameShare: 'Condividi il mio nome',
    namePrivacy: 'La scheda è creata su questo dispositivo. Niente viene condiviso finché non tocchi Condividi.',
    fvTitle: 'Voce di Famiglia', fvSub: 'Fai parlare Anbessa con la voce di una persona cara', fvWhoSpeaks: 'Chi parla?', fvDefault: 'Predefinita', fvImport: 'Importa una voce', fvForGrownups: 'Per i grandi', fvRecordBtn: 'Registra una nuova voce', fvNoMic: 'La registrazione richiede un microfono — usa un telefono o un tablet.',
    streakDays: '{n} giorni di fila', chapterDone: 'Capitolo {n} completato!', earnedItem: 'Anbessa ha ottenuto {item}!', shareMilestone: '{name} ha imparato {n} lettere!',
    huntShort: 'Caccia del giorno', huntTitle: 'Caccia alle lettere del giorno', huntSub: 'Jibby ha nascosto le lettere! Trovale con l’orecchio',
    huntFind: 'Trova la lettera che dice', huntListen: 'Riascolta il suono', huntDoneTitle: 'Le hai trovate tutte!',
    huntTreasure: 'Apri il tesoro', huntTomorrow: 'Torna domani — Jibby nasconderà nuove lettere!',
    huntGo: 'Jibby ha nascosto le lettere di oggi — trovale!', huntDoneChip: 'Fatto per oggi — nuova caccia domani!', huntFoundOne: 'trovata', huntHidden: 'lettera nascosta',
    pcShort: 'Cartolina', pcTitle: 'Cartolina vocale', pcSub: 'Manda la tua voce a chi ami',
    pcHint: 'Di’ «Selam!», di’ le tue lettere nuove o canta — i nonni adorano sentirti.',
    pcRecord: 'Registra', pcStop: 'Ferma', pcListen: 'Ascolta', pcRedo: 'Registra di nuovo', pcSend: 'Invia alla famiglia', pcSendAgain: 'Invia di nuovo',
    pcGateIntro: 'L’invio è per i grandi — scegli tu chi la riceve.', pcShared: 'Cartolina inviata!', pcSaved: 'Salvata! Condividila dove vuoi.',
    pcPrivacy: 'La registrazione resta su questo dispositivo. Parte solo quando un adulto la invia.',
    celebPostcard: 'Mandalo alla famiglia!',
    calToday: 'Oggi', hol_enkutatash: 'Enkutatash — Buon anno!', hol_meskel: 'Meskel — la festa della Croce', hol_genna: 'Genna — Buon Natale!', hol_timkat: 'Timkat — Epifania!', hol_adwa: 'Giorno della vittoria di Adwa', hol_eritrea: 'Festa dell’indipendenza eritrea',
    aFriend: 'Un amico',
    bestStreak: 'Serie migliore',
    catchHint: 'Nutri Anbessa prima che Jibby lo prenda!',
    ccApply: 'Applica',
    ccBlurb: 'Hai un codice da una chiesa, scuola o gruppo della comunità? Inseriscilo per dare loro il merito.',
    ccChange: 'Cambia',
    ccPh: 'es. DEBRE',
    ccThanks: 'Grazie — stai sostenendo',
    ccTitle: 'Codice comunità',
    challengeBack: 'Rilancia la sfida',
    challengeFriend: 'Sfida un amico',
    challengeFrom: '${who} ti sfida!',
    challengeGone: 'Questa sfida non è disponibile.',
    challengeLose: 'Per un pelo!',
    challengeScored: '${who} ha fatto ${challenge.accuracy}% in ${levelTitle}. Riesci a batterlo?',
    challengeShareText: 'Batti il mio punteggio a Fidel Quest! Ci riesci?',
    challengeStart: 'Accetta la sfida',
    challengeTie: 'È un pareggio!',
    challengeTitle: 'Una sfida!',
    challengeWin: 'Hai vinto!',
    champion: 'Campione del Fidel - ogni stella guadagnata!',
    closetEmpty: 'Finisci le lezioni per guadagnare cappelli, sciarpe e mantelli per Anbessa!',
    dailyGift: 'Apri il regalo di Anbessa',
    dismiss: 'Non ora',
    feedHint: 'Trascina la lettera che dice Kokeb verso Anbessa',
    firstTry: 'Al primo colpo',
    fvDefaultVoice: 'Torna alla voce predefinita',
    fvDelete: 'Elimina voce',
    fvEmpty: 'Ancora nessuna voce di famiglia. Registrane una, o importa una voce che ti ha mandato un parente.',
    fvGateIntro: 'La registrazione è per i grandi — usa il microfono.',
    fvGreetingShort: 'Ciao!',
    fvGreetingSlot: 'Saluto',
    fvImportFail: 'Questo file non è una voce di Fidel Quest.',
    fvImported: 'Voce importata!',
    fvNameLabel: 'Nome della voce',
    fvNamePh: 'Di chi è la voce? es. Nonna',
    fvNowSpeaking: 'Anbessa ora parla con questa voce',
    fvPrivacy: 'Le voci restano su questo dispositivo. Niente viene caricato — una voce viaggia solo nel file che scegli di condividere.',
    fvRecordBlurb: 'Registra le lettere con la tua voce, poi condividi il file con il tuo bambino via WhatsApp. Un nonno lontano può registrare per i bambini qui — e viceversa.',
    fvRecordHint: 'Tocca una lettera per registrarla, tocca di nuovo per fermare. Tocca ✓ per riascoltarla.',
    fvRecordTitle: 'Registra la tua voce',
    fvShare: 'Condividi con un bambino',
    fvUseVoice: 'Usala qui',
    giftAllDone: 'Hai raccolto tutto - che bello che sei tornato!',
    giftGot: 'Un nuovo ${reward.name}!',
    giftTitle: 'Un regalo da Anbessa!',
    goHome: 'Home',
    gpAccuracy: 'Precisione',
    gpCorrect: 'corretti',
    gpHold: 'Tienimi premuto',
    gpHoldHint: 'Premi e tieni premuto per due secondi',
    gpIntro: 'Quest\'area è per i grandi: dettagli sui progressi e consigli per esercitarsi.',
    gpLessonStars: 'Stelle delle lezioni',
    gpMastery: 'Padronanza delle lettere · ${events.length} risposte registrate',
    gpMasteryLegend: 'Verde: solido · Giallo: quasi · Rosso: serve aiuto · Grigio: non ancora esercitato. I quiz al momento esercitano le lettere di prim\'ordine.',
    gpOpenExplorer: 'Apri in Esploratore',
    gpPlayerName: 'Nome giocatore',
    gpPlayerNameHint: 'Mostrato nelle sfide che mandi agli amici. Facoltativo — lascialo vuoto per restare "Un amico". Non lascia mai questo dispositivo se non dentro un link di sfida che scegli di condividere.',
    gpPlayerNamePh: 'es. Selam',
    gpReplayLevel: 'Rigioca il Livello ${tip.level}',
    gpReset: 'Azzera tutti i progressi…',
    gpResetConfirm: 'Cancellare stelle, record, isole e cronologia di apprendimento?',
    gpResetNo: 'Tieni tutto',
    gpResetYes: 'Sì, cancella',
    gpRunnerBest: 'Record Corsa',
    gpTapNumber: 'Tocca il numero ${challenge.word}',
    gpTrouble: 'Lettere difficili',
    gpTroubleFew: 'Ancora troppo poco gioco — ricontrolla dopo qualche partita.',
    gpTroubleNone: 'Nessuna lettera difficile ora. Bravo!',
    grownupsSub: 'Progressi, lettere difficili e consigli per esercitarsi',
    installCta: 'Aggiungi',
    installHow: 'Come?',
    installIosHint: 'Tocca il pulsante Condividi, poi \'Aggiungi a Home\'',
    installTitle: 'Aggiungi Anbessa alla tua schermata Home',
    jumpToStep: 'Vai al mio prossimo passo',
    learnSub: 'Impara ogni lettera, un passo alla volta',
    learnTitle: 'Passi delle Lettere',
    lettersLearned: '${stats.forms} / 231 lettere imparate',
    level: 'Livello',
    linkCopied: 'Link copiato!',
    masterInOrder: 'In ordine',
    masterLetters: 'lettere',
    masterMixed: 'Mescolate',
    masterPause: 'Pausa',
    masterPlay: 'Play',
    masterReshuffle: 'Rimescola',
    mixDone: 'Bella mescolata!',
    munched: 'Sgranocchiato!',
    myStep: 'Il mio passo',
    newReward: 'Nuovo!',
    nextVowel: 'Poi la vocale seguente',
    openCloset: 'Apri l\'Armadio di Anbessa',
    practiceComplete: 'Esercizio completato!',
    practicePraise: 'Quelle lettere difficili stanno diventando più forti. Kokeb è fiero di te!',
    remindBody: 'Vieni a imparare una lettera oggi.',
    remindDesc: 'Una gentile spinta ogni pomeriggio per non perdere la serie.',
    remindTitle: 'Anbessa ti manca!',
    remindTitleLabel: 'Promemoria giornaliero',
    runAgain: 'Corri di nuovo',
    runBest: 'Record',
    runBossAttack: 'Jibby la iena attacca!',
    runBossWin: 'Il potere delle lettere di Anbessa vince!',
    runMoveLeft: 'Vai a sinistra',
    runMoveRight: 'Vai a destra',
    runNewBest: 'Nuovo record!',
    runQuit: 'Esci dalla corsa',
    saysWord: 'dice',
    scopeAll: 'Tutte le lettere',
    scopeLabel: 'Quali lettere',
    scopeLearned: 'Le mie lettere',
    shareAnbessa: 'Condividi Anbessa',
    shareSaved: 'Salvato! Condividilo ovunque.',
    shareShowOff: 'Mostralo a tutti!',
    shareThanks: 'Grazie per aver condiviso!',
    skyAllCleared: 'Tutte e quattro le isole del cielo liberate — Anbessa è un Campione del Fidel!',
    skyAllFree: 'ogni isola del cielo è libera!',
    skyBridge: 'il ponte verso ${SESSIONS[st.session].place} è cresciuto!',
    skyCleared: 'Isola liberata!',
    skyClearedSub: '${st.quiz.length} lettere + 3 salvate da Jibby ·',
    skyHold: 'Jibby tiene stretto — riascolta per',
    skyLearnBtn: 'Impara la Sessione ${nextLearn}',
    skyLearnPrompt: 'impara le lettere della Sessione ${nextLearn} per svegliare l\'albero.',
    skyLearnTap: 'Tocca ogni frutto per sentire la sua lettera —',
    skyListenFirst: 'Ascoltale tutte prima',
    skyMap: 'Mappa',
    skyPlayBtn: 'Gioca al Livello ${nextLearn}',
    skyPluck: 'Cogli il frutto che dice',
    skyReady: 'pronto per il Livello ${nextLearn}: mette alla prova le Sessioni 1–${nextLearn}!',
    skyReplay: 'Rigioca:',
    skyRescued: 'Salvata!',
    skyRight: 'Sì!',
    skySession: 'Sessione',
    skyStartQuest: 'Inizia la missione del Livello ${st.session}',
    skyStole: 'Jibby ha rubato ${st.stolen.length} lettere!',
    skyWinBack: 'Riconquista quella che dice',
    skyWrong: 'Jibby ridacchia — riascolta per',
    skylandsTitle: 'Isole del Cielo del Fidel',
    starHint: 'Scorri da stella a stella e disegna la costellazione',
    steerInto: 'Guida Anbessa verso',
    teeGrownup: 'Ordinare apre un negozio — chiedi a un grande.',
    teeIntro: 'Guadagna un nuovo disegno di maglietta a ogni capitolo — Anbessa indossa il tuo alfabeto! Salva l\'immagine o chiedi a un grande di ordinare una maglietta vera.',
    teeLockedAt: 'Impara ${design.unlock} lettere',
    teeNext: 'Impara altre ${Math.max(0, nextAt - families)} famiglie per sbloccare la prossima maglietta!',
    teeOrdered: 'Apro il negozio per un grande...',
    teeSaveHint: 'Salva l\'immagine e stampala su qualsiasi maglietta.',
    teeSaved: 'Disegno salvato! Stampalo ovunque.',
    teeUnlocked: 'Sbloccato!',
    whichLetter: 'Quale lettera dice',
    you: 'Tu',
  },
  sv: {
    tagline: 'Lär dig Fidel-alfabetet med Anbessa',
    playLevel: 'Spela', backpack: 'Ryggsäck', home: 'Hem', continue: 'Fortsätt', gotIt: 'Klart',
    nice: 'Bra!', amazing: 'Fantastiskt! {n} i rad!', notQuite: 'Inte riktigt!', tryAgain: '— lyssna och försök igen',
    yourTurn: 'Nu säger du det!', levelComplete: 'Nivå klar!', playAgain: 'Spela igen', listen: 'Lyssna…',
    classicTitle: 'Klassiskt spel', classicSub: 'Sjung ordningarna, spåra bokstäver, lär dig första orden',
    explorerTitle: 'Bokstavsutforskaren', explorerSub: 'Tryck på någon av de 231 stavelserna för att höra den',
    grownups: 'För vuxna: framsteg och tips', practiceTitle: 'Stjärnövning',
    wordsTitle: 'Första orden', wordsSub: 'Hör ordet, tryck på bilden', whichStart: 'Vilken bokstav börjar det med?',
    popHint: 'Poppa bubblan!', familyDone: 'Familjen klar!', traceHint: 'Lyssna och spåra bokstaven med fingret',
    hearIt: 'Hör igen', traceClear: 'Rensa', traceCheck: 'Kolla', start: 'Start', langText: 'Appspråk', langLearn: 'Språk att lära',
    teeTitle: 'Anbessas T-shirtbutik', teeSub: 'Tjäna och bär dina alfabets-t-shirtar', teeOrder: 'Beställ en riktig t-shirt', teeSave: 'Spara designen',
    masterTitle: 'Fidel-mästare', masterChart: 'Tabell', masterAuto: 'Auto-röst', masterSay: 'Säg det', masterAbugida: 'Abugida', masterPlayAbugida: 'Spela hela Abugidan',
    sayGreat: 'Perfekt! ⭐', sayGood: 'Bra försök!', sayAgain: 'Säg det igen med mig', saySayIt: 'Säg det', sayWithMe: 'Säg med mig', sayListening: 'Jag lyssnar…', sayScore: 'Poäng',
    closetTitle: 'Anbessas garderob', closetSub: 'Klä upp Anbessa och dela!', keepGoing: 'Fortsätt så!',
    back: 'Tillbaka', playAll: 'Spela alla', stop: 'Stopp', pace_slow: 'Långsam', pace_normal: 'Normal', pace_fast: 'Snabb',
    exploreHeader: 'Bokstavsutforskaren', exploreHeaderSub: 'Välj en vokal och tryck på en familj för att höra den',
    exploreFamilyTitle: 'Familjen {name}', exploreFamilySub: 'Sju former, en bokstav — tryck för att höra var och en',
    closetShort: 'Garderob', teeShort: 'T-shirtbutik', wordsShort: 'Första orden', explorerShort: 'Utforska', classicShort: 'Klassisk', practiceShort: 'Öva', familyShort: 'Familj', fvShort: 'Familjeröst', nameShort: 'Mitt namn', grownupsShort: 'Vuxna', giftShort: 'Present', reviewShort: 'Recension',
    nameTitle: 'Skriv ditt namn', nameSub: 'Stava det i Fidel, ett ljud i taget',
    nameHint: 'Välj ett vokalljud nedan, tryck sedan på bokstäver för att stava ditt namn.',
    namePlay: 'Hör namnet', nameBackspace: 'Ta bort sista bokstaven', nameClear: 'Rensa', nameVowel: 'Vokalljud', nameLetters: 'Bokstäver', nameShare: 'Dela mitt namn',
    namePrivacy: 'Kortet skapas på den här enheten. Inget delas om du inte trycker på Dela.',
    fvTitle: 'Familjeröst', fvSub: 'Låt Anbessa tala med en kär persons röst', fvWhoSpeaks: 'Vem talar?', fvDefault: 'Standard', fvImport: 'Importera en röst', fvForGrownups: 'För vuxna', fvRecordBtn: 'Spela in en ny röst', fvNoMic: 'Inspelning kräver en mikrofon — använd en telefon eller surfplatta.',
    streakDays: '{n} dagar i rad', chapterDone: 'Kapitel {n} klart!', earnedItem: 'Anbessa fick {item}!', shareMilestone: '{name} lärde sig {n} bokstäver!',
    huntShort: 'Dagens jakt', huntTitle: 'Dagens bokstavsjakt', huntSub: 'Jibby har gömt bokstäverna! Hitta dem på ljudet',
    huntFind: 'Hitta bokstaven som säger', huntListen: 'Hör ljudet igen', huntDoneTitle: 'Du hittade alla!',
    huntTreasure: 'Öppna skatten', huntTomorrow: 'Kom tillbaka i morgon — Jibby gömmer nya bokstäver!',
    huntGo: 'Jibby har gömt dagens bokstäver — hitta dem!', huntDoneChip: 'Klart för idag — ny jakt i morgon!', huntFoundOne: 'hittad', huntHidden: 'gömd bokstav',
    pcShort: 'Vykort', pcTitle: 'Röstvykort', pcSub: 'Skicka din röst till någon du älskar',
    pcHint: 'Säg ”Selam!”, säg dina nyaste bokstäver eller sjung — mormor och farfar älskar att höra dig.',
    pcRecord: 'Spela in', pcStop: 'Stopp', pcListen: 'Lyssna', pcRedo: 'Spela in igen', pcSend: 'Skicka till familjen', pcSendAgain: 'Skicka igen',
    pcGateIntro: 'Att skicka är för vuxna — du väljer vem som får det.', pcShared: 'Vykortet skickat!', pcSaved: 'Sparat! Dela det var som helst.',
    pcPrivacy: 'Inspelningen stannar på den här enheten. Den skickas bara när en vuxen skickar den.',
    celebPostcard: 'Skicka det till familjen!',
    calToday: 'Idag', hol_enkutatash: 'Enkutatash — Gott nytt år!', hol_meskel: 'Meskel — korsets högtid', hol_genna: 'Genna — God jul!', hol_timkat: 'Timkat — trettondagen!', hol_adwa: 'Adwa-segerdagen', hol_eritrea: 'Eritreas självständighetsdag',
    aFriend: 'En kompis',
    bestStreak: 'Bästa svit',
    catchHint: 'Mata Anbessa innan Jibby tar den!',
    ccApply: 'Använd',
    ccBlurb: 'Har du en kod från en kyrka, skola eller förening? Skriv in den så får de äran.',
    ccChange: 'Ändra',
    ccPh: 't.ex. DEBRE',
    ccThanks: 'Tack — du stöttar',
    ccTitle: 'Föreningskod',
    challengeBack: 'Utmana tillbaka',
    challengeFriend: 'Utmana en kompis',
    challengeFrom: '${who} utmanar dig!',
    challengeGone: 'Den här utmaningen finns inte längre.',
    challengeLose: 'Så nära!',
    challengeScored: '${who} fick ${challenge.accuracy}% på ${levelTitle}. Kan du slå det?',
    challengeShareText: 'Slå mitt resultat i Fidel Quest! Klarar du det?',
    challengeStart: 'Anta utmaningen',
    challengeTie: 'Det blev oavgjort!',
    challengeTitle: 'En utmaning!',
    challengeWin: 'Du vinner!',
    champion: 'Fidel-mästare - varje stjärna tagen!',
    closetEmpty: 'Klara lektioner för att vinna hattar, halsdukar och mantlar till Anbessa!',
    dailyGift: 'Öppna Anbessas present',
    dismiss: 'Inte nu',
    feedHint: 'Dra bokstaven som Kokeb säger till Anbessa',
    firstTry: 'Första försöket',
    fvDefaultVoice: 'Tillbaka till standardrösten',
    fvDelete: 'Radera röst',
    fvEmpty: 'Inga familjeröster än. Spela in en, eller importera en röst som en släkting skickat.',
    fvGateIntro: 'Inspelning är för vuxna — den använder mikrofonen.',
    fvGreetingShort: 'Hej!',
    fvGreetingSlot: 'Hälsning',
    fvImportFail: 'Den filen är ingen Fidel Quest-röst.',
    fvImported: 'Rösten importerad!',
    fvNameLabel: 'Röstens namn',
    fvNamePh: 'Vems röst? t.ex. Mormor',
    fvNowSpeaking: 'Anbessa pratar nu med den här rösten',
    fvPrivacy: 'Röster stannar på den här enheten. Inget laddas upp — en röst reser bara i filen du väljer att dela.',
    fvRecordBlurb: 'Spela in bokstäverna med din egen röst och dela filen med ditt barn via WhatsApp. En mor- eller farförälder långt borta kan spela in åt barnen här — och tvärtom.',
    fvRecordHint: 'Tryck på en bokstav för att spela in, tryck igen för att stoppa. Tryck ✓ för att lyssna.',
    fvRecordTitle: 'Spela in din röst',
    fvShare: 'Dela med ett barn',
    fvUseVoice: 'Använd den här',
    giftAllDone: 'Du har samlat allt - så glad att du kom tillbaka!',
    giftGot: 'En ny ${reward.name}!',
    giftTitle: 'En present från Anbessa!',
    goHome: 'Hem',
    gpAccuracy: 'Träffsäkerhet',
    gpCorrect: 'rätt',
    gpHold: 'Håll mig',
    gpHoldHint: 'Tryck och håll i två sekunder',
    gpIntro: 'Det här området är för vuxna: framsteg i detalj och övningstips.',
    gpLessonStars: 'Lektionsstjärnor',
    gpMastery: 'Bokstavskunskap · ${events.length} svar sparade',
    gpMasteryLegend: 'Grön: säker · Gul: på gång · Röd: behöver hjälp · Grå: inte övad än. Frågesporterna övar just nu första ordningens bokstäver.',
    gpOpenExplorer: 'Öppna i Utforskaren',
    gpPlayerName: 'Spelarnamn',
    gpPlayerNameHint: 'Visas på utmaningar du skickar till kompisar. Frivilligt — lämna tomt för att förbli "En kompis". Det lämnar aldrig den här enheten utom i en utmaningslänk du väljer att dela.',
    gpPlayerNamePh: 't.ex. Selam',
    gpReplayLevel: 'Spela nivå ${tip.level} igen',
    gpReset: 'Nollställ alla framsteg…',
    gpResetConfirm: 'Radera stjärnor, rekord, öar och inlärningshistorik?',
    gpResetNo: 'Behåll',
    gpResetYes: 'Ja, radera',
    gpRunnerBest: 'Löprekord',
    gpTapNumber: 'Tryck på talet ${challenge.word}',
    gpTrouble: 'Kluriga bokstäver',
    gpTroubleFew: 'Inte tillräckligt spelat än — kom tillbaka efter några spel.',
    gpTroubleNone: 'Inga kluriga bokstäver just nu. Bra jobbat!',
    grownupsSub: 'Framsteg, kluriga bokstäver och övningstips',
    installCta: 'Lägg till',
    installHow: 'Hur?',
    installIosHint: 'Tryck på Dela-knappen och sedan \'Lägg till på hemskärmen\'',
    installTitle: 'Lägg till Anbessa på hemskärmen',
    jumpToStep: 'Gå till mitt nästa steg',
    learnSub: 'Lär dig varje bokstav, ett steg i taget',
    learnTitle: 'Bokstavssteg',
    lettersLearned: '${stats.forms} / 231 bokstäver lärda',
    level: 'Nivå',
    linkCopied: 'Länk kopierad!',
    masterInOrder: 'I ordning',
    masterLetters: 'bokstäver',
    masterMixed: 'Blandat',
    masterPause: 'Pausa',
    masterPlay: 'Spela',
    masterReshuffle: 'Blanda om',
    mixDone: 'Bra blandat!',
    munched: 'Mumsat!',
    myStep: 'Mitt steg',
    newReward: 'Ny!',
    nextVowel: 'Sedan nästa vokal',
    openCloset: 'Öppna Anbessas garderob',
    practiceComplete: 'Övningen klar!',
    practicePraise: 'De kluriga bokstäverna blir starkare. Kokeb är stolt över dig!',
    remindBody: 'Kom och lär dig en bokstav idag.',
    remindDesc: 'En vänlig knuff varje eftermiddag för att hålla sviten vid liv.',
    remindTitle: 'Anbessa saknar dig!',
    remindTitleLabel: 'Daglig påminnelse',
    runAgain: 'Spring igen',
    runBest: 'Bäst',
    runBossAttack: 'Jibby hyenan attackerar!',
    runBossWin: 'Anbessas bokstavskraft vinner!',
    runMoveLeft: 'Åt vänster',
    runMoveRight: 'Åt höger',
    runNewBest: 'Nytt rekord!',
    runQuit: 'Avsluta löpning',
    saysWord: 'säger',
    scopeAll: 'Alla bokstäver',
    scopeLabel: 'Vilka bokstäver',
    scopeLearned: 'Mina bokstäver',
    shareAnbessa: 'Dela Anbessa',
    shareSaved: 'Sparat! Dela var du vill.',
    shareShowOff: 'Visa alla!',
    shareThanks: 'Tack för att du delar!',
    skyAllCleared: 'Alla fyra skyöar klarade — Anbessa är en Fidel-mästare!',
    skyAllFree: 'varje skyö är fri!',
    skyBridge: 'bron till ${SESSIONS[st.session].place} har växt fram!',
    skyCleared: 'Ön klarad!',
    skyClearedSub: '${st.quiz.length} bokstäver + 3 räddade från Jibby ·',
    skyHold: 'Jibby håller hårt — lyssna igen efter',
    skyLearnBtn: 'Lär pass ${nextLearn}',
    skyLearnPrompt: 'lär pass ${nextLearn}s bokstäver för att väcka trädet.',
    skyLearnTap: 'Tryck på varje frukt för att höra dess bokstav —',
    skyListenFirst: 'Lyssna på alla först',
    skyMap: 'Karta',
    skyPlayBtn: 'Spela nivå ${nextLearn}',
    skyPluck: 'Plocka frukten som säger',
    skyReady: 'redo för nivå ${nextLearn}: den testar pass 1–${nextLearn}!',
    skyReplay: 'Spela igen:',
    skyRescued: 'Räddad!',
    skyRight: 'Ja!',
    skySession: 'Pass',
    skyStartQuest: 'Starta uppdrag nivå ${st.session}',
    skyStole: 'Jibby stal ${st.stolen.length} bokstäver!',
    skyWinBack: 'Vinn tillbaka den som säger',
    skyWrong: 'Jibby fnissar — lyssna igen efter',
    skylandsTitle: 'Fidel Skylands',
    starHint: 'Dra från stjärna till stjärna och rita stjärnbilden',
    steerInto: 'Styr Anbessa in i',
    teeGrownup: 'Beställning öppnar en butik — fråga en vuxen.',
    teeIntro: 'Vinn en ny tröjdesign varje kapitel — Anbessa bär ditt alfabet! Spara bilden eller be en vuxen beställa en riktig tröja.',
    teeLockedAt: 'Lär ${design.unlock} bokstäver',
    teeNext: 'Lär ${Math.max(0, nextAt - families)} familjer till för att låsa upp nästa tröja!',
    teeOrdered: 'Öppnar butiken för en vuxen...',
    teeSaveHint: 'Spara bilden och tryck den på vilken tröja som helst.',
    teeSaved: 'Design sparad! Tryck den var du vill.',
    teeUnlocked: 'Upplåst!',
    whichLetter: 'Vilken bokstav säger',
    you: 'Du',
  },
  nl: {
    tagline: 'Leer het Fidel-alfabet met Anbessa',
    playLevel: 'Spelen', backpack: 'Rugzak', home: 'Home', continue: 'Verder', gotIt: 'Begrepen',
    nice: 'Goed zo!', amazing: 'Geweldig! {n} op een rij!', notQuite: 'Net niet!', tryAgain: '— luister en probeer opnieuw',
    yourTurn: 'Nu zeg jij het!', levelComplete: 'Level voltooid!', playAgain: 'Opnieuw spelen', listen: 'Luister…',
    classicTitle: 'Klassiek spel', classicSub: 'Zing de rijen, teken letters, leer eerste woorden',
    explorerTitle: 'Letterontdekker', explorerSub: 'Tik op een van de 231 lettergrepen om te horen',
    grownups: 'Voor volwassenen: voortgang en tips', practiceTitle: 'Steroefening',
    wordsTitle: 'Eerste woorden', wordsSub: 'Hoor het woord, tik op het plaatje', whichStart: 'Met welke letter begint het?',
    popHint: 'Prik de bel!', familyDone: 'Familie geleerd!', traceHint: 'Luister en trek de letter na met je vinger',
    hearIt: 'Nog eens horen', traceClear: 'Wissen', traceCheck: 'Check', start: 'Start', langText: 'App-taal', langLearn: 'Leertaal',
    teeTitle: 'Anbessa T-shirtwinkel', teeSub: 'Verdien en draag je alfabet-shirts', teeOrder: 'Bestel een echt shirt', teeSave: 'Ontwerp opslaan',
    masterTitle: 'Fidel-meester', masterChart: 'Tabel', masterAuto: 'Auto-stem', masterSay: 'Zeg het', masterAbugida: 'Abugida', masterPlayAbugida: 'Speel de hele Abugida',
    sayGreat: 'Perfect! ⭐', sayGood: 'Goede poging!', sayAgain: 'Zeg het nog eens met mij', saySayIt: 'Zeg het', sayWithMe: 'Zeg met mij mee', sayListening: 'Ik luister…', sayScore: 'Score',
    closetTitle: 'Anbessa’s kledingkast', closetSub: 'Kleed Anbessa aan en deel!', keepGoing: 'Ga zo door!',
    back: 'Terug', playAll: 'Alles afspelen', stop: 'Stop', pace_slow: 'Langzaam', pace_normal: 'Normaal', pace_fast: 'Snel',
    exploreHeader: 'Letterontdekker', exploreHeaderSub: 'Kies een klinker en tik op een familie om te horen',
    exploreFamilyTitle: 'De {name}-familie', exploreFamilySub: 'Zeven vormen, één letter — tik om elke te horen',
    closetShort: 'Kledingkast', teeShort: 'T-shirtwinkel', wordsShort: 'Eerste woorden', explorerShort: 'Ontdek', classicShort: 'Klassiek', practiceShort: 'Oefenen', familyShort: 'Familie', fvShort: 'Familiestem', nameShort: 'Mijn naam', grownupsShort: 'Volwassenen', giftShort: 'Cadeau', reviewShort: 'Beoordeling',
    nameTitle: 'Schrijf je naam', nameSub: 'Spel hem in Fidel, één klank per keer',
    nameHint: 'Kies hieronder een klinker, tik dan op letters om je naam te spellen.',
    namePlay: 'Hoor de naam', nameBackspace: 'Laatste letter verwijderen', nameClear: 'Wissen', nameVowel: 'Klinker', nameLetters: 'Letters', nameShare: 'Mijn naam delen',
    namePrivacy: 'De kaart wordt op dit apparaat gemaakt. Er wordt niets gedeeld tenzij je op Delen tikt.',
    fvTitle: 'Familiestem', fvSub: 'Laat Anbessa spreken met de stem van een dierbare', fvWhoSpeaks: 'Wie spreekt er?', fvDefault: 'Standaard', fvImport: 'Een stem importeren', fvForGrownups: 'Voor volwassenen', fvRecordBtn: 'Een nieuwe stem opnemen', fvNoMic: 'Opnemen heeft een microfoon nodig — gebruik een telefoon of tablet.',
    streakDays: '{n} dagen op rij', chapterDone: 'Hoofdstuk {n} voltooid!', earnedItem: 'Anbessa kreeg {item}!', shareMilestone: '{name} leerde {n} letters!',
    huntShort: 'Dagelijkse jacht', huntTitle: 'Dagelijkse letterjacht', huntSub: 'Jibby heeft de letters verstopt! Vind ze op het gehoor',
    huntFind: 'Vind de letter die zegt', huntListen: 'Hoor het geluid nog eens', huntDoneTitle: 'Je hebt ze allemaal gevonden!',
    huntTreasure: 'Open de schat', huntTomorrow: 'Kom morgen terug — Jibby verstopt nieuwe letters!',
    huntGo: 'Jibby heeft de letters van vandaag verstopt — vind ze!', huntDoneChip: 'Klaar voor vandaag — morgen een nieuwe jacht!', huntFoundOne: 'gevonden', huntHidden: 'verstopte letter',
    pcShort: 'Kaartje', pcTitle: 'Spraakkaartje', pcSub: 'Stuur je stem naar iemand van wie je houdt',
    pcHint: 'Zeg “Selam!”, zeg je nieuwste letters of zing — opa en oma horen je graag.',
    pcRecord: 'Opnemen', pcStop: 'Stop', pcListen: 'Luister', pcRedo: 'Opnieuw opnemen', pcSend: 'Naar familie sturen', pcSendAgain: 'Opnieuw sturen',
    pcGateIntro: 'Versturen is voor volwassenen — jij kiest wie het krijgt.', pcShared: 'Kaartje verstuurd!', pcSaved: 'Opgeslagen! Deel het waar je wilt.',
    pcPrivacy: 'De opname blijft op dit apparaat. Hij reist alleen als een volwassene hem verstuurt.',
    celebPostcard: 'Stuur dit naar de familie!',
    calToday: 'Vandaag', hol_enkutatash: 'Enkutatash — Gelukkig nieuwjaar!', hol_meskel: 'Meskel — het feest van het Kruis', hol_genna: 'Genna — Vrolijk kerstfeest!', hol_timkat: 'Timkat — Driekoningen!', hol_adwa: 'Adwa-overwinningsdag', hol_eritrea: 'Eritrese onafhankelijkheidsdag',
    aFriend: 'Een vriend',
    bestStreak: 'Beste reeks',
    catchHint: 'Voer Anbessa voordat Jibby het pakt!',
    ccApply: 'Toepassen',
    ccBlurb: 'Heb je een code van een kerk, school of buurtgroep? Vul hem in zodat zij punten krijgen.',
    ccChange: 'Wijzigen',
    ccPh: 'bijv. DEBRE',
    ccThanks: 'Bedankt — je steunt',
    ccTitle: 'Buurtcode',
    challengeBack: 'Daag terug uit',
    challengeFriend: 'Daag een vriend uit',
    challengeFrom: '${who} daagt je uit!',
    challengeGone: 'Deze uitdaging is niet beschikbaar.',
    challengeLose: 'Net niet!',
    challengeScored: '${who} scoorde ${challenge.accuracy}% op ${levelTitle}. Kun jij het verslaan?',
    challengeShareText: 'Versla mijn Fidel Quest-score! Lukt het jou?',
    challengeStart: 'Doe de uitdaging',
    challengeTie: 'Gelijkspel!',
    challengeTitle: 'Een uitdaging!',
    challengeWin: 'Je wint!',
    champion: 'Fidel Kampioen - elke ster verdiend!',
    closetEmpty: 'Maak lessen af om hoeden, sjaals en capes voor Anbessa te verdienen!',
    dailyGift: 'Open Anbessa\'s cadeau',
    dismiss: 'Niet nu',
    feedHint: 'Sleep de letter die Kokeb zegt naar Anbessa',
    firstTry: 'Eerste keer',
    fvDefaultVoice: 'Terug naar de standaardstem',
    fvDelete: 'Stem verwijderen',
    fvEmpty: 'Nog geen familiestemmen. Neem er een op, of importeer een stem die een familielid je stuurde.',
    fvGateIntro: 'Opnemen is voor volwassenen — het gebruikt de microfoon.',
    fvGreetingShort: 'Hoi!',
    fvGreetingSlot: 'Begroeting',
    fvImportFail: 'Dat bestand is geen Fidel Quest-stem.',
    fvImported: 'Stem geïmporteerd!',
    fvNameLabel: 'Naam van de stem',
    fvNamePh: 'Wiens stem? bijv. Oma',
    fvNowSpeaking: 'Anbessa spreekt nu met deze stem',
    fvPrivacy: 'Stemmen blijven op dit apparaat. Er wordt niets geüpload — een stem reist alleen mee in het bestand dat je deelt.',
    fvRecordBlurb: 'Neem de letters in je eigen stem op en deel het bestand met je kind via WhatsApp. Een opa of oma ver weg kan opnemen voor kinderen hier — en andersom.',
    fvRecordHint: 'Tik op een letter om op te nemen, tik weer om te stoppen. Tik op ✓ om het terug te horen.',
    fvRecordTitle: 'Neem je stem op',
    fvShare: 'Deel met een kind',
    fvUseVoice: 'Gebruik het hier',
    giftAllDone: 'Je hebt alles verzameld - fijn dat je terug bent!',
    giftGot: 'Een nieuwe ${reward.name}!',
    giftTitle: 'Een cadeau van Anbessa!',
    goHome: 'Home',
    gpAccuracy: 'Nauwkeurigheid',
    gpCorrect: 'goed',
    gpHold: 'Houd me vast',
    gpHoldHint: 'Twee seconden ingedrukt houden',
    gpIntro: 'Dit gedeelte is voor volwassenen: voortgang en oefentips.',
    gpLessonStars: 'Lessterren',
    gpMastery: 'Letterbeheersing · ${events.length} antwoorden opgeslagen',
    gpMasteryLegend: 'Groen: sterk · Geel: bijna · Rood: hulp nodig · Grijs: nog niet geoefend. Quizzen oefenen nu de eersteordeletters.',
    gpOpenExplorer: 'Open in Verkenner',
    gpPlayerName: 'Naam speler',
    gpPlayerNameHint: 'Getoond bij uitdagingen die je naar vrienden stuurt. Optioneel — laat leeg om "Een vriend" te blijven. Het verlaat dit apparaat alleen in een uitdagingslink die je zelf deelt.',
    gpPlayerNamePh: 'bijv. Selam',
    gpReplayLevel: 'Speel Level ${tip.level} opnieuw',
    gpReset: 'Alle voortgang wissen…',
    gpResetConfirm: 'Sterren, records, eilanden en leergeschiedenis wissen?',
    gpResetNo: 'Behouden',
    gpResetYes: 'Ja, wissen',
    gpRunnerBest: 'Runner-record',
    gpTapNumber: 'Tik op het getal ${challenge.word}',
    gpTrouble: 'Lastige letters',
    gpTroubleFew: 'Nog niet genoeg gespeeld — kom terug na een paar spelletjes.',
    gpTroubleNone: 'Geen lastige letters nu. Goed gedaan!',
    grownupsSub: 'Voortgang, lastige letters en oefentips',
    installCta: 'Toevoegen',
    installHow: 'Hoe?',
    installIosHint: 'Tik op de Deel-knop en dan op \'Zet op beginscherm\'',
    installTitle: 'Zet Anbessa op je beginscherm',
    jumpToStep: 'Ga naar mijn volgende stap',
    learnSub: 'Leer elke letter, stap voor stap',
    learnTitle: 'Letterstappen',
    lettersLearned: '${stats.forms} / 231 letters geleerd',
    level: 'Level',
    linkCopied: 'Link gekopieerd!',
    masterInOrder: 'Op volgorde',
    masterLetters: 'letters',
    masterMixed: 'Gemengd',
    masterPause: 'Pauze',
    masterPlay: 'Speel',
    masterReshuffle: 'Opnieuw mengen',
    mixDone: 'Goed gemengd!',
    munched: 'Opgegeten!',
    myStep: 'Mijn stap',
    newReward: 'Nieuw!',
    nextVowel: 'Dan de volgende klinker',
    openCloset: 'Open Anbessa\'s kledingkast',
    practiceComplete: 'Oefening voltooid!',
    practicePraise: 'Die lastige letters worden sterker. Kokeb is trots op je!',
    remindBody: 'Kom vandaag een letter leren.',
    remindDesc: 'Elke middag een zacht duwtje om de reeks vol te houden.',
    remindTitle: 'Anbessa mist je!',
    remindTitleLabel: 'Dagelijkse herinnering',
    runAgain: 'Ren opnieuw',
    runBest: 'Beste',
    runBossAttack: 'Jibby de hyena valt aan!',
    runBossWin: 'Anbessa\'s letterkracht wint!',
    runMoveLeft: 'Ga naar links',
    runMoveRight: 'Ga naar rechts',
    runNewBest: 'Nieuw record!',
    runQuit: 'Stop de run',
    saysWord: 'zegt',
    scopeAll: 'Alle letters',
    scopeLabel: 'Welke letters',
    scopeLearned: 'Mijn letters',
    shareAnbessa: 'Deel Anbessa',
    shareSaved: 'Opgeslagen! Deel het overal.',
    shareShowOff: 'Laat het iedereen zien!',
    shareThanks: 'Bedankt voor het delen!',
    skyAllCleared: 'Alle vier de skylands vrij — Anbessa is een Fidel Kampioen!',
    skyAllFree: 'elk skyland is vrij!',
    skyBridge: 'de brug naar ${SESSIONS[st.session].place} is gegroeid!',
    skyCleared: 'Eiland vrij!',
    skyClearedSub: '${st.quiz.length} letters + 3 gered van Jibby ·',
    skyHold: 'Jibby houdt stevig vast — luister nog eens naar',
    skyLearnBtn: 'Leer Sessie ${nextLearn}',
    skyLearnPrompt: 'leer de letters van Sessie ${nextLearn} om de boom te wekken.',
    skyLearnTap: 'Tik op elke vrucht om de letter te horen —',
    skyListenFirst: 'Luister eerst naar ze allemaal',
    skyMap: 'Kaart',
    skyPlayBtn: 'Speel Level ${nextLearn}',
    skyPluck: 'Pluk de vrucht die zegt',
    skyReady: 'klaar voor Level ${nextLearn}: het test Sessies 1–${nextLearn}!',
    skyReplay: 'Opnieuw:',
    skyRescued: 'Gered!',
    skyRight: 'Ja!',
    skySession: 'Sessie',
    skyStartQuest: 'Start de quest van Level ${st.session}',
    skyStole: 'Jibby stal ${st.stolen.length} letters!',
    skyWinBack: 'Win de letter terug die zegt',
    skyWrong: 'Jibby giechelt — luister nog eens naar',
    skylandsTitle: 'Fidel Skylands',
    starHint: 'Schuif van ster naar ster en teken het sterrenbeeld',
    steerInto: 'Stuur Anbessa naar',
    teeGrownup: 'Bestellen opent een winkel — vraag een volwassene.',
    teeIntro: 'Verdien elk hoofdstuk een nieuw shirtontwerp — Anbessa draagt jouw alfabet! Bewaar de foto of vraag een volwassene om een echt shirt te bestellen.',
    teeLockedAt: 'Leer ${design.unlock} letters',
    teeNext: 'Leer nog ${Math.max(0, nextAt - families)} families om het volgende shirt te ontgrendelen!',
    teeOrdered: 'De winkel wordt geopend voor een volwassene...',
    teeSaveHint: 'Bewaar de foto en druk hem op elk shirt.',
    teeSaved: 'Ontwerp opgeslagen! Druk het overal.',
    teeUnlocked: 'Ontgrendeld!',
    whichLetter: 'Welke letter zegt',
    you: 'Jij',
  },
  no: {
    tagline: 'Lær Fidel-alfabetet med Anbessa',
    playLevel: 'Spill', backpack: 'Ryggsekk', home: 'Hjem', continue: 'Fortsett', gotIt: 'Skjønner',
    nice: 'Bra!', amazing: 'Fantastisk! {n} på rad!', notQuite: 'Ikke helt!', tryAgain: '— lytt og prøv igjen',
    yourTurn: 'Nå sier du det!', levelComplete: 'Nivå fullført!', playAgain: 'Spill igjen', listen: 'Lytt…',
    classicTitle: 'Klassisk spill', classicSub: 'Syng rekkene, tegn bokstaver, lær første ord',
    explorerTitle: 'Bokstavutforskeren', explorerSub: 'Trykk på en av de 231 stavelsene for å høre den',
    grownups: 'For voksne: fremgang og tips', practiceTitle: 'Stjerneøving',
    wordsTitle: 'Første ord', wordsSub: 'Hør ordet, trykk på bildet', whichStart: 'Hvilken bokstav begynner det med?',
    popHint: 'Sprett boblen!', familyDone: 'Familien mestret!', traceHint: 'Lytt og tegn bokstaven med fingeren',
    hearIt: 'Hør igjen', traceClear: 'Tøm', traceCheck: 'Sjekk', start: 'Start', langText: 'App-språk', langLearn: 'Språk å lære',
    teeTitle: 'Anbessas T-skjortebutikk', teeSub: 'Tjen og bruk dine alfabet-skjorter', teeOrder: 'Bestill en ekte skjorte', teeSave: 'Lagre designet',
    masterTitle: 'Fidel-mester', masterChart: 'Tabell', masterAuto: 'Auto-stemme', masterSay: 'Si det', masterAbugida: 'Abugida', masterPlayAbugida: 'Spill hele Abugidaen',
    sayGreat: 'Perfekt! ⭐', sayGood: 'Godt forsøk!', sayAgain: 'Si det igjen med meg', saySayIt: 'Si det', sayWithMe: 'Si med meg', sayListening: 'Jeg lytter…', sayScore: 'Poeng',
    closetTitle: 'Anbessas garderobe', closetSub: 'Kle på Anbessa og del!', keepGoing: 'Fortsett sånn!',
    back: 'Tilbake', playAll: 'Spill alle', stop: 'Stopp', pace_slow: 'Sakte', pace_normal: 'Normal', pace_fast: 'Rask',
    exploreHeader: 'Bokstavutforskeren', exploreHeaderSub: 'Velg en vokal og trykk på en familie for å høre den',
    exploreFamilyTitle: '{name}-familien', exploreFamilySub: 'Sju former, én bokstav — trykk for å høre hver',
    closetShort: 'Garderobe', teeShort: 'T-skjortebutikk', wordsShort: 'Første ord', explorerShort: 'Utforsk', classicShort: 'Klassisk', practiceShort: 'Øv', familyShort: 'Familie', fvShort: 'Familiestemme', nameShort: 'Mitt navn', grownupsShort: 'Voksne', giftShort: 'Gave', reviewShort: 'Vurdering',
    nameTitle: 'Skriv navnet ditt', nameSub: 'Stav det i Fidel, én lyd om gangen',
    nameHint: 'Velg en vokallyd nedenfor, trykk så på bokstaver for å stave navnet ditt.',
    namePlay: 'Hør navnet', nameBackspace: 'Fjern siste bokstav', nameClear: 'Tøm', nameVowel: 'Vokallyd', nameLetters: 'Bokstaver', nameShare: 'Del navnet mitt',
    namePrivacy: 'Kortet lages på denne enheten. Ingenting deles med mindre du trykker på Del.',
    fvTitle: 'Familiestemme', fvSub: 'La Anbessa snakke med stemmen til en du er glad i', fvWhoSpeaks: 'Hvem snakker?', fvDefault: 'Standard', fvImport: 'Importer en stemme', fvForGrownups: 'For voksne', fvRecordBtn: 'Spill inn en ny stemme', fvNoMic: 'Innspilling krever en mikrofon — bruk en telefon eller nettbrett.',
    streakDays: '{n} dager på rad', chapterDone: 'Kapittel {n} fullført!', earnedItem: 'Anbessa fikk {item}!', shareMilestone: '{name} lærte {n} bokstaver!',
    huntShort: 'Dagens jakt', huntTitle: 'Dagens bokstavjakt', huntSub: 'Jibby har gjemt bokstavene! Finn dem på lyden',
    huntFind: 'Finn bokstaven som sier', huntListen: 'Hør lyden igjen', huntDoneTitle: 'Du fant alle!',
    huntTreasure: 'Åpne skatten', huntTomorrow: 'Kom tilbake i morgen — Jibby gjemmer nye bokstaver!',
    huntGo: 'Jibby har gjemt dagens bokstaver — finn dem!', huntDoneChip: 'Ferdig for i dag — ny jakt i morgen!', huntFoundOne: 'funnet', huntHidden: 'gjemt bokstav',
    pcShort: 'Postkort', pcTitle: 'Talepostkort', pcSub: 'Send stemmen din til noen du er glad i',
    pcHint: 'Si «Selam!», si dine nyeste bokstaver eller syng — besteforeldre elsker å høre deg.',
    pcRecord: 'Ta opp', pcStop: 'Stopp', pcListen: 'Lytt', pcRedo: 'Ta opp igjen', pcSend: 'Send til familien', pcSendAgain: 'Send igjen',
    pcGateIntro: 'Sending er for voksne — du velger hvem som får det.', pcShared: 'Postkort sendt!', pcSaved: 'Lagret! Del det hvor som helst.',
    pcPrivacy: 'Opptaket blir på denne enheten. Det reiser bare når en voksen sender det.',
    celebPostcard: 'Send dette til familien!',
    calToday: 'I dag', hol_enkutatash: 'Enkutatash — Godt nytt år!', hol_meskel: 'Meskel — korsets høytid', hol_genna: 'Genna — God jul!', hol_timkat: 'Timkat — helligtrekongersdag!', hol_adwa: 'Adwa-seiersdagen', hol_eritrea: 'Eritreas uavhengighetsdag',
    aFriend: 'En venn',
    bestStreak: 'Beste rekke',
    catchHint: 'Gi Anbessa mat før Jibby napper den!',
    ccApply: 'Bruk',
    ccBlurb: 'Har du en kode fra en kirke, skole eller lokal gruppe? Skriv den inn så de får æren.',
    ccChange: 'Endre',
    ccPh: 'f.eks. DEBRE',
    ccThanks: 'Takk — du støtter',
    ccTitle: 'Fellesskapskode',
    challengeBack: 'Utfordre tilbake',
    challengeFriend: 'Utfordre en venn',
    challengeFrom: '${who} utfordrer deg!',
    challengeGone: 'Denne utfordringen er ikke tilgjengelig.',
    challengeLose: 'Så nære!',
    challengeScored: '${who} fikk ${challenge.accuracy}% på ${levelTitle}. Kan du slå det?',
    challengeShareText: 'Slå min Fidel Quest-poengsum! Klarer du det?',
    challengeStart: 'Ta utfordringen',
    challengeTie: 'Det ble uavgjort!',
    challengeTitle: 'En utfordring!',
    challengeWin: 'Du vinner!',
    champion: 'Fidel-mester - hver stjerne tjent!',
    closetEmpty: 'Fullfør leksjoner for å tjene hatter, skjerf og kapper til Anbessa!',
    dailyGift: 'Åpne Anbessas gave',
    dismiss: 'Ikke nå',
    feedHint: 'Dra bokstaven Kokeb sier til Anbessa',
    firstTry: 'Første forsøk',
    fvDefaultVoice: 'Tilbake til standardstemmen',
    fvDelete: 'Slett stemme',
    fvEmpty: 'Ingen familiestemmer ennå. Ta opp en, eller importer en stemme en slektning sendte deg.',
    fvGateIntro: 'Opptak er for voksne — det bruker mikrofonen.',
    fvGreetingShort: 'Hei!',
    fvGreetingSlot: 'Hilsen',
    fvImportFail: 'Den filen er ikke en Fidel Quest-stemme.',
    fvImported: 'Stemme importert!',
    fvNameLabel: 'Stemmenavn',
    fvNamePh: 'Hvem sin stemme? f.eks. Bestemor',
    fvNowSpeaking: 'Anbessa snakker nå med denne stemmen',
    fvPrivacy: 'Stemmer blir på denne enheten. Ingenting lastes opp — en stemme reiser bare i filen du velger å dele.',
    fvRecordBlurb: 'Ta opp bokstavene med din egen stemme, og del filen med barnet ditt på WhatsApp. En besteforelder langt unna kan ta opp for barn her — og motsatt.',
    fvRecordHint: 'Trykk på en bokstav for å ta den opp, trykk igjen for å stoppe. Trykk ✓ for å høre den.',
    fvRecordTitle: 'Ta opp stemmen din',
    fvShare: 'Del med et barn',
    fvUseVoice: 'Bruk den her',
    giftAllDone: 'Du har samlet alt - så glad for at du kom tilbake!',
    giftGot: 'En ny ${reward.name}!',
    giftTitle: 'En gave fra Anbessa!',
    goHome: 'Hjem',
    gpAccuracy: 'Treffsikkerhet',
    gpCorrect: 'riktig',
    gpHold: 'Hold meg',
    gpHoldHint: 'Trykk og hold i to sekunder',
    gpIntro: 'Dette området er for voksne: fremgangsdetaljer og øvingstips.',
    gpLessonStars: 'Leksjonsstjerner',
    gpMastery: 'Bokstavmestring · ${events.length} svar registrert',
    gpMasteryLegend: 'Grønn: sitter · Gul: på vei · Rød: trenger hjelp · Grå: ikke øvd ennå. Quizene øver nå på førsteordens bokstaver.',
    gpOpenExplorer: 'Åpne i Utforsker',
    gpPlayerName: 'Spillernavn',
    gpPlayerNameHint: 'Vises på utfordringer du sender til venner. Valgfritt — la det stå tomt for å være "En venn". Det forlater aldri denne enheten unntatt i en utfordringslenke du velger å dele.',
    gpPlayerNamePh: 'f.eks. Selam',
    gpReplayLevel: 'Spill nivå ${tip.level} på nytt',
    gpReset: 'Nullstill all fremgang…',
    gpResetConfirm: 'Slette stjerner, rekorder, øyer og læringshistorikk?',
    gpResetNo: 'Behold det',
    gpResetYes: 'Ja, slett',
    gpRunnerBest: 'Løper-rekord',
    gpTapNumber: 'Trykk på tallet ${challenge.word}',
    gpTrouble: 'Vanskelige bokstaver',
    gpTroubleFew: 'Ikke nok spilling ennå — kom tilbake etter noen spill.',
    gpTroubleNone: 'Ingen vanskelige bokstaver akkurat nå. Bra jobbet!',
    grownupsSub: 'Fremgang, vanskelige bokstaver og øvingstips',
    installCta: 'Legg til',
    installHow: 'Hvordan?',
    installIosHint: 'Trykk på Del-knappen, deretter \'Legg til på Hjem-skjerm\'',
    installTitle: 'Legg Anbessa til på hjem-skjermen',
    jumpToStep: 'Gå til mitt neste steg',
    learnSub: 'Lær hver bokstav, ett steg om gangen',
    learnTitle: 'Bokstavsteg',
    lettersLearned: '${stats.forms} / 231 bokstaver lært',
    level: 'Nivå',
    linkCopied: 'Lenke kopiert!',
    masterInOrder: 'I rekkefølge',
    masterLetters: 'bokstaver',
    masterMixed: 'Blandet',
    masterPause: 'Pause',
    masterPlay: 'Spill',
    masterReshuffle: 'Bland på nytt',
    mixDone: 'Flott blanding!',
    munched: 'Mumset!',
    myStep: 'Mitt steg',
    newReward: 'Ny!',
    nextVowel: 'Så neste vokal',
    openCloset: 'Åpne Anbessas garderobe',
    practiceComplete: 'Øving fullført!',
    practicePraise: 'De vanskelige bokstavene blir sterkere. Kokeb er stolt av deg!',
    remindBody: 'Kom og lær en bokstav i dag.',
    remindDesc: 'Et vennlig dytt hver ettermiddag for å holde rekka i gang.',
    remindTitle: 'Anbessa savner deg!',
    remindTitleLabel: 'Daglig påminnelse',
    runAgain: 'Løp igjen',
    runBest: 'Best',
    runBossAttack: 'Jibby hyenen angriper!',
    runBossWin: 'Anbessas bokstavkraft vinner!',
    runMoveLeft: 'Beveg til venstre',
    runMoveRight: 'Beveg til høyre',
    runNewBest: 'Ny rekord!',
    runQuit: 'Avslutt løp',
    saysWord: 'sier',
    scopeAll: 'Alle bokstaver',
    scopeLabel: 'Hvilke bokstaver',
    scopeLearned: 'Mine bokstaver',
    shareAnbessa: 'Del Anbessa',
    shareSaved: 'Lagret! Del den hvor som helst.',
    shareShowOff: 'Vis det til alle!',
    shareThanks: 'Takk for at du delte!',
    skyAllCleared: 'Alle fire himmelland ryddet — Anbessa er en Fidel-mester!',
    skyAllFree: 'hvert himmelland er fritt!',
    skyBridge: 'broen til ${SESSIONS[st.session].place} har vokst!',
    skyCleared: 'Øy ryddet!',
    skyClearedSub: '${st.quiz.length} bokstaver + 3 reddet fra Jibby ·',
    skyHold: 'Jibby holder hardt fast — hør igjen etter',
    skyLearnBtn: 'Lær økt ${nextLearn}',
    skyLearnPrompt: 'lær bokstavene i økt ${nextLearn} for å vekke treet.',
    skyLearnTap: 'Trykk på hver frukt for å høre bokstaven —',
    skyListenFirst: 'Hør på alle først',
    skyMap: 'Kart',
    skyPlayBtn: 'Spill nivå ${nextLearn}',
    skyPluck: 'Plukk frukten som sier',
    skyReady: 'klar for nivå ${nextLearn}: det tester øktene 1–${nextLearn}!',
    skyReplay: 'Spill på nytt:',
    skyRescued: 'Reddet!',
    skyRight: 'Ja!',
    skySession: 'Økt',
    skyStartQuest: 'Start nivå ${st.session}-oppdrag',
    skyStole: 'Jibby stjal ${st.stolen.length} bokstaver!',
    skyWinBack: 'Vinn tilbake den som sier',
    skyWrong: 'Jibby fniser — hør igjen etter',
    skylandsTitle: 'Fidel Skylands',
    starHint: 'Skyv fra stjerne til stjerne og tegn stjernebildet',
    steerInto: 'Styr Anbessa inn i',
    teeGrownup: 'Bestilling åpner en butikk — spør en voksen.',
    teeIntro: 'Tjen et nytt skjortedesign hvert kapittel — Anbessa har på seg alfabetet ditt! Lagre bildet eller be en voksen bestille en ekte skjorte.',
    teeLockedAt: 'Lær ${design.unlock} bokstaver',
    teeNext: 'Lær ${Math.max(0, nextAt - families)} familier til for å låse opp neste skjorte!',
    teeOrdered: 'Åpner butikken for en voksen...',
    teeSaveHint: 'Lagre bildet og trykk det på hvilken som helst skjorte.',
    teeSaved: 'Design lagret! Trykk det hvor som helst.',
    teeUnlocked: 'Låst opp!',
    whichLetter: 'Hvilken bokstav sier',
    you: 'Du',
  },
  fr: {
    tagline: "Apprends l'alphabet Fidel avec Anbessa",
    playLevel: 'Jouer', backpack: 'Sac à dos', home: 'Accueil', continue: 'Continuer', gotIt: 'Compris',
    nice: 'Bravo !', amazing: 'Fantastique ! {n} d’affilée !', notQuite: 'Pas tout à fait !', tryAgain: '— écoute et réessaie',
    yourTurn: "À toi de le dire !", levelComplete: 'Niveau terminé !', playAgain: 'Rejouer', listen: 'Écoute…',
    classicTitle: 'Jeu Classique', classicSub: 'Chante les ordres, trace les lettres, apprends les premiers mots',
    explorerTitle: 'Explorateur de Lettres', explorerSub: 'Touche une des 231 syllabes pour l’entendre',
    grownups: 'Pour les grands : progrès et astuces', practiceTitle: 'Entraînement Étoile',
    wordsTitle: 'Premiers Mots', wordsSub: 'Écoute le mot, touche son image', whichStart: 'Par quelle lettre ça commence ?',
    popHint: 'Fais éclater la bulle !', familyDone: 'Famille maîtrisée !', traceHint: 'Écoute, puis trace la lettre avec ton doigt',
    hearIt: 'Réécouter', traceClear: 'Effacer', traceCheck: 'Vérifier', start: 'Départ', langText: "Langue de l'appli", langLearn: 'Langue à apprendre',
    teeTitle: 'Boutique T-shirt Anbessa', teeSub: 'Gagne et porte tes t-shirts de l’alphabet', teeOrder: 'Commander un vrai t-shirt', teeSave: 'Enregistrer le motif',
    masterTitle: 'Maître du Fidel', masterChart: 'Tableau', masterAuto: 'Voix auto', masterSay: 'Dis-le', masterAbugida: 'Abugida', masterPlayAbugida: "Lire tout l'Abugida",
    sayGreat: 'Parfait ! ⭐', sayGood: 'Bien essayé !', sayAgain: 'Répète avec moi', saySayIt: 'Dis-le', sayWithMe: 'Dis avec moi', sayListening: "J'écoute…", sayScore: 'Score',
    closetTitle: "L'armoire d'Anbessa", closetSub: 'Habille Anbessa et partage !', keepGoing: 'Continue !',
    back: 'Retour', playAll: 'Tout jouer', stop: 'Stop', pace_slow: 'Lent', pace_normal: 'Normal', pace_fast: 'Rapide',
    exploreHeader: 'Explorateur de Lettres', exploreHeaderSub: 'Choisis une voyelle, puis touche une famille pour l’entendre',
    exploreFamilyTitle: 'La famille {name}', exploreFamilySub: 'Sept formes, une lettre — touche pour entendre chacune',
    closetShort: 'Armoire', teeShort: 'Boutique T-shirt', wordsShort: 'Premiers Mots', explorerShort: 'Explorer', classicShort: 'Classique', practiceShort: 'Entraînement', familyShort: 'Famille', fvShort: 'Voix de Famille', nameShort: 'Mon nom', grownupsShort: 'Adultes', giftShort: 'Cadeau', reviewShort: 'Avis',
    nameTitle: 'Écris ton nom', nameSub: 'Épelle-le en Fidel, un son à la fois',
    nameHint: 'Choisis un son de voyelle ci-dessous, puis touche les lettres pour écrire ton nom.',
    namePlay: 'Entendre le nom', nameBackspace: 'Enlever la dernière lettre', nameClear: 'Effacer', nameVowel: 'Voyelle', nameLetters: 'Lettres', nameShare: 'Partager mon nom',
    namePrivacy: 'La carte est créée sur cet appareil. Rien n’est partagé sauf si tu touches Partager.',
    fvTitle: 'Voix de Famille', fvSub: 'Fais parler Anbessa avec la voix d’un proche', fvWhoSpeaks: 'Qui parle ?', fvDefault: 'Par défaut', fvImport: 'Importer une voix', fvForGrownups: 'Pour les grands', fvRecordBtn: 'Enregistrer une nouvelle voix', fvNoMic: 'L’enregistrement nécessite un microphone — utilise un téléphone ou une tablette.',
    streakDays: '{n} jours d’affilée', chapterDone: 'Chapitre {n} terminé !', earnedItem: 'Anbessa a obtenu {item} !', shareMilestone: '{name} a appris {n} lettres !',
    huntShort: 'Chasse du jour', huntTitle: 'Chasse aux lettres du jour', huntSub: 'Jibby a caché les lettres ! Trouve-les à l’oreille',
    huntFind: 'Trouve la lettre qui dit', huntListen: 'Réécouter le son', huntDoneTitle: 'Tu les as toutes trouvées !',
    huntTreasure: 'Ouvre le trésor', huntTomorrow: 'Reviens demain — Jibby cachera de nouvelles lettres !',
    huntGo: 'Jibby a caché les lettres du jour — trouve-les !', huntDoneChip: 'Fini pour aujourd’hui — nouvelle chasse demain !', huntFoundOne: 'trouvée', huntHidden: 'lettre cachée',
    pcShort: 'Carte postale', pcTitle: 'Carte postale vocale', pcSub: 'Envoie ta voix à quelqu’un que tu aimes',
    pcHint: 'Dis « Selam ! », dis tes nouvelles lettres ou chante — les grands-parents adorent t’entendre.',
    pcRecord: 'Enregistrer', pcStop: 'Stop', pcListen: 'Écouter', pcRedo: 'Réenregistrer', pcSend: 'Envoyer à la famille', pcSendAgain: 'Renvoyer',
    pcGateIntro: 'L’envoi est pour les grands — tu choisis qui la reçoit.', pcShared: 'Carte envoyée !', pcSaved: 'Enregistrée ! Partage-la où tu veux.',
    pcPrivacy: 'L’enregistrement reste sur cet appareil. Il ne voyage que si un adulte l’envoie.',
    celebPostcard: 'Envoie ça à la famille !',
    calToday: 'Aujourd’hui', hol_enkutatash: 'Enkutatash — Bonne année !', hol_meskel: 'Meskel — la fête de la Croix', hol_genna: 'Genna — Joyeux Noël !', hol_timkat: 'Timkat — l’Épiphanie !', hol_adwa: 'Jour de la victoire d’Adwa', hol_eritrea: 'Fête de l’indépendance de l’Érythrée',
    aFriend: 'Un ami',
    bestStreak: 'Meilleure série',
    catchHint: 'Nourris Anbessa avant que Jibby ne l\'attrape !',
    ccApply: 'Valider',
    ccBlurb: 'Tu as un code d\'une église, d\'une école ou d\'un groupe ? Saisis-le pour qu\'ils soient crédités.',
    ccChange: 'Changer',
    ccPh: 'ex. DEBRE',
    ccThanks: 'Merci — tu soutiens',
    ccTitle: 'Code communautaire',
    challengeBack: 'Défier en retour',
    challengeFriend: 'Défier un ami',
    challengeFrom: '${who} te lance un défi !',
    challengeGone: 'Ce défi n\'est plus disponible.',
    challengeLose: 'Si près !',
    challengeScored: '${who} a fait ${challenge.accuracy}% au niveau ${levelTitle}. Peux-tu le battre ?',
    challengeShareText: 'Bats mon score à Fidel Quest ! Tu peux ?',
    challengeStart: 'Relever le défi',
    challengeTie: 'Égalité !',
    challengeTitle: 'Un défi !',
    challengeWin: 'Tu gagnes !',
    champion: 'Champion du Fidel - toutes les étoiles gagnées !',
    closetEmpty: 'Termine des leçons pour gagner des chapeaux, écharpes et capes pour Anbessa !',
    dailyGift: 'Ouvrir le cadeau d\'Anbessa',
    dismiss: 'Plus tard',
    feedHint: 'Fais glisser la lettre que dit Kokeb vers Anbessa',
    firstTry: 'Du premier coup',
    fvDefaultVoice: 'Revenir à la voix par défaut',
    fvDelete: 'Supprimer la voix',
    fvEmpty: 'Pas encore de voix de famille. Enregistres-en une, ou importe la voix qu\'un proche t\'a envoyée.',
    fvGateIntro: 'L\'enregistrement est pour les grands — il utilise le micro.',
    fvGreetingShort: 'Coucou !',
    fvGreetingSlot: 'Salutation',
    fvImportFail: 'Ce fichier n\'est pas une voix Fidel Quest.',
    fvImported: 'Voix importée !',
    fvNameLabel: 'Nom de la voix',
    fvNamePh: 'La voix de qui ? ex. Mamie',
    fvNowSpeaking: 'Anbessa parle maintenant avec cette voix',
    fvPrivacy: 'Les voix restent sur cet appareil. Rien n\'est envoyé — une voix ne voyage que dans le fichier que tu choisis de partager.',
    fvRecordBlurb: 'Enregistre les lettres avec ta propre voix, puis partage le fichier avec ton enfant par WhatsApp. Un grand-parent loin peut enregistrer pour les enfants ici — et vice versa.',
    fvRecordHint: 'Touche une lettre pour l\'enregistrer, retouche pour arrêter. Touche ✓ pour la réécouter.',
    fvRecordTitle: 'Enregistre ta voix',
    fvShare: 'Partager avec un enfant',
    fvUseVoice: 'L\'utiliser ici',
    giftAllDone: 'Tu as tout collectionné - trop contente que tu sois revenu !',
    giftGot: 'Un nouveau ${reward.name} !',
    giftTitle: 'Un cadeau d\'Anbessa !',
    goHome: 'Accueil',
    gpAccuracy: 'Précision',
    gpCorrect: 'correct',
    gpHold: 'Maintiens-moi',
    gpHoldHint: 'Appuie et maintiens deux secondes',
    gpIntro: 'Cette zone est pour les grands : détails des progrès et conseils.',
    gpLessonStars: 'Étoiles des leçons',
    gpMastery: 'Maîtrise des lettres · ${events.length} réponses enregistrées',
    gpMasteryLegend: 'Vert : solide · Jaune : en progrès · Rouge : à revoir · Gris : pas encore travaillé. Les quiz travaillent pour l\'instant les lettres du premier ordre.',
    gpOpenExplorer: 'Ouvrir dans l\'Explorateur',
    gpPlayerName: 'Nom du joueur',
    gpPlayerNameHint: 'Affiché sur les défis envoyés aux amis. Facultatif — laisse vide pour rester « Un ami ». Il ne quitte jamais cet appareil, sauf dans un lien de défi que tu choisis de partager.',
    gpPlayerNamePh: 'ex. Selam',
    gpReplayLevel: 'Rejouer le niveau ${tip.level}',
    gpReset: 'Effacer tous les progrès…',
    gpResetConfirm: 'Effacer étoiles, records, îles et historique d\'apprentissage ?',
    gpResetNo: 'Garder',
    gpResetYes: 'Oui, effacer',
    gpRunnerBest: 'Record du Runner',
    gpTapNumber: 'Touche le nombre ${challenge.word}',
    gpTrouble: 'Lettres difficiles',
    gpTroubleFew: 'Pas encore assez joué — reviens après quelques parties.',
    gpTroubleNone: 'Aucune lettre difficile pour l\'instant. Bravo !',
    grownupsSub: 'Progrès, lettres difficiles et conseils de pratique',
    installCta: 'Ajouter',
    installHow: 'Comment ?',
    installIosHint: 'Touche le bouton Partager, puis « Sur l\'écran d\'accueil »',
    installTitle: 'Ajoute Anbessa à ton écran d\'accueil',
    jumpToStep: 'Aller à mon étape suivante',
    learnSub: 'Apprends chaque lettre, une étape à la fois',
    learnTitle: 'Les étapes des lettres',
    lettersLearned: '${stats.forms} / 231 lettres apprises',
    level: 'Niveau',
    linkCopied: 'Lien copié !',
    masterInOrder: 'Dans l\'ordre',
    masterLetters: 'lettres',
    masterMixed: 'Mélangées',
    masterPause: 'Pause',
    masterPlay: 'Lire',
    masterReshuffle: 'Remélanger',
    mixDone: 'Beau mélange !',
    munched: 'Miam !',
    myStep: 'Mon étape',
    newReward: 'Nouveau !',
    nextVowel: 'Puis la voyelle suivante',
    openCloset: 'Ouvrir la garde-robe d\'Anbessa',
    practiceComplete: 'Entraînement terminé !',
    practicePraise: 'Ces lettres difficiles deviennent plus fortes. Kokeb est fier de toi !',
    remindBody: 'Viens apprendre une lettre aujourd\'hui.',
    remindDesc: 'Un petit rappel chaque après-midi pour garder la série.',
    remindTitle: 'Anbessa s\'ennuie de toi !',
    remindTitleLabel: 'Rappel quotidien',
    runAgain: 'Recourir',
    runBest: 'Record',
    runBossAttack: 'Jibby la hyène attaque !',
    runBossWin: 'Le pouvoir des lettres d\'Anbessa gagne !',
    runMoveLeft: 'Aller à gauche',
    runMoveRight: 'Aller à droite',
    runNewBest: 'Nouveau record !',
    runQuit: 'Quitter la course',
    saysWord: 'dit',
    scopeAll: 'Toutes les lettres',
    scopeLabel: 'Quelles lettres',
    scopeLearned: 'Mes lettres',
    shareAnbessa: 'Partager Anbessa',
    shareSaved: 'Enregistré ! Partage-le partout.',
    shareShowOff: 'Montre à tout le monde !',
    shareThanks: 'Merci d\'avoir partagé !',
    skyAllCleared: 'Les quatre îles célestes libérées — Anbessa est Champion du Fidel !',
    skyAllFree: 'toutes les îles célestes sont libres !',
    skyBridge: 'le pont vers ${SESSIONS[st.session].place} a grandi !',
    skyCleared: 'Île libérée !',
    skyClearedSub: '${st.quiz.length} lettres + 3 sauvées de Jibby ·',
    skyHold: 'Jibby s\'accroche fort — réécoute pour',
    skyLearnBtn: 'Apprendre la session ${nextLearn}',
    skyLearnPrompt: 'apprends les lettres de la session ${nextLearn} pour réveiller l\'arbre.',
    skyLearnTap: 'Touche chaque fruit pour entendre sa lettre —',
    skyListenFirst: 'Écoute-les toutes d\'abord',
    skyMap: 'Carte',
    skyPlayBtn: 'Jouer le niveau ${nextLearn}',
    skyPluck: 'Cueille le fruit qui dit',
    skyReady: 'prêt pour le niveau ${nextLearn} : il teste les sessions 1–${nextLearn} !',
    skyReplay: 'Rejouer :',
    skyRescued: 'Sauvée !',
    skyRight: 'Oui !',
    skySession: 'Session',
    skyStartQuest: 'Commencer la quête du niveau ${st.session}',
    skyStole: 'Jibby a volé ${st.stolen.length} lettres !',
    skyWinBack: 'Récupère celle qui dit',
    skyWrong: 'Jibby ricane — réécoute pour',
    skylandsTitle: 'Fidel Skylands',
    starHint: 'Glisse d\'étoile en étoile et dessine la constellation',
    steerInto: 'Dirige Anbessa vers',
    teeGrownup: 'Commander ouvre une boutique — demande à un grand.',
    teeIntro: 'Gagne un nouveau design de t-shirt à chaque chapitre — Anbessa porte ton alphabet ! Enregistre l\'image ou demande à un grand de commander un vrai t-shirt.',
    teeLockedAt: 'Apprends ${design.unlock} lettres',
    teeNext: 'Apprends ${Math.max(0, nextAt - families)} familles de plus pour débloquer le prochain t-shirt !',
    teeOrdered: 'Ouverture de la boutique pour un grand...',
    teeSaveHint: 'Enregistre l\'image et imprime-la sur n\'importe quel t-shirt.',
    teeSaved: 'Design enregistré ! Imprime-le partout.',
    teeUnlocked: 'Débloqué !',
    whichLetter: 'Quelle lettre dit',
    you: 'Toi',
  },
}
